language: java
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- "./gradlew build"
deploy:
- provider: script
  script: "./gradlew bintrayUpload"
  skip_cleanup: true
  on:
    repo: hmcts/sscs-common
    tags: true
- provider: releases
  api_key:
    secure: m1tGlk4SAw4skqwyOp2R+RCfPVgtT2AFnVAdkaylDlEyqZfT/I0QcmNuHiN52ChweecX5wG5qAhPtgu+zfIHavciwn48wh3fFgKq6hVW4pELnsP3Ow2plMr0xgetklTfHDkFii7Nl9U7AGKXM9PNAQIuU5MiwZISQS0oc/cnlgrsgM9ON7V3xYiQG4LoMoZ/8K3hlaGspBiVuBnaF0pp7CfiBU8Q7sQRhyQf39gC/2gBUH8Wi6rBiXkOOGMioJm5tk0g5RSoojp+po7kBinqNjffjZSq15BgbQxjwnuNxOaMRi8vM4lVR2ta/0rQlkb4mvKpJ33UezcIs3HLkZUV13yU7vmalxJrDAVC9+IQy9P7o0B29T63orqPyHgQGEdySvhi75QyK/ii/sOY7zI9akM31na3Aujd+bjUQp0ZaowC5q8Eg/t40KQJ2Xr+qeIGO0nUvXvGYE1ikm3a1OEET6Gtn77xKSMfpK6gsR7yuKwNXii5GXko7xN+27Li6+BODxUOVost04DutLuZCDmhYfP+hwT8R0JIn3One1i4ZI5bKYu2QQODrsYU8gqzElcOXENJuBwGM6ZmdFURdwuuLzkwXlMXZsALx6RTVItiyljfH2jwZifuLiZb3GDE1lrGWvkyWlnp17jbujMhxVqN2M1ssnZ6rHKI9NgCdl7nzEw=
  file: build/libs/sscs-common-*.jar
  file_glob: true
  skip_cleanup: true
  on:
    repo: hmcts/sscs-common
    tags: true
env:
  global:
  - secure: CLtmMhobJAN2m8o6I3TjKuOVTro+K/aRSkOiZTXgNvJWAbpHnE58yfLvtfw95z8VNrRDQD4RBMcKJL/becU6PUU1xja17L5Rk0D5CwkzaAjz/aLknqNCjyODTgoyxhrJTNlj/XvRPgHXx8slXXHSKxYrbfHy4q1vor49Bs+uF5sUs8MWozoammQfkf+c4ayjfjTmurl2UCdQ4SPVRL+XV92rkQPcmKtp0XsWVSm33J/EZjNvurFeDVKQQUJ5gNuKSm5fM3grMB1uGAGMwTrwj3I2ExJ/F6ApCGO50LtYuR1eITs7+eDwCcqes5YbK2Tb/LiLRNila4O+W59HE9t+Nh22X4XfLNJV50SrzW69ad+Ru+wORHR6aXhTWxhG4iHr/xQ5tKQlNPYO11op3dw+j8iMDXba0pyc62e4xyPgZDxcgWXHMwhSJusEN3yxUAGZWQBbRhCdHYqkvPTynhd1MvHUCRo+OwA+i6v+OwbHTtsBnwJSfYyRXSlTiZp7GO0zWXdI1rExAUC8hiqNqeFo8mDxKr1BrfPP7ELza0Q0wgxUszNJpHzDQj9kUyPXMkjo5GugSg2llfI5Id09Thl151+zhdgJVvGC0J5tCedw/G0w3jDooDpsNTmc6aKHn+pcbOiDWvnF8LaaH0jtShB9ylNnLTzvUUR4HS0/tiLE7Ac=
  - secure: kXk1g2t70/pLXMm8Zn7dV/GaebZRSjhHz5lUOg9KJPBgdOX5tEGSuuZxpl1MPv3xBHCVOZLAeXv5vh2+io1LtbtRpB2I/2s888r2HI0+BVMfokjzM4ihVeaXXKbGAXyFH+euGnu1apvQyvPYlXuFGuxEhK+Ihc5UH5SmbJcKKN3+oxZEg6jGv2Fqu9bQNQzfxYzvyZOJqnXs3r6vovadT0dusDPVERDpCXOXjwT9xCNoGhLOmSD78cxJfr8cDJMT56PJHrt3wCXhwjkjxzjvrsEKCHPEy7cwDZpyJmPfDno4XT9rXP9WvBegGgKdxZE7dJQlC7F0yZYftSKBviAOsmSrSRZBpiT8qtKhcGPTM5kVXn77OU9h5ekRNrWpVI5m/nqhUUVT6OM2n2h38HXMxtPONl0n2ayWtBaH/3ycfb3Q8HcnkIle/xgD3zKJNiWzZp6eg1AfK9awpEjVfBnyTlzk+ALWrkbTIV5BEy0B1yFxQxdi5Mte2x55WLFpKlKfcpMjc5vQffz2gL+fGq1jowixfiwDZhQ88QjTTeIZ1qFmLTOr6DBnYLmsmHPg6laKqb0BvaEhSikKLaGByqU62Asqrz+VRRn+8CguX2hAelmBlYJQRXGLjlz5gxJkNcOjqaqPyysaOcT8PH8MNk23VB/WM3ZvOGivFFR5WScKfzo=
