language: java
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- "./gradlew build"
deploy:
- provider: script
  script: "./gradlew bintrayUpload"
  skip_cleanup: true
  on:
    repo: hmcts/sscs-common
    tags: true
- provider: releases
  api_key:
    secure: IR4zECv3MVZBkFM7hrMIWa0jUMoeqNNOxrj1mSkZpKL3UN+3IAjEGruVPT2RS6IRGkQgPdAtwM1mgfRS23Oj/LtXS9Ezw8RUHYV9OR/T7+h8qr4PnGkQJ044mnnafE3tRZ69Uzeit8MEY7L+S56jqCPRcP85+Q58xuVifLu2/vD9PxDbpcAdPtyTrx59eR7df4qe0jvDQiXLpx1MTg+NUhWAtOdJu3Hz2zRXd/3+46mGz2QJzJsdHogyIfrABqBfWybg1qZTfstae2tvSmI0CwjOKFJZVdMsEweQ49/N99CErrUSYmEyR2tw3Lmv8X2s6Y5HO64R9BnIxEemtYP4fsxKAa/r/IeMs5n6MnaDaRyuWNqxY7e2KlSob7W+fzsVe8twKlA+t/tqB2GmbGvmsF8J4p+jpRPcuCOAFd+NFgpYIL+BCXYCxSQIrS6mtcUnF1j7jJa2tZPS7SDAm0e1IIkV3gd60UZgNnU3f2NRGDUJL912S9Sd/I6UStMxOj2Qe5Ka+daghc97gmZvChWeq8r7desbMPQlCQAnnP4YmmWbZi7w9jAe3pVNhm5L2I5fS+gnSkm8ext8RmZd/IkcCAZ75bV8rzkjRlFCpoR+eeBLiY3sqa9BLsU7wNwxLNK2zkdbOAuBNg2fK0ariFQDXmpQjlmfofZJWsmP2YQZOIM=
  file: build/libs/sscs-common-*.jar
  file_glob: true
  skip_cleanup: true
  on:
    repo: hmcts/sscs-common
    tags: true
env:
  global:
  - secure: STeSRipnfrxoxJGAeU+ToMpmlMkqYdvsL9dJY/Ju+IXNFxURt3rBpmWINFSebArOuS9i0IKz2VnYvODFlKgOc17+C2Y4EblGXwp25uq/EUufFbNG18jM6ulL8pHTqQWWnlQXg9bw/sMbNryTLRUmg7UGAS8Zikk48+vx4BSrmd1CB2DpLm5DR/PpyAvITYa7dQunxITsd/dUsx97W5cgjPXlQVumSC6od0tea3I8rE4unX3jVEsZzI3DayeCDIA+GPKHxoklRycWONEIAW4c/C3E/zV5f4nuzV4DwF+qb8ihu7jnVys0xIA+dMosF+1aFrU0/VDK3j8uHtBT1it2h+pJar6luAagDtVE9EtkR6dg5KSZhTMG3GZdkoSr340FdVNDqcT5IzShYDRFq3WUw9MBDQ/K6HZdtohJ6DhjuNGR6gzjSumvXuIhBSQZJ5bTa3uRby1ihlkTo/ZeYVhCKy65i/bYTSRDWf3OTyFrL/T0BNtrWvxN90gT6Dw25U/ptz0wNGcoG9X+2OXva7ur6NVNIxuio1qtKk4RsbVql0BVPEJJiIBGz+03RelgKJvnaaxfInN76wBsMLml5SQxDW2L47A9+7IXUPaPlu8gHmN4jxbYMV3g3YtbRj4Y4uKu7gMdEA53ChOh75lYqHnszVvL7jd58I6+FlNJZbUPEuY=
  - secure: KDTUS+AgKyLrGBfqapzwcy+b7Div1VmMcEUtOyohxw0hkhURXy5wh3rV0CJzIkVSazE0k6mUP0sNGlvUEwW90MV8OHN96QY0/UgAqchUFe4/OrHwG1ROTXiewZue8nRf8CKGt5Sez7Hd1bgYIkeXPzFQ0qSmvKnapls7o8LRFwT2zVvJu4K+tROh3/ljzcH02q9Fdz9c5iiIQPr0BdgdEi8VPa5HMVgWyEQFzTIcXsadTdYtXLE2UcILUh4giKXlCMWu4DWYrmzSs5NdfUcznWIMx3h1u1JHNKghA2FVmW6nlE2HyW2aKYuoIbHGJaKL/6tSSGyTkQ7sgtcmlbCWUVwCUTD6FCyVhS2Asd5Y/joNzcwuEVYZ30ReCTElO67xP+HxMOVP2ILkJt3U9MRukPgk5Slum8nHWGrYRt/A5/uAabmcHw9JauyfaVz2fNmM7Z2WdQsaAlq8t5mJZuivU+NGrgnKTPA4f0GLWtls7mLqDDyAh+2lZPa6dV7oi/16iBRZn+XvLIGjji6Pg0pnsRCT8jt/UGggNJEdV4YGIqXYACpAirTUJUPs7SL9/IelqwZi6xHlZJsaB+kwBTiwvUG+dSyOCHs1wvhpuYyagQdmCxGvos2UVY2nr6tRoAVx4YMrtGLmgJqW+BaUhZqZk6JZBaqvJsP+PuILsVy0BCM=
