package uk.gov.hmcts.reform.sscs.ccd.access;

import com.google.common.collect.HashMultimap;
import com.google.common.collect.SetMultimap;
import uk.gov.hmcts.ccd.sdk.api.HasAccessControl;
import uk.gov.hmcts.ccd.sdk.api.HasRole;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
public class ClerkCruPlus4RolesOesmduAccess implements HasAccessControl {
    @Override
    public SetMultimap<HasRole, Permission> getGrants() {
        SetMultimap<HasRole, Permission> grants = HashMultimap.create();
        grants.put(UserRole.CASEWORKER_SSCS_CLERK, Permission.C);
        grants.put(UserRole.CASEWORKER_SSCS_CLERK, Permission.R);
        grants.put(UserRole.CASEWORKER_SSCS_CLERK, Permission.U);
        grants.put(UserRole.CASEWORKER_SSCS_DWPRESPONSEWRITER, Permission.C);
        grants.put(UserRole.CASEWORKER_SSCS_DWPRESPONSEWRITER, Permission.R);
        grants.put(UserRole.CASEWORKER_SSCS_DWPRESPONSEWRITER, Permission.U);
        grants.put(UserRole.CASEWORKER_SSCS_HMRCRESPONSEWRITER, Permission.C);
        grants.put(UserRole.CASEWORKER_SSCS_HMRCRESPONSEWRITER, Permission.R);
        grants.put(UserRole.CASEWORKER_SSCS_HMRCRESPONSEWRITER, Permission.U);
        grants.put(UserRole.CASEWORKER_SSCS_SUPERUSER, Permission.C);
        grants.put(UserRole.CASEWORKER_SSCS_SUPERUSER, Permission.R);
        grants.put(UserRole.CASEWORKER_SSCS_SUPERUSER, Permission.U);
        grants.put(UserRole.CASEWORKER_SSCS_SUPERUSER, Permission.D);
        grants.put(UserRole.CASEWORKER_SSCS_SYSTEMUPDATE, Permission.C);
        grants.put(UserRole.CASEWORKER_SSCS_SYSTEMUPDATE, Permission.R);
        grants.put(UserRole.CASEWORKER_SSCS_SYSTEMUPDATE, Permission.U);
        grants.put(UserRole.CASEWORKER_SSCS_SYSTEMUPDATE, Permission.D);
        return grants;
    }
}
