package uk.gov.hmcts.reform.sscs.ccd.access;

import com.google.common.collect.HashMultimap;
import com.google.common.collect.SetMultimap;
import uk.gov.hmcts.ccd.sdk.api.HasAccessControl;
import uk.gov.hmcts.ccd.sdk.api.HasRole;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
public class SscsCudPanelmemberRCitizenCrudAccess implements HasAccessControl {
    @Override
    public SetMultimap<HasRole, Permission> getGrants() {
        SetMultimap<HasRole, Permission> grants = HashMultimap.create();
        grants.put(UserRole.CASEWORKER_SSCS, Permission.C);
        grants.put(UserRole.CASEWORKER_SSCS, Permission.U);
        grants.put(UserRole.CASEWORKER_SSCS, Permission.D);
        grants.put(UserRole.CASEWORKER_SSCS_PANELMEMBER, Permission.R);
        grants.put(UserRole.CITIZEN, Permission.C);
        grants.put(UserRole.CITIZEN, Permission.R);
        grants.put(UserRole.CITIZEN, Permission.U);
        grants.put(UserRole.CITIZEN, Permission.D);
        return grants;
    }
}
