package uk.gov.hmcts.reform.sscs.ccd.domain;

import java.util.Set;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "adjournCaseTimeCT",
        generate = true
)
public class AdjournCaseTimeCT {
    @CCD(
            label = " "
    )
    private Set<AdjournCaseFirstOnSession> adjournCaseNextHearingFirstOnSession;

    @CCD(
            label = "Provide time"
    )
    private AdjournCaseNextHearingTime adjournCaseNextHearingSpecificTime;
}
