package uk.gov.hmcts.reform.sscs.ccd.domain;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "audioVideoEvidenceBundleDocumentCT",
        generate = true
)
public class AudioVideoEvidenceBundleDocumentCT {
    @CCD(
            label = "Audio video bundle document file name",
            showCondition = "documentLink=\"AnyValueToFailThisCondition\""
    )
    private String documentFileName;

    @CCD(
            label = "Select document"
    )
    private Document documentLink;
}
