package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_audioVideoPartyUploaded",
        generate = true
)
@Getter
@AllArgsConstructor
public enum AudioVideoPartyUploaded implements HasLabel {
    CTSC("CTSC clerk", "ctsc"),

    APPELLANT("Appellant", "appellant"),

    APPOINTEE("Appointee", "appointee"),

    REP("Representative", "rep"),

    JOINT_PARTY("Joint party", "jointParty"),

    DWP("FTA", "dwp"),

    OTHER_PARTY("Other party", "otherParty"),

    OTHER_PARTY_REP("Other party representative", "otherPartyRep"),

    OTHER_PARTY_APPOINTEE("Other party appointee", "otherPartyAppointee");

    private final String label;

    @JsonValue
    private final String code;
}
