package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_caseOutcome",
        generate = true
)
@Getter
@AllArgsConstructor
public enum CaseOutcome2 implements HasLabel {
    _19("Revised, Assessment the same, for longer period", "19"),

    _18("Revised, Assessment less, for longer period", "18"),

    _17("Revised, Assessment increased, for shortened period", "17"),

    _21("Reference, Revised in favour of Appellant", "21"),

    _22("Reference, Revised against Appellant", "22"),

    _9("Decision Upheld", "9"),

    _8("Decision Revised Against Appellant", "8"),

    _63("Decision Reserved", "63"),

    _10("Decision in favour of Appellant", "10"),

    _39("% Disablement Increased <80%, No Benefit award", "39");

    private final String label;

    @JsonValue
    private final String code;
}
