package uk.gov.hmcts.reform.sscs.ccd.domain;

import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "caseCorrectionInfo",
        generate = true
)
public class CaseCorrectionInfo {
    @CCD(
            label = "Requesting party",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "FL_requestingParty"
    )
    private RequestingParty FL_requestingParty;

    @CCD(
            label = "Date of correction request"
    )
    private LocalDate dateCorrectionRequest;

    @CCD(
            label = "Date correction referral made"
    )
    private LocalDate dateCorrectionReferralMade;
}
