package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_clerkDelegatedAuthority",
        generate = true
)
@Getter
@AllArgsConstructor
public enum ClerkDelegatedAuthority implements HasLabel {
    DELEGATED_AUTHORITY_TEXT("Using the authority delegated to me by the Senior President of Tribunals under Rule 4 of the Tribunal Procedure Rules (First-tier Tribunal (Social Entitlement Chamber) Rules 2008 I have waived the compliance requirements for the following reason(s):", "delegatedAuthorityText");

    private final String label;

    @JsonValue
    private final String code;
}
