package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_commRequestTopic",
        generate = true
)
@Getter
@AllArgsConstructor
public enum CommRequestTopic implements HasLabel {
    APPEAL_TYPE("Appeal Type", "appealType"),

    APPELLANT_PERSONAL_INFO("Appellant personal information", "appellantPersonalInfo"),

    APPOINTEE_PERSONAL_INFO("Appointee personal information", "appointeePersonalInfo"),

    ISSUING_OFFICE("Issuing office", "issuingOffice"),

    JOINT_PARTY_PERSONAL_INFO("Joint party personal information", "jointPartyPersonalInfo"),

    MRN_DETAILS("MRN/Review Decision Notice Details", "mrnDetails"),

    OTHER_PARTY_PERSONAL_INFO("Other party personal information", "otherPartyPersonalInfo");

    private final String label;

    @JsonValue
    private final String code;
}
