package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_confidentialityType",
        generate = true
)
@Getter
@AllArgsConstructor
public enum ConfidentialityType2 implements HasLabel {
    GENERAL("Send to all parties", "general"),

    CONFIDENTIAL("Select specific recipients", "confidential");

    private final String label;

    @JsonValue
    private final String code;
}
