package uk.gov.hmcts.reform.sscs.ccd.domain;

import lombok.Getter;

@Getter
public enum CountryOfResidence {

    AFGHANISTAN("Afghanistan", "Afghanistan"),
    ALAND_ISLANDS("Aland Islands", "Aland Islands"),
    ALBANIA("Albania", "Albania"),
    ALDERNEY("Alderney", "Alderney"),
    ALGERIA("Algeria", "Algeria"),
    AMERICAN_SAMOA("American Samoa", "American Samoa"),
    ANDORRA("Andorra", "Andorra"),
    ANGOLA("Angola", "Angola"),
    ANGUILLA("Anguilla", "Anguilla"),
    ANTARCTICA("Antarctica", "Antarctica"),
    ANTIGUA_AND_BARBUDA("Antigua and Barbuda", "Antigua and Barbuda"),
    ARGENTINA("Argentina", "Argentina"),
    ARMENIA("Armenia", "Armenia"),
    ARUBA("Aruba", "Aruba"),
    AUSTRALIA("Australia", "Australia"),
    AUSTRIA("Austria", "Austria"),
    AZERBAIJAN("Azerbaijan", "Azerbaijan"),
    BAHAMAS("Bahamas", "Bahamas"),
    BAHRAIN("Bahrain", "Bahrain"),
    BANGLADESH("Bangladesh", "Bangladesh"),
    BARBADOS("Barbados", "Barbados"),
    BELARUS("Belarus", "Belarus"),
    BELGIUM("Belgium", "Belgium"),
    BELIZE("Belize", "Belize"),
    BENIN("Benin", "Benin"),
    BERMUDA("Bermuda", "Bermuda"),
    BHUTAN("Bhutan", "Bhutan"),
    BOLIVIA("Bolivia", "Bolivia"),
    BONAIRE_SINT_EUSTATIUS_AND_SABA("Bonaire, Sint Eustatius and Saba", "Bonaire, Sint Eustatius and Saba"),
    BOSNIA_AND_HERZEGOVINA("Bosnia and Herzegovina", "Bosnia and Herzegovina"),
    BOTSWANA("Botswana", "Botswana"),
    BOUVET_ISLAND("Bouvet Island", "Bouvet Island"),
    BRAZIL("Brazil", "Brazil"),
    BRITISH_INDIAN_OCEAN_TERRITORY("British Indian Ocean Territory", "British Indian Ocean Territory"),
    BRUNEI_DARUSSALAM("Brunei Darussalam", "Brunei Darussalam"),
    BULGARIA("Bulgaria", "Bulgaria"),
    BURKINA_FASO("Burkina Faso", "Burkina Faso"),
    BURUNDI("Burundi", "Burundi"),
    CAMBODIA("Cambodia", "Cambodia"),
    CAMEROON("Cameroon", "Cameroon"),
    CANADA("Canada", "Canada"),
    CAPE_VERDE("Cape Verde", "Cape Verde"),
    CAYMAN_ISLANDS("Cayman Islands", "Cayman Islands"),
    CENTRAL_AFRICAN_REPUBLIC("Central African Republic", "Central African Republic"),
    CHAD("Chad", "Chad"),
    CHILE("Chile", "Chile"),
    CHINA("China", "China"),
    CHRISTMAS_ISLAND("Christmas Island", "Christmas Island"),
    COCOS_KEELING_ISLANDS("Cocos (Keeling) Islands", "Cocos (Keeling) Islands"),
    COLOMBIA("Colombia", "Colombia"),
    COMOROS("Comoros", "Comoros"),
    CONGO("Congo", "Congo"),
    CONGO_THE_DEMOCRATIC_REPUBLIC_OF_THE("Congo, the Democratic Republic of the", "Congo, the Democratic Republic of the"),
    COOK_ISLANDS("Cook Islands", "Cook Islands"),
    COSTA_RICA("Costa Rica", "Costa Rica"),
    CROATIA("Croatia", "Croatia"),
    CUBA("Cuba", "Cuba"),
    CURACAO("Curacao", "Curacao"),
    CYPRUS("Cyprus", "Cyprus"),
    CZECH_REPUBLIC("Czech Republic", "Czech Republic"),
    DENMARK("Denmark", "Denmark"),
    DJIBOUTI("Djibouti", "Djibouti"),
    DOMINICA("Dominica", "Dominica"),
    DOMINICAN_REPUBLIC("Dominican Republic", "Dominican Republic"),
    EAST_TIMOR("East Timor", "East Timor"),
    ECUADOR("Ecuador", "Ecuador"),
    EGYPT("Egypt", "Egypt"),
    EL_SALVADOR("El Salvador", "El Salvador"),
    ENGLAND("England", "England"),
    EQUATORIAL_GUINEA("Equatorial Guinea", "Equatorial Guinea"),
    ERITREA("Eritrea", "Eritrea"),
    ESTONIA("Estonia", "Estonia"),
    ESWATINI("Eswatini", "Eswatini"),
    ETHIOPIA("Ethiopia", "Ethiopia"),
    FALKLAND_ISLANDS("Falkland Islands", "Falkland Islands"),
    FAROE_ISLANDS("Faroe Islands", "Faroe Islands"),
    FIJI("Fiji", "Fiji"),
    FINLAND("Finland", "Finland"),
    FRANCE("France", "France"),
    FRENCH_GUIANA("French Guiana", "French Guiana"),
    FRENCH_POLYNESIA("French Polynesia", "French Polynesia"),
    FRENCH_SOUTHERN_TERRITORIES("French Southern Territories", "French Southern Territories"),
    GABON("Gabon", "Gabon"),
    GAMBIA("Gambia", "Gambia"),
    GEORGIA("Georgia", "Georgia"),
    GERMANY("Germany", "Germany"),
    GHANA("Ghana", "Ghana"),
    GIBRALTAR("Gibraltar", "Gibraltar"),
    GREECE("Greece", "Greece"),
    GREENLAND("Greenland", "Greenland"),
    GRENADA("Grenada", "Grenada"),
    GUADELOUPE("Guadeloupe", "Guadeloupe"),
    GUAM("Guam", "Guam"),
    GUATEMALA("Guatemala", "Guatemala"),
    GUERNSEY("Guernsey", "Guernsey"),
    GUINEA("Guinea", "Guinea"),
    GUINEA_BISSAU("Guinea-Bissau", "Guinea-Bissau"),
    GUYANA("Guyana", "Guyana"),
    HAITI("Haiti", "Haiti"),
    HEARD_ISLAND_AND_MC_DONALD_ISLANDS("Heard Island and McDonald Islands", "Heard Island and McDonald Islands"),
    HERM("Herm", "Herm"),
    HONDURAS("Honduras", "Honduras"),
    HONG_KONG("Hong Kong", "Hong Kong"),
    HUNGARY("Hungary", "Hungary"),
    ICELAND("Iceland", "Iceland"),
    INDIA("India", "India"),
    INDONESIA("Indonesia", "Indonesia"),
    IRAN("Iran", "Iran"),
    IRAQ("Iraq", "Iraq"),
    IRELAND("Ireland", "Ireland"),
    ISLE_OF_MAN("Isle of Man", "Isle of Man"),
    ISRAEL("Israel", "Israel"),
    ITALY("Italy", "Italy"),
    IVORY_COAST("Ivory Coast", "Ivory Coast"),
    JAMAICA("Jamaica", "Jamaica"),
    JAPAN("Japan", "Japan"),
    JERSEY("Jersey", "Jersey"),
    JORDAN("Jordan", "Jordan"),
    KAZAKHSTAN("Kazakhstan", "Kazakhstan"),
    KENYA("Kenya", "Kenya"),
    KIRIBATI("Kiribati", "Kiribati"),
    KOSOVO("Kosovo", "Kosovo"),
    KUWAIT("Kuwait", "Kuwait"),
    KYRGYZSTAN("Kyrgyzstan", "Kyrgyzstan"),
    LAOS("Laos", "Laos"),
    LATVIA("Latvia", "Latvia"),
    LEBANON("Lebanon", "Lebanon"),
    LESOTHO("Lesotho", "Lesotho"),
    LIBERIA("Liberia", "Liberia"),
    LIBYA("Libya", "Libya"),
    LIECHTENSTEIN("Liechtenstein", "Liechtenstein"),
    LITHUANIA("Lithuania", "Lithuania"),
    LUXEMBOURG("Luxembourg", "Luxembourg"),
    MACAO("Macao", "Macao"),
    MACEDONIA("Macedonia", "Macedonia"),
    MADAGASCAR("Madagascar", "Madagascar"),
    MALAWI("Malawi", "Malawi"),
    MALAYSIA("Malaysia", "Malaysia"),
    MALDIVES("Maldives", "Maldives"),
    MALI("Mali", "Mali"),
    MALTA("Malta", "Malta"),
    MARSHALL_ISLANDS("Marshall Islands", "Marshall Islands"),
    MARTINIQUE("Martinique", "Martinique"),
    MAURITANIA("Mauritania", "Mauritania"),
    MAURITIUS("Mauritius", "Mauritius"),
    MAYOTTE("Mayotte", "Mayotte"),
    MEXICO("Mexico", "Mexico"),
    MICRONESIA("Micronesia", "Micronesia"),
    MOLDOVA("Moldova", "Moldova"),
    MONACO("Monaco", "Monaco"),
    MONGOLIA("Mongolia", "Mongolia"),
    MONTENEGRO("Montenegro", "Montenegro"),
    MONTSERRAT("Montserrat", "Montserrat"),
    MOROCCO("Morocco", "Morocco"),
    MOZAMBIQUE("Mozambique", "Mozambique"),
    MYANMAR("Myanmar", "Myanmar"),
    NAMIBIA("Namibia", "Namibia"),
    NAURU("Nauru", "Nauru"),
    NEPAL("Nepal", "Nepal"),
    NETHERLANDS("Netherlands", "Netherlands"),
    NEW_CALEDONIA("New Caledonia", "New Caledonia"),
    NEW_ZEALAND("New Zealand", "New Zealand"),
    NICARAGUA("Nicaragua", "Nicaragua"),
    NIGER("Niger", "Niger"),
    NIGERIA("Nigeria", "Nigeria"),
    NIUE("Niue", "Niue"),
    NORFOLK_ISLAND("Norfolk Island", "Norfolk Island"),
    NORTH_KOREA("North Korea", "North Korea"),
    NORTHERN_IRELAND("Northern Ireland", "Northern Ireland"),
    NORTHERN_MARIANA_ISLANDS("Northern Mariana Islands", "Northern Mariana Islands"),
    NORWAY("Norway", "Norway"),
    OMAN("Oman", "Oman"),
    PAKISTAN("Pakistan", "Pakistan"),
    PALAU("Palau", "Palau"),
    PALESTINE_STATE_OF("Palestine, State of", "Palestine, State of"),
    PANAMA("Panama", "Panama"),
    PAPUA_NEW_GUINEA("Papua New Guinea", "Papua New Guinea"),
    PARAGUAY("Paraguay", "Paraguay"),
    PERU("Peru", "Peru"),
    PHILIPPINES("Philippines", "Philippines"),
    PITCAIRN("Pitcairn", "Pitcairn"),
    POLAND("Poland", "Poland"),
    PORTUGAL("Portugal", "Portugal"),
    PUERTO_RICO("Puerto Rico", "Puerto Rico"),
    QATAR("Qatar", "Qatar"),
    REUNION("Reunion", "Reunion"),
    ROMANIA("Romania", "Romania"),
    RUSSIA("Russia", "Russia"),
    RWANDA("Rwanda", "Rwanda"),
    SAINT_BARTHELEMY("Saint Barthelemy", "Saint Barthelemy"),
    SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA("Saint Helena, Ascension and Tristan da Cunha", "Saint Helena, Ascension and Tristan da Cunha"),
    SAINT_KITTS_AND_NEVIS("Saint Kitts and Nevis", "Saint Kitts and Nevis"),
    SAINT_LUCIA("Saint Lucia", "Saint Lucia"),
    SAINT_MARTIN_FRENCH("Saint Martin (French part)", "Saint Martin (French part)"),
    SAINT_PIERRE_AND_MIQUELON("Saint Pierre and Miquelon", "Saint Pierre and Miquelon"),
    SAINT_VINCENT_AND_THE_GRENADINES("Saint Vincent and the Grenadines", "Saint Vincent and the Grenadines"),
    SAMOA("Samoa", "Samoa"),
    SAN_MARINO("San Marino", "San Marino"),
    SAO_TOME_AND_PRINCIPE("Sao Tome and Principe", "Sao Tome and Principe"),
    SARK("Sark", "Sark"),
    SAUDI_ARABIA("Saudi Arabia", "Saudi Arabia"),
    SCOTLAND("Scotland", "Scotland"),
    SENEGAL("Senegal", "Senegal"),
    SERBIA("Serbia", "Serbia"),
    SEYCHELLES("Seychelles", "Seychelles"),
    SIERRA_LEONE("Sierra Leone", "Sierra Leone"),
    SINGAPORE("Singapore", "Singapore"),
    SINT_MAARTEN_DUTCH("Sint Maarten (Dutch part)", "Sint Maarten (Dutch part)"),
    SLOVAKIA("Slovakia", "Slovakia"),
    SLOVENIA("Slovenia", "Slovenia"),
    SOLOMON_ISLANDS("Solomon Islands", "Solomon Islands"),
    SOMALIA("Somalia", "Somalia"),
    SOUTH_AFRICA("South Africa", "South Africa"),
    SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS("South Georgia and the South Sandwich Islands", "South Georgia and the South Sandwich Islands"),
    SOUTH_KOREA("South Korea", "South Korea"),
    SOUTH_SUDAN("South Sudan", "South Sudan"),
    SPAIN("Spain", "Spain"),
    SRI_LANKA("Sri Lanka", "Sri Lanka"),
    SUDAN("Sudan", "Sudan"),
    SURINAME("Suriname", "Suriname"),
    SVALBARD_AND_JAN_MAYEN("Svalbard and Jan Mayen", "Svalbard and Jan Mayen"),
    SWEDEN("Sweden", "Sweden"),
    SWITZERLAND("Switzerland", "Switzerland"),
    SYRIA("Syria", "Syria"),
    TAIWAN("Taiwan", "Taiwan"),
    TAJIKISTAN("Tajikistan", "Tajikistan"),
    TANZANIA("Tanzania", "Tanzania"),
    THAILAND("Thailand", "Thailand"),
    TOGO("Togo", "Togo"),
    TOKELAU("Tokelau", "Tokelau"),
    TONGA("Tonga", "Tonga"),
    TRINIDAD_AND_TOBAGO("Trinidad and Tobago", "Trinidad and Tobago"),
    TUNISIA("Tunisia", "Tunisia"),
    TURKEY("Turkey", "Turkey"),
    TURKMENISTAN("Turkmenistan", "Turkmenistan"),
    TURKS_AND_CAICOS_ISLANDS("Turks and Caicos Islands", "Turks and Caicos Islands"),
    TUVALU("Tuvalu", "Tuvalu"),
    UGANDA("Uganda", "Uganda"),
    UKRAINE("Ukraine", "Ukraine"),
    UNITED_ARAB_EMIRATES("United Arab Emirates", "United Arab Emirates"),
    UNITED_KINGDOM("United Kingdom", "United Kingdom"),
    UNITED_STATES("United States", "United States"),
    UNITED_STATES_MINOR_OUTLYING_ISLANDS("United States Minor Outlying Islands", "United States Minor Outlying Islands"),
    URUGUAY("Uruguay", "Uruguay"),
    UZBEKISTAN("Uzbekistan", "Uzbekistan"),
    VANUATU("Vanuatu", "Vanuatu"),
    VATICAN_CITY("Vatican City", "Vatican City"),
    VENEZUELA("Venezuela", "Venezuela"),
    VIETNAM("Vietnam", "Vietnam"),
    VIRGIN_ISLANDS_BRITISH("Virgin Islands, British", "Virgin Islands, British"),
    VIRGIN_ISLANDS_US("Virgin Islands, U.S.", "Virgin Islands, U.S."),
    WALES("Wales", "Wales"),
    WALLIS_AND_FUTUNA("Wallis and Futuna", "Wallis and Futuna"),
    WESTERN_SAHARA("Western Sahara", "Western Sahara"),
    YEMEN("Yemen", "Yemen"),
    ZAMBIA("Zambia", "Zambia"),
    ZIMBABWE("Zimbabwe", "Zimbabwe");


    private final String label;
    private final String officialName;

    CountryOfResidence(String label, String officialName) {
        this.label = label;
        this.officialName = officialName;
    }
}
