package uk.gov.hmcts.reform.sscs.ccd.domain;

import lombok.Getter;

@Getter
public enum CountryOfResidence {

    AFGHANISTAN("Afghanistan", "The Islamic Republic of Afghanistan"),
    ALBANIA("Albania", "The Republic of Albania"),
    ALGERIA("Algeria", "The People's Democratic Republic of Algeria"),
    ANDORRA("Andorra", "The Principality of Andorra"),
    ANGOLA("Angola", "The Republic of Angola"),
    ANTIGUA_AND_BARBUDA("Antigua and Barbuda", "Antigua and Barbuda"),
    ARGENTINA("Argentina", "The Argentine Republic"),
    ARMENIA("Armenia", "The Republic of Armenia"),
    AUSTRALIA("Australia", "The Commonwealth of Australia"),
    AUSTRIA("Austria", "The Republic of Austria"),
    AZERBAIJAN("Azerbaijan", "The Republic of Azerbaijan"),
    BAHRAIN("Bahrain", "The Kingdom of Bahrain"),
    BANGLADESH("Bangladesh", "The People's Republic of Bangladesh"),
    BARBADOS("Barbados", "Barbados"),
    BELARUS("Belarus", "The Republic of Belarus"),
    BELGIUM("Belgium", "The Kingdom of Belgium"),
    BELIZE("Belize", "Belize"),
    BENIN("Benin", "The Republic of Benin"),
    BHUTAN("Bhutan", "The Kingdom of Bhutan"),
    BOLIVIA("Bolivia", "The Plurinational State of Bolivia"),
    BOSNIA_AND_HERZEGOVINA("Bosnia and Herzegovina", "Bosnia and Herzegovina"),
    BOTSWANA("Botswana", "The Republic of Botswana"),
    BRAZIL("Brazil", "The Federative Republic of Brazil"),
    BRUNEI("Brunei", "Brunei Darussalam"),
    BULGARIA("Bulgaria", "The Republic of Bulgaria"),
    BURKINA_FASO("Burkina Faso", "Burkina Faso"),
    BURUNDI("Burundi", "The Republic of Burundi"),
    CAMBODIA("Cambodia", "The Kingdom of Cambodia"),
    CAMEROON("Cameroon", "The Republic of Cameroon"),
    CANADA("Canada", "Canada"),
    CAPE_VERDE("Cape Verde", "The Republic of Cabo Verde"),
    CENTRAL_AFRICAN_REPUBLIC("Central African Republic", "The Central African Republic"),
    CHAD("Chad", "The Republic of Chad"),
    CHILE("Chile", "The Republic of Chile"),
    CHINA("China", "The People's Republic of China"),
    COLOMBIA("Colombia", "The Republic of Colombia"),
    COMOROS("Comoros", "The Union of the Comoros"),
    CONGO("Congo", "The Republic of the Congo"),
    CONGO_DEMOCRATIC_REPUBLIC("Congo (Democratic Republic)", "The Democratic Republic of the Congo"),
    COSTA_RICA("Costa Rica", "The Republic of Costa Rica"),
    CROATIA("Croatia", "The Republic of Croatia"),
    CUBA("Cuba", "The Republic of Cuba"),
    CYPRUS("Cyprus", "The Republic of Cyprus"),
    CZECHIA("Czechia", "The Czech Republic"),
    DENMARK("Denmark", "The Kingdom of Denmark"),
    DJIBOUTI("Djibouti", "The Republic of Djibouti"),
    DOMINICA("Dominica", "The Commonwealth of Dominica"),
    DOMINICAN_REPUBLIC("Dominican Republic", "The Dominican Republic"),
    EAST_TIMOR("East Timor", "The Democratic Republic of Timor-Leste"),
    ECUADOR("Ecuador", "The Republic of Ecuador"),
    EGYPT("Egypt", "The Arab Republic of Egypt"),
    EL_SALVADOR("El Salvador", "The Republic of El Salvador"),
    EQUATORIAL_GUINEA("Equatorial Guinea", "The Republic of Equatorial Guinea"),
    ERITREA("Eritrea", "The State of Eritrea"),
    ESTONIA("Estonia", "The Republic of Estonia"),
    ESWATINI("Eswatini", "Kingdom of Eswatini"),
    ETHIOPIA("Ethiopia", "The Federal Democratic Republic of Ethiopia"),
    FIJI("Fiji", "The Republic of Fiji"),
    FINLAND("Finland", "The Republic of Finland"),
    FRANCE("France", "The French Republic"),
    GABON("Gabon", "The Gabonese Republic"),
    GEORGIA("Georgia", "Georgia"),
    GERMANY("Germany", "The Federal Republic of Germany"),
    GHANA("Ghana", "The Republic of Ghana"),
    GREECE("Greece", "The Hellenic Republic"),
    GRENADA("Grenada", "Grenada"),
    GUATEMALA("Guatemala", "The Republic of Guatemala"),
    GUINEA("Guinea", "The Republic of Guinea"),
    GUINEA_BISSAU("Guinea-Bissau", "The Republic of Guinea-Bissau"),
    GUYANA("Guyana", "The Co-operative Republic of Guyana"),
    HAITI("Haiti", "The Republic of Haiti"),
    HONDURAS("Honduras", "The Republic of Honduras"),
    HUNGARY("Hungary", "Hungary"),
    ICELAND("Iceland", "Iceland"),
    INDIA("India", "The Republic of India"),
    INDONESIA("Indonesia", "The Republic of Indonesia"),
    IRAN("Iran", "The Islamic Republic of Iran"),
    IRAQ("Iraq", "The Republic of Iraq"),
    IRELAND("Ireland", "Ireland"),
    ISRAEL("Israel", "The State of Israel"),
    ITALY("Italy", "The Italian Republic"),
    IVORY_COAST("Ivory Coast", "The Republic of Côte D’Ivoire"),
    JAMAICA("Jamaica", "Jamaica"),
    JAPAN("Japan", "Japan"),
    JORDAN("Jordan", "The Hashemite Kingdom of Jordan"),
    KAZAKHSTAN("Kazakhstan", "The Republic of Kazakhstan"),
    KENYA("Kenya", "The Republic of Kenya"),
    KIRIBATI("Kiribati", "The Republic of Kiribati"),
    KOSOVO("Kosovo", "The Republic of Kosovo"),
    KUWAIT("Kuwait", "The State of Kuwait"),
    KYRGYZSTAN("Kyrgyzstan", "The Kyrgyz Republic"),
    LAOS("Laos", "The Lao People's Democratic Republic"),
    LATVIA("Latvia", "The Republic of Latvia"),
    LEBANON("Lebanon", "The Lebanese Republic"),
    LESOTHO("Lesotho", "The Kingdom of Lesotho"),
    LIBERIA("Liberia", "The Republic of Liberia"),
    LIBYA("Libya", "State of Libya"),
    LIECHTENSTEIN("Liechtenstein", "The Principality of Liechtenstein"),
    LITHUANIA("Lithuania", "The Republic of Lithuania"),
    LUXEMBOURG("Luxembourg", "The Grand Duchy of Luxembourg"),
    MADAGASCAR("Madagascar", "The Republic of Madagascar"),
    MALAWI("Malawi", "The Republic of Malawi"),
    MALAYSIA("Malaysia", "Malaysia"),
    MALDIVES("Maldives", "The Republic of Maldives"),
    MALI("Mali", "The Republic of Mali"),
    MALTA("Malta", "The Republic of Malta"),
    MARSHALL_ISLANDS("Marshall Islands", "The Republic of the Marshall Islands"),
    MAURITANIA("Mauritania", "The Islamic Republic of Mauritania"),
    MAURITIUS("Mauritius", "The Republic of Mauritius"),
    MEXICO("Mexico", "The United Mexican States"),
    FEDERATED_STATES_OF_MICRONESIA("Federated States of Micronesia", "Federated States of Micronesia"),
    MOLDOVA("Moldova", "The Republic of Moldova"),
    MONACO("Monaco", "The Principality of Monaco"),
    MONGOLIA("Mongolia", "Mongolia"),
    MONTENEGRO("Montenegro", "Montenegro"),
    MOROCCO("Morocco", "The Kingdom of Morocco"),
    MOZAMBIQUE("Mozambique", "The Republic of Mozambique"),
    MYANMAR_BURMA("Myanmar (Burma)", "The Republic of the Union of Myanmar"),
    NAMIBIA("Namibia", "The Republic of Namibia"),
    NAURU("Nauru", "The Republic of Nauru"),
    NEPAL("Nepal", "Nepal"),
    NETHERLANDS("Netherlands", "The Kingdom of the Netherlands"),
    NEW_ZEALAND("New Zealand", "New Zealand"),
    NICARAGUA("Nicaragua", "The Republic of Nicaragua"),
    NIGER("Niger", "The Republic of Niger"),
    NIGERIA("Nigeria", "The Federal Republic of Nigeria"),
    NORTH_KOREA("North Korea", "The Democratic People's Republic of Korea"),
    NORTH_MACEDONIA("North Macedonia", "Republic of North Macedonia"),
    NORWAY("Norway", "The Kingdom of Norway"),
    OMAN("Oman", "The Sultanate of Oman"),
    PAKISTAN("Pakistan", "The Islamic Republic of Pakistan"),
    PALAU("Palau", "The Republic of Palau"),
    PANAMA("Panama", "The Republic of Panama"),
    PAPUA_NEW_GUINEA("Papua New Guinea", "The Independent State of Papua New Guinea"),
    PARAGUAY("Paraguay", "The Republic of Paraguay"),
    PERU("Peru", "The Republic of Peru"),
    PHILIPPINES("Philippines", "The Republic of the Philippines"),
    POLAND("Poland", "The Republic of Poland"),
    PORTUGAL("Portugal", "The Portuguese Republic"),
    QATAR("Qatar", "The State of Qatar"),
    ROMANIA("Romania", "Romania"),
    RUSSIA("Russia", "The Russian Federation"),
    RWANDA("Rwanda", "The Republic of Rwanda"),
    ST_KITTS_AND_NEVIS("St Kitts and Nevis", "The Federation of Saint Christopher and Nevis"),
    ST_LUCIA("St Lucia", "Saint Lucia"),
    ST_VINCENT("St Vincent", "Saint Vincent and the Grenadines"),
    SAMOA("Samoa", "The Independent State of Samoa"),
    SAN_MARINO("San Marino", "The Republic of San Marino"),
    SAO_TOME_AND_PRINCIPE("Sao Tome and Principe", "The Democratic Republic of Sao Tome and Principe"),
    SAUDI_ARABIA("Saudi Arabia", "The Kingdom of Saudi Arabia"),
    SENEGAL("Senegal", "The Republic of Senegal"),
    SERBIA("Serbia", "The Republic of Serbia"),
    SEYCHELLES("Seychelles", "The Republic of Seychelles"),
    SIERRA_LEONE("Sierra Leone", "The Republic of Sierra Leone"),
    SINGAPORE("Singapore", "The Republic of Singapore"),
    SLOVAKIA("Slovakia", "The Slovak Republic"),
    SLOVENIA("Slovenia", "The Republic of Slovenia"),
    SOLOMON_ISLANDS("Solomon Islands", "Solomon Islands"),
    SOMALIA("Somalia", "Federal Republic of Somalia"),
    SOUTH_AFRICA("South Africa", "The Republic of South Africa"),
    SOUTH_KOREA("South Korea", "The Republic of Korea"),
    SOUTH_SUDAN("South Sudan", "The Republic of South Sudan"),
    SPAIN("Spain", "The Kingdom of Spain"),
    SRI_LANKA("Sri Lanka", "The Democratic Socialist Republic of Sri Lanka"),
    SUDAN("Sudan", "The Republic of the Sudan"),
    SURINAME("Suriname", "The Republic of Suriname"),
    SWEDEN("Sweden", "The Kingdom of Sweden"),
    SWITZERLAND("Switzerland", "The Swiss Confederation"),
    SYRIA("Syria", "The Syrian Arab Republic"),
    TAJIKISTAN("Tajikistan", "The Republic of Tajikistan"),
    TANZANIA("Tanzania", "The United Republic of Tanzania"),
    THAILAND("Thailand", "The Kingdom of Thailand"),
    THE_BAHAMAS("The Bahamas", "The Commonwealth of The Bahamas"),
    THE_GAMBIA("The Gambia", "The Republic of The Gambia"),
    TOGO("Togo", "The Togolese Republic"),
    TONGA("Tonga", "The Kingdom of Tonga"),
    TRINIDAD_AND_TOBAGO("Trinidad and Tobago", "The Republic of Trinidad and Tobago"),
    TUNISIA("Tunisia", "Republic of Tunisia"),
    TURKEY("Turkey", "Republic of Türkiye"),
    TURKMENISTAN("Turkmenistan", "Turkmenistan"),
    TUVALU("Tuvalu", "Tuvalu"),
    UGANDA("Uganda", "The Republic of Uganda"),
    UKRAINE("Ukraine", "Ukraine"),
    UNITED_ARAB_EMIRATES("United Arab Emirates", "The United Arab Emirates"),
    UNITED_STATES("United States", "The United States of America"),
    URUGUAY("Uruguay", "The Oriental Republic of Uruguay"),
    UZBEKISTAN("Uzbekistan", "The Republic of Uzbekistan"),
    VANUATU("Vanuatu", "The Republic of Vanuatu"),
    VATICAN_CITY("Vatican City", "Vatican City State"),
    VENEZUELA("Venezuela", "The Bolivarian Republic of Venezuela"),
    VIETNAM("Vietnam", "The Socialist Republic of Viet Nam"),
    YEMEN("Yemen", "The Republic of Yemen"),
    ZAMBIA("Zambia", "The Republic of Zambia"),
    ZIMBABWE("Zimbabwe", "The Republic of Zimbabwe");

    private final String label;
    private final String officialName;
    CountryOfResidence(String label, String trafficType) {
        this.label = label;
        this.officialName = trafficType;
    }
}
