package uk.gov.hmcts.reform.sscs.ccd.domain;

import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "decisionCorrection",
        generate = true
)
public class DecisionCorrection {
    @CCD(
            label = "Date returned"
    )
    private LocalDate dateReturned;

    @CCD(
            label = "Decision correction outcome",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "FL_decisionCorrected"
    )
    private DecisionCorrected FL_decisionCorrected;
}
