package uk.gov.hmcts.reform.sscs.ccd.domain;

import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "doc",
        generate = true
)
public class Doc {
    @CCD(
            label = "Date Received"
    )
    private LocalDate dateReceived;

    @CCD(
            label = "Evidence Type"
    )
    private String evidenceType;

    @CCD(
            label = "Evidence Provided By"
    )
    private String evidenceProvidedBy;
}
