package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "documentTypeDwp",
        generate = true
)
@Getter
@AllArgsConstructor
public enum DocumentTypeDwp implements HasLabel {
    TL1_FORM("TL1 form (Request for time extension)", "tl1Form"),

    UCB("Unacceptable customer behaviour document", "ucb"),

    DWP_LT203("LT203 or OM1 document", "dwpLT203"),

    DWP_CHALLENGE_VALIDITY_DOCUMENT("FTA challenge validity document", "dwpChallengeValidityDocument"),

    DWP_LAPSE_LETTER("Lapse letter", "dwpLapseLetter"),

    DWP_RESPONSE("FTA response", "dwpResponse"),

    DWP_EDITED_RESPONSE("FTA edited response", "dwpEditedResponse"),

    AT38("AT38", "at38"),

    DWP_EVIDENCE_BUNDLE("FTA evidence bundle", "dwpEvidenceBundle"),

    DWP_EDITED_EVIDENCE_BUNDLE("FTA edited evidence bundle", "dwpEditedEvidenceBundle"),

    APPENDIX12("Appendix 12 document", "appendix12"),

    AUDIO_DOCUMENT("Audio document", "audioDocument"),

    VIDEO_DOCUMENT("Video document", "videoDocument");

    private final String label;

    @JsonValue
    private final String code;
}
