package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "documentType",
        generate = true
)
@Getter
@AllArgsConstructor
public enum DocumentType2 implements HasLabel {
    AUDIO_VIDEO_EVIDENCE_DIRECTION_NOTICE("Audio/Video evidence direction notice", "audioVideoEvidenceDirectionNotice"),

    AUDIO_DOCUMENT("Audio document", "audioDocument"),

    VIDEO_DOCUMENT("Video document", "videoDocument"),

    MEDICAL_EVIDENCE("Medical evidence", "Medical evidence"),

    OTHER_EVIDENCE("Other evidence", "Other evidence"),

    DWP_RESPONSE("FTA response", "DWP response"),

    OTHER_DOCUMENT("Other document", "Other document"),

    DECISION_NOTICE("Decision Notice", "Decision Notice"),

    DIRECTION_NOTICE("Directions Notice", "Direction Notice"),

    DL6("DL6", "dl6"),

    DL16("DL16", "dl16"),

    HMCTS_EVIDENCE("HMCTS evidence", "hmctsEvidence"),

    APPELLANT_EVIDENCE("Appellant evidence", "appellantEvidence"),

    REPRESENTATIVE_EVIDENCE("Representative evidence", "representativeEvidence"),

    DWP_EVIDENCE("FTA evidence", "dwpEvidence"),

    AT38("AT38", "at38"),

    SSCS1("SSCS1", "sscs1"),

    SSCS2("SSCS2", "sscs2"),

    TL1_FORM("TL1 form", "tl1Form"),

    DRAFT_DECISION_NOTICE("Draft Decision Notice", "draftDecisionNotice"),

    FINAL_DECISION_NOTICE("Final Decision Notice", "finalDecisionNotice"),

    DRAFT_ADJOURNMENT_NOTICE("Draft Adjournment Notice", "draftAdjournmentNotice"),

    ADJOURNMENT_NOTICE("Adjournment Notice", "adjournmentNotice"),

    JOINT_PARTY_EVIDENCE("Joint party evidence", "jointPartyEvidence"),

    REINSTATEMENT_REQUEST("Reinstatement request", "reinstatementRequest"),

    URGENT_HEARING_REQUEST("Urgent hearing request", "urgentHearingRequest"),

    CONFIDENTIALITY_REQUEST("Confidentiality request", "confidentialityRequest"),

    RIP1_DOCUMENT("RIP 1 document", "rip1Document"),

    WITHDRAWAL_REQUEST("Withdrawal Request", "withdrawalRequest"),

    OTHER_PARTY_EVIDENCE("Other party evidence", "otherPartyEvidence"),

    OTHER_PARTY_REP_EVIDENCE("Other party representative evidence", "otherPartyRepEvidence"),

    OTHER_PARTY_HEARING_PREFERENCES("Other party hearing preferences", "otherPartyHearingPreferences"),

    POSTPONEMENT_REQUEST("Postponement request", "postponementRequest"),

    POSTPONEMENT_REQUEST_DIRECTION_NOTICE("Postponement Request direction notice", "postponementRequestDirectionNotice"),

    SSCS5("SSCS5", "sscs5"),

    SSCS8("SSCS8", "sscs8"),

    SET_ASIDE_APPLICATION("Set aside application", "setAsideApplication"),

    CORRECTION_APPLICATION("Correction application", "correctionApplication"),

    SET_ASIDE_GRANTED("Set aside granted decision notice", "setAsideGranted"),

    SET_ASIDE_REFUSED("Set aside refused decision notice", "setAsideRefused"),

    DRAFT_CORRECTED_NOTICE("Draft Corrected Final Decision Notice", "draftCorrectedNotice"),

    CORRECTION_GRANTED("Corrected Final Decision Notice", "correctionGranted"),

    CORRECTION_REFUSED("Correction refused decision notice", "correctionRefused"),

    STATEMENT_OF_REASONS_GRANTED("SOR granted decision notice", "statementOfReasonsGranted"),

    STATEMENT_OF_REASONS_REFUSED("SOR refused decision notice", "statementOfReasonsRefused"),

    STATEMENT_OF_REASONS_APPLICATION("SOR application", "statementOfReasonsApplication"),

    CORRECTED_DECISION_NOTICE("Corrected decision notice", "correctedDecisionNotice"),

    STATEMENT_OF_REASONS_GRANTED_2("SOR Granted Decision Notice", "statementOfReasonsGranted"),

    STATEMENT_OF_REASONS_REFUSED_2("SOR Refused Decision Notice", "statementOfReasonsRefused"),

    STATEMENT_OF_REASONS("Statement of Reasons", "statementOfReasons"),

    LIBERTY_TO_APPLY_GRANTED("Liberty to Apply granted decision notice", "libertyToApplyGranted"),

    LIBERTY_TO_APPLY_REFUSED("Liberty to Apply refused decision notice", "libertyToApplyRefused"),

    LIBERTY_TO_APPLY_APPLICATION("Liberty to Apply application", "libertyToApplyApplication"),

    PERMISSION_TO_APPEAL_GRANTED("Permission to Appeal granted decision notice", "permissionToAppealGranted"),

    PERMISSION_TO_APPEAL_REFUSED("Permission to Appeal refused decision notice", "permissionToAppealRefused"),

    PERMISSION_TO_APPEAL_APPLICATION("Permission to Appeal application", "permissionToAppealApplication"),

    REVIEW_AND_SET_ASIDE("Review granted", "reviewAndSetAside"),

    UPPER_TRIBUNALS_DECISION_REMADE("Upper Tribunals Decision Remade Notice", "upperTribunalsDecisionRemade"),

    UPPER_TRIBUNALS_DECISION_REFUSED("Upper Tribunals Decision Refused Notice", "upperTribunalsDecisionRefused"),

    UPPER_TRIBUNALS_DECISION_REMITTED("Upper Tribunals Decision Remitted Notice", "upperTribunalsDecisionRemitted"),

    POST_HEARING_OTHER("Post hearing other", "postHearingOther");

    private final String label;

    @JsonValue
    private final String code;
}
