package uk.gov.hmcts.reform.sscs.ccd.domain;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "documentLanguage",
        generate = true
)
@RequiredArgsConstructor
@Getter
public enum DocumentLanguage implements HasLabel {
    CY("Welsh"),

    EN("English");

    private final String label;
}
