package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "documentTypeWelsh",
        generate = true
)
@Getter
@AllArgsConstructor
public enum DocumentTypeWelsh implements HasLabel {
    POSTPONEMENT_REQUEST("Postponement request", "postponementRequest"),

    POSTPONEMENT_REQUEST_DIRECTION_NOTICE("Postponement Request direction notice", "postponementRequestDirectionNotice"),

    APPELLANT_EVIDENCE("Appellant evidence", "appellantEvidence"),

    DECISION_NOTICE("Decision Notice", "Decision Notice"),

    DIRECTION_NOTICE("Directions Notice", "Direction Notice"),

    SSCS1("SSCS1", "sscs1"),

    URGENT_HEARING_REQUEST("Urgent hearing request", "urgentHearingRequest"),

    ADJOURNMENT_NOTICE("Adjournment Notice", "adjournmentNotice"),

    REINSTATEMENT_REQUEST("Reinstatement request", "reinstatementRequest"),

    FINAL_DECISION_NOTICE("Final Decision Notice", "finalDecisionNotice"),

    RIP1_DOCUMENT("RIP 1 document", "rip1Document"),

    AUDIO_VIDEO_EVIDENCE_DIRECTION_NOTICE("Audio/Video evidence direction notice", "audioVideoEvidenceDirectionNotice"),

    SET_ASIDE_APPLICATION("Set Aside Application", "setAsideApplication"),

    SET_ASIDE_GRANTED("Set Aside Granted Decision Notice", "setAsideGranted"),

    SET_ASIDE_REFUSED("Set Aside Refused Decision Notice", "setAsideRefused"),

    CORRECTION_APPLICATION("Correction Application", "correctionApplication"),

    DRAFT_CORRECTED_NOTICE("Draft Corrected Final Decision Notice", "draftCorrectedNotice"),

    CORRECTION_GRANTED("Corrected Final Decision Notice", "correctionGranted"),

    CORRECTION_REFUSED("Correction Refused Decision Notice", "correctionRefused"),

    STATEMENT_OF_REASONS_APPLICATION("SOR Application", "statementOfReasonsApplication"),

    STATEMENT_OF_REASONS_GRANTED("SOR Granted Decision Notice", "statementOfReasonsGranted"),

    STATEMENT_OF_REASONS_REFUSED("SOR Refused Decision Notice", "statementOfReasonsRefused"),

    STATEMENT_OF_REASONS("Statement of Reasons", "statementOfReasons"),

    LIBERTY_TO_APPLY_GRANTED("Liberty to Apply granted decision notice", "libertyToApplyGranted"),

    LIBERTY_TO_APPLY_REFUSED("Liberty to Apply refused decision notice", "libertyToApplyRefused"),

    LIBERTY_TO_APPLY_APPLICATION("Liberty to Apply application", "libertyToApplyApplication"),

    PERMISSION_TO_APPEAL_GRANTED("Permission to Appeal granted decision notice", "permissionToAppealGranted"),

    PERMISSION_TO_APPEAL_REFUSED("Permission to Appeal refused decision notice", "permissionToAppealRefused"),

    PERMISSION_TO_APPEAL_APPLICATION("Permission to Appeal application", "permissionToAppealApplication"),

    POST_HEARING_OTHER("Post hearing other", "postHearingOther"),

    REVIEW_AND_SET_ASIDE("Review granted", "reviewAndSetAside");

    private final String label;

    @JsonValue
    private final String code;
}
