package uk.gov.hmcts.reform.sscs.ccd.domain;

import java.time.LocalDate;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "dwpDocuments",
        generate = true
)
public class DwpDocuments {
    @CCD(
            label = "Document type",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "documentTypeDwp"
    )
    private DocumentTypeDwp documentType;

    @CCD(
            label = "Original document Url"
    )
    private Document documentLink;

    @CCD(
            label = "Edited document URL"
    )
    private Document editedDocumentLink;

    @CCD(
            label = "Edited evidence reason",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "FL_editedEvidenceReason"
    )
    private EditedEvidenceReason dwpEditedEvidenceReason;

    @CCD(
            label = "Document file name"
    )
    private String documentFileName;

    @CCD(
            label = "Comment"
    )
    private String documentComment;

    @CCD(
            label = "Bundle addition"
    )
    private String bundleAddition;

    @CCD(
            label = "Evidence issued"
    )
    private YesOrNo evidenceIssued;

    @CCD(
            label = "Date added"
    )
    private LocalDate documentDateAdded;

    @CCD(
            label = "Date and time added"
    )
    private LocalDateTime documentDateTimeAdded;

    @CCD(
            label = "Party uploaded"
    )
    private String partyUploaded;

    @CCD(
            label = "Date approved"
    )
    private LocalDate dateApproved;

    @CCD(
            label = "Audio/video document"
    )
    private Document avDocumentLink;

    @CCD(
            label = "Translation status",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "documentTranslationStatus"
    )
    private DocumentTranslationStatus documentTranslationStatus;
}
