package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "dwpEvidenceBundleDocumentCT",
        generate = true
)
public class DwpEvidenceBundleDocumentCT {
    @JsonProperty("EvidenceBundleDocumentTitle")
    @CCD(
            label = "Evidence Bundle",
            typeOverride = FieldType.Label
    )
    private String evidenceBundleDocumentTitle;

    @CCD(
            label = "Evidence bundle file name",
            showCondition = "EvidenceBundleDocumentTitle=\"AnyValueToFailThisCondition\""
    )
    private String documentFileName;

    @CCD(
            label = "Select document",
            hint = "All documents must be PDF formatted",
            regex = ".pdf"
    )
    private Document documentLink;
}
