package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_dwpFurtherEvidenceStates",
        generate = true
)
@Getter
@AllArgsConstructor
public enum DwpFurtherEvidenceStates implements HasLabel {
    FURTHER_EVIDENCE_RECEIVED("Further evidence received", "furtherEvidenceReceived"),

    NO_ACTION("No action", "noAction"),

    SUPPLEMENTARY_SUBMISSION("Supplementary submission", "supplementarySubmission"),

    IN_PROGRESS("Further evidence in progress", "inProgress");

    private final String label;

    @JsonValue
    private final String code;
}
