package uk.gov.hmcts.reform.sscs.ccd.domain;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "dwpResponseDocumentCT",
        generate = true
)
public class DwpResponseDocumentCT {
    @CCD(
            label = "Secretary of State's response",
            showCondition = "documentFileName=\"AnyValueToFailThisCondition\"",
            typeOverride = FieldType.Label
    )
    private String dwpResponseDocumentTitle;

    @CCD(
            label = "HM Revenue and Customs",
            showCondition = "documentFileName=\"AnyValueToFailThisCondition\"",
            typeOverride = FieldType.Label
    )
    private String hmrcResponseDocumentTitle;

    @CCD(
            label = "Infected Blood Compensation Authority's response",
            showCondition = "documentFileName=\"AnyValueToFailThisCondition\"",
            typeOverride = FieldType.Label
    )
    private String ibcaResponseDocumentTitle;

    @CCD(
            label = "Evidence bundle file name",
            showCondition = "dwpResponseDocumentTitle=\"AnyValueToFailThisCondition\""
    )
    private String documentFileName;

    @CCD(
            label = "Select document",
            hint = "All documents must be PDF formatted",
            regex = ".pdf"
    )
    private Document documentLink;
}
