package uk.gov.hmcts.reform.sscs.ccd.domain;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "dwpSupplementaryResponseDocumentCT",
        generate = true
)
public class DwpSupplementaryResponseDocumentCT {
    @CCD(
            label = "-",
            typeOverride = FieldType.Label
    )
    private String dwpSupplementaryResponseDocument;

    @CCD(
            label = "Select document for upload",
            hint = "All documents must be PDF formatted",
            regex = ".pdf"
    )
    private Document documentLink;
}
