package uk.gov.hmcts.reform.sscs.ccd.domain;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "elementAndIssueCode",
        generate = true
)
public class ElementAndIssueCode {
    @CCD(
            label = "Issue code",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "FL_issueCodesUc"
    )
    private IssueCodesUc issueCode;

    @CCD(
            label = "Outcome"
    )
    private String outcome;
}
