package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_esaWriteFinalDecisionReachingQuestion",
        generate = true
)
@Getter
@AllArgsConstructor
public enum EsaWriteFinalDecisionReachingQuestion implements HasLabel {
    REACHING3A("3a. Cannot raise either arm as if to put something in the top pocket of a coat or jacket. (15 points)", "reaching3a"),

    REACHING3B("3b. Cannot raise either arm to top of head as if to put on a hat. (9 points)", "reaching3b"),

    REACHING3C("3c. Cannot raise either arm above head height as if to reach for something. (6 points)", "reaching3c"),

    REACHING3D("3d. None of the above apply. (0 points)", "reaching3d");

    private final String label;

    @JsonValue
    private final String code;
}
