package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_esaWriteFinalDecisionGettingAboutQuestion",
        generate = true
)
@Getter
@AllArgsConstructor
public enum EsaWriteFinalDecisionGettingAboutQuestion implements HasLabel {
    GETTING_ABOUT15A("15a. Cannot get to any place outside the claimant’s home with which the claimant is familiar. (15 points)", "gettingAbout15a"),

    GETTING_ABOUT15B("15b. Is unable to get to a specified place with which the claimant is familiar, without being accompanied by another person. (9 points)", "gettingAbout15b"),

    GETTING_ABOUT15C("15c. Is unable to get to a specified place with which the claimant is unfamiliar without being accompanied by another person. (6 points)", "gettingAbout15c"),

    GETTING_ABOUT15D("15d. None of the above apply. (0 points)", "gettingAbout15d");

    private final String label;

    @JsonValue
    private final String code;
}
