package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_esaWriteFinalDecisionManualDexterityQuestion",
        generate = true
)
@Getter
@AllArgsConstructor
public enum EsaWriteFinalDecisionManualDexterityQuestion implements HasLabel {
    MANUAL_DEXTERITY5A("5a. Cannot press a button (such as a telephone keypad) with either hand or cannot turn the pages of a book with either hand. (15 points)", "manualDexterity5a"),

    MANUAL_DEXTERITY5B("5b. Cannot pick up a £1 coin or equivalent with either hand. (15 points)", "manualDexterity5b"),

    MANUAL_DEXTERITY5C("5c. Cannot use a pen or pencil to make a meaningful mark with either hand. (9 points)", "manualDexterity5c"),

    MANUAL_DEXTERITY5D("5d. Cannot single-handedly use a suitable keyboard or mouse. (9 points)", "manualDexterity5d"),

    MANUAL_DEXTERITY5E("5e. None of the above apply. (0 points)", "manualDexterity5e");

    private final String label;

    @JsonValue
    private final String code;
}
