package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_esaWriteFinalDecisionPickingUpQuestion",
        generate = true
)
@Getter
@AllArgsConstructor
public enum EsaWriteFinalDecisionPickingUpQuestion implements HasLabel {
    PICKING_UP4A("4a. Cannot pick up and move a 0.5 litre carton full of liquid. (15 points)", "pickingUp4a"),

    PICKING_UP4B("4b. Cannot pick up and move a one litre carton full of liquid. (9 points)", "pickingUp4b"),

    PICKING_UP4C("4c. Cannot transfer a light but bulky object such as an empty cardboard box. (6 points)", "pickingUp4c"),

    PICKING_UP4D("4d. None of the above apply. (0 points)", "pickingUp4d");

    private final String label;

    @JsonValue
    private final String code;
}
