package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_esaWriteFinalDecisionCopingWithChangeQuestion",
        generate = true
)
@Getter
@AllArgsConstructor
public enum EsaWriteFinalDecisionCopingWithChangeQuestion implements HasLabel {
    COPING_WITH_CHANGE14A("14a. Cannot cope with any change to the extent that day to day life cannot be managed. (15 points)", "copingWithChange14a"),

    COPING_WITH_CHANGE14B("14b. Cannot cope with minor planned change (such as a pre- arranged change to the routine time scheduled for a lunch break), to the extent that, overall, day to day life is made significantly more difficult. (9 points)", "copingWithChange14b"),

    COPING_WITH_CHANGE14C("14c. Cannot cope with minor unplanned change (such as the timing of an appointment on the day it is due to occur), to the extent that, overall, day to day life is made significantly more difficult. (6 points)", "copingWithChange14c"),

    COPING_WITH_CHANGE14D("14d. None of the above apply. (0 points)", "copingWithChange14d");

    private final String label;

    @JsonValue
    private final String code;
}
