package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_esaWriteFinalDecisionPersonalActionQuestion",
        generate = true
)
@Getter
@AllArgsConstructor
public enum EsaWriteFinalDecisionPersonalActionQuestion implements HasLabel {
    PERSONAL_ACTION13A("13a. Cannot, due to impaired mental function, reliably initiate or complete at least 2 sequential personal actions. (15 points)", "personalAction13a"),

    PERSONAL_ACTION13B("13b. Cannot, due to impaired mental function, reliably initiate or complete at least 2 sequential personal actions for the majority of the time. (9 points)", "personalAction13b"),

    PERSONAL_ACTION13C("13c. Frequently cannot, due to impaired mental function, reliably initiate or complete at least 2 sequential personal actions. (6 points)", "personalAction13c"),

    PERSONAL_ACTION13D("13d. None of the above applies. (0 points)", "personalAction13d");

    private final String label;

    @JsonValue
    private final String code;
}
