package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "eventType",
        generate = true
)
@Getter
@AllArgsConstructor
public enum EventType2 implements HasLabel {
    APPEAL_CREATED("Appeal Created", "appealCreated"),

    UPDATE_CASE_DATA("Case Updated", "updateCaseData"),

    APPEAL_LAPSED("Appeal Lapsed", "appealLapsed"),

    APPEAL_RECEIVED("Appeal Received", "appealReceived"),

    APPEAL_WITHDRAWN("Appeal Withdrawn", "appealWithdrawn"),

    EVIDENCE_RECEIVED("Evidence Received", "evidenceReceived"),

    EVIDENCE_REMINDER("Evidence Reminder", "evidenceReminder"),

    HEARING_BOOKED("Hearing Booked", "hearingBooked"),

    HEARING_REMINDER("Hearing Reminder", "hearingReminder"),

    HEARING_POSTPONED("Hearing Postponed", "hearingPostponed"),

    HEARING_ADJOURNED("Hearing Adjourned", "hearingAdjourned"),

    RESPONSE_RECEIVED("Response received", "responseReceived"),

    APPEAL_DORMANT("Appeal Dormant", "appealDormant"),

    READY_TO_LIST("Ready to List", "readyToList"),

    NOT_LISTABLE("Not Listable", "notListable");

    private final String label;

    @JsonValue
    private final String code;
}
