package uk.gov.hmcts.reform.sscs.ccd.domain;

import java.time.LocalDate;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "ftaCommunicationRequest",
        generate = true
)
public class FtaCommunicationRequest {
    @CCD(
            label = "Reply"
    )
    private FtaCommunicationReply requestReply;

    @CCD(
            label = "Date Of Request"
    )
    private LocalDateTime requestDateTime;

    @CCD(
            label = "Reply Due Date"
    )
    private LocalDate requestResponseDueDate;

    @CCD(
            label = "Request From Name"
    )
    private String requestUserName;

    @CCD(
            label = "Request From Role"
    )
    private String requestUserRole;

    @CCD(
            label = "Request Topic",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "FL_commRequestTopic"
    )
    private CommRequestTopic requestTopic;

    @CCD(
            label = "Request",
            typeOverride = FieldType.TextArea
    )
    private String requestMessage;
}
