package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_hearingEpimsId",
        generate = true
)
@Getter
@AllArgsConstructor
public enum HearingEpimsId implements HasLabel {
    _219164("Aberdeen", "219164"),

    _827534("Aberystwyth JC", "827534"),

    _450049("Aldershot", "450049"),

    _239985("Ashford", "239985"),

    _206150("Ayr", "206150"),

    _574546("Barnsley", "574546"),

    _774335("Barnstaple", "774335"),

    _761518("Barrow", "761518"),

    _694840("Basildon CC", "694840"),

    _446255("Bedford", "446255"),

    _572158("Bedlington", "572158"),

    _824367("Belfast RCJ (IBC)", "824367"),

    _999999("Benbecula (Closed)", "999999"),

    _999974("Berwick (Closed)", "999974"),

    _381649("Bexleyheath", "381649"),

    _444097("Birkenhead", "444097"),

    _231596("Birmingham CJC", "231596"),

    _107017("Blackburn", "107017"),

    _196222("Blackpool (Closed)", "196222"),

    _999968("Blackpool", "999968"),

    _271813("Bodmin (Closed)", "271813"),

    _210228("Bolton", "210228"),

    _117667("Boston", "117667"),

    _101633("Bournemouth", "101633"),

    _698118("Bradford", "698118"),

    _759555("Bridlington Mags", "759555"),

    _296806("Brighton", "296806"),

    _819890("Bristol CJC", "819890"),

    _781155("Bristol", "781155"),

    _443089("Burnley", "443089"),

    _366572("Caernarfon", "366572"),

    _602674("Cambridge", "602674"),

    _999998("Campbeltown Centre (Closed)", "999998"),

    _372653("Cardiff", "372653"),

    _234850("Cardiff (CJC) (Closed)", "234850"),

    _779109("Cardiff Court", "779109"),

    _243126("Carlisle", "243126"),

    _101959("Carmarthen JC", "101959"),

    _771467("Chatham", "771467"),

    _624810("Chelmsford (Closed)", "624810"),

    _816875("Chelmsford", "816875"),

    _226511("Chester", "226511"),

    _443014("Chester Mags (Closed)", "443014"),

    _652852("Chesterfield", "652852"),

    _787030("Coventry (CMCB)", "787030"),

    _288691("Darlington", "288691"),

    _484482("Derby", "484482"),

    _45900("Doncaster", "45900"),

    _624161("Dorchester", "624161"),

    _367564("Dundee", "367564"),

    _999995("Dunfermline", "999995"),

    _999997("Dumfries (Cairndale) (Closed)", "999997"),

    _491107("Durham JC", "491107"),

    _816964("East London (S)", "816964"),

    _999980("Eastbourne", "999980"),

    _604040("Edinburgh (Closed)", "604040"),

    _376138("Edinburgh", "376138"),

    _208506("Enfield", "208506"),

    _815811("Exeter", "815811"),

    _406867("Fox Court (S) (Closed)", "406867"),

    _369230("London Tribunals", "369230"),

    _999993("Galashiels (Closed)", "999993"),

    _427519("Gateshead", "427519"),

    _366559("Glasgow", "366559"),

    _198592("Gloucester", "198592"),

    _999992("Greenock", "999992"),

    _641199("Grimsby", "641199"),

    _723075("Hamilton", "723075"),

    _784691("Hastings", "784691"),

    _386417("Hatton Cross", "386417"),

    _741758("Havant", "741758"),

    _700596("Haverfordwest", "700596"),

    _228883("Hereford JC", "228883"),

    _437303("High Wycombe", "437303"),

    _197852("Huddersfield (Closed)", "197852"),

    _320113("Huddersfield", "320113"),

    _195520("Hull", "195520"),

    _362420("Hull Mags", "362420"),

    _900001("Inverness", "900001"),

    _287515("Ipswich", "287515"),

    _767032("Kidderminster", "767032"),

    _999991("Kilmarnock (Closed)", "999991"),

    _671879("Kings Lynn Mags", "671879"),

    _999990("Kirkcaldy (Volunteer House)", "999990"),

    _999989("Kirkwall (Closed)", "999989"),

    _353615("Lancaster", "353615"),

    _495952("Leeds", "495952"),

    _500064("Leicester", "500064"),

    _999988("Lerwick (Closed)", "999988"),

    _999986("Lewis", "999986"),

    _195465("Lincoln", "195465"),

    _196538("Liverpool", "196538"),

    _345663("Liverpool 2", "345663"),

    _860090("Llandrindod", "860090"),

    _361595("Llandudno", "361595"),

    _390932("Llanelli", "390932"),

    _252292("Luton", "252292"),

    _701411("Manchester", "701411"),

    _144641("Manchester 3", "144641"),

    _512401("Manchester MAT (Closed)", "512401"),

    _659591("Margate", "659591"),

    _448345("Merthyr Tydfil", "448345"),

    _815997("Milton Keynes (Closed)", "815997"),

    _497356("Milton Keynes", "497356"),

    _366796("Newcastle", "366796"),

    _227101("Newport", "227101"),

    _416742("Newport IOW", "416742"),

    _270253("Newton Abbot", "270253"),

    _562808("North Shields", "562808"),

    _420219("Northampton", "420219"),

    _631555("Norwich", "631555"),

    _618632("Nottingham Mags", "618632"),

    _228231("Nuneaton", "228231"),

    _999987("Oban", "999987"),

    _371016("Oxford", "371016"),

    _583034("Peterborough", "583034"),

    _235590("Plymouth", "235590"),

    _764728("Plymouth Mags (Closed)", "764728"),

    _490237("Poole", "490237"),

    _846055("Port Talbot CJC", "846055"),

    _379656("Prestatyn", "379656"),

    _317334("Preston Mags", "317334"),

    _432294("Reading", "432294"),

    _245287("Reading", "245287"),

    _558490("Rochdale", "558490"),

    _400947("Romford", "400947"),

    _239171("Romford", "239171"),

    _817113("Salisbury", "817113"),

    _744412("Scarborough", "744412"),

    _720624("Sheffield", "720624"),

    _259170("Shrewsbury", "259170"),

    _563156("South Shields", "563156"),

    _43104("Southampton (Closed)", "43104"),

    _330480("Southampton Mags", "330480"),

    _781139("Southend", "781139"),

    _563906("St Helens", "563906"),

    _284455("Stevenage", "284455"),

    _198561("Stirling (Closed)", "198561"),

    _560788("Stockport", "560788"),

    _370964("Stoke", "370964"),

    _999984("Stranraer (Closed)", "999984"),

    _517400("Sunderland", "517400"),

    _37792("Sutton", "37792"),

    _234946("Swansea CJC", "234946"),

    _314074("Swindon", "314074"),

    _506742("Taunton", "506742"),

    _449358("Teesside JC", "449358"),

    _292771("Telford", "292771"),

    _384843("Truro", "384843"),

    _852649("Wakefield CJC", "852649"),

    _177463("Walsall", "177463"),

    _685391("Watford", "685391"),

    _535735("Wellingborough", "535735"),

    _103147("Welshpool", "103147"),

    _999983("Wick (Closed)", "999983"),

    _245068("Wigan", "245068"),

    _788436("Wolverhampton", "788436"),

    _703200("Worcester Mags", "703200"),

    _209396("Workington", "209396"),

    _545334("Worle", "545334"),

    _637145("Wrexham", "637145"),

    _107581("York", "107581");

    private final String label;

    @JsonValue
    private final String code;
}
