package uk.gov.hmcts.reform.sscs.ccd.domain;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_hearingStatus",
        generate = true
)
@RequiredArgsConstructor
@Getter
public enum HearingStatus2 implements HasLabel {
    AWAITING_LISTING("Hearing is Awaiting a listing"),

    LISTED("Hearing has been Listed"),

    EXCEPTION("Hearing has an Exception"),

    CANCELLED("Hearing has been Cancelled"),

    AWAITING_ACTUALS("Hearing is Awaiting Actuals"),

    COMPLETED("Hearing is Completed"),

    ADJOURNED("Hearing is Adjourned");

    private final String label;
}
