package uk.gov.hmcts.reform.sscs.ccd.domain;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_hearingChannel",
        generate = true
)
@RequiredArgsConstructor
@Getter
public enum HearingChannel2 implements HasLabel {
    TEL("Telephone"),

    VID("Video"),

    INTER("Face To Face"),

    NA("Not Attending"),

    ONPPRS("Paper");

    private final String label;
}
