package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_interlocReferralReason",
        generate = true
)
@Getter
@AllArgsConstructor
public enum InterlocReferralReason2 implements HasLabel {
    REVIEW_REINSTATEMENT_REQUEST("Review reinstatement request", "reviewReinstatementRequest"),

    REVIEW_CONFIDENTIALITY_REQUEST("UC JP ONLY - Review confidentiality request", "reviewConfidentialityRequest"),

    REVIEW_CORRECTION_REQUEST("Review correction request", "reviewCorrectionRequest"),

    REVIEW_SET_ASIDE_APPLICATION("Review set aside application", "reviewSetAsideApplication"),

    REVIEW_CORRECTION_APPLICATION("Review correction application", "reviewCorrectionApplication"),

    STATEMENT_OF_REASONS_APPLICATION("Statement of reasons application", "statementOfReasonsApplication"),

    LATE_STATEMENT_OF_REASONS_APPLICATION("Late statement of reasons application", "lateStatementOfReasonsApplication"),

    REVIEW_PERMISSION_TO_APPEAL_APPLICATION("Review permission to appeal application", "reviewPermissionToAppealApplication"),

    REVIEW_LIBERTY_TO_APPLY_APPLICATION("Review liberty to apply application", "reviewLibertyToApplyApplication"),

    REVIEW_UPPER_TRIBUNAL_DECISION("Review upper tribunal decision", "reviewUpperTribunalDecision"),

    CONFIDENTIALITY("Confidentiality", "confidentiality"),

    ADVICE_ON_HOW_TO_PROCEED("Advice on how to proceed", "adviceOnHowToProceed"),

    COMPLEX_CASE("Complex Case", "complexCase"),

    OVER13_MONTHS_AND_GROUNDS_MISSING("Grounds for appeal missing", "over13MonthsAndGroundsMissing"),

    LISTING_DIRECTIONS("Listing directions", "listingDirections"),

    NONE("N/A", "none"),

    NO_MRN("No MRN", "noMrn"),

    NO_RESPONSE_TO_DIRECTION("No response to a direction", "noResponseToDirection"),

    OTHER("Other", "other"),

    OVER13MONTHS("Over 13 months", "over13months"),

    OVER300_PAGES("Over 300 pages", "over300Pages"),

    PHME_REQUEST("PHE request", "phmeRequest"),

    REVIEW_AUDIO_VIDEO_EVIDENCE("Review A/V evidence", "reviewAudioVideoEvidence"),

    REVIEW_POSTPONEMENT_REQUEST("Review hearing postponement request", "reviewPostponementRequest"),

    TIME_EXTENSION("Time extension", "timeExtension"),

    REJECT_HEARING_RECORDING_REQUEST("Reject hearing recording request", "rejectHearingRecordingRequest"),

    CONFIRM_PANEL_COMPOSITION_AND_LISTING_DIRECTIONS("Confirm panel composition and listing directions", "confirmPanelCompositionAndListingDirections");

    private final String label;

    @JsonValue
    private final String code;
}
