package uk.gov.hmcts.reform.sscs.ccd.domain;

import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.ListValue;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "interlocDecision",
        generate = true
)
public class InterlocDecision2 {
    @CCD(
            label = "Interloc decision"
    )
    private List<ListValue<SscsInterlocDecisionDocument>> interlocDecisionDocument;
}
