package uk.gov.hmcts.reform.sscs.ccd.domain;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_issueCodes",
        generate = true
)
@RequiredArgsConstructor
@Getter
public enum IssueCodes implements HasLabel {
    XA("XA"),

    WI("WI"),

    WF("WF"),

    WC("WC"),

    WB("WB"),

    VW("VW"),

    US("US"),

    UM("UM"),

    UL("UL"),

    UE("UE"),

    UA("UA"),

    TT("TT"),

    TP("TP"),

    TO("TO"),

    TL("TL"),

    TE("TE"),

    TD("TD"),

    TB("TB"),

    SX("SX"),

    SU("SU"),

    SS("SS"),

    SR("SR"),

    SM("SM"),

    SG("SG"),

    SF("SF"),

    SD("SD"),

    SC("SC"),

    RY("RY"),

    RT("RT"),

    RS("RS"),

    RR("RR"),

    RL("RL"),

    RI("RI"),

    RG("RG"),

    RE("RE"),

    RD("RD"),

    RC("RC"),

    RB("RB"),

    RA("RA"),

    QC("QC"),

    PT("PT"),

    PR("PR"),

    PF("PF"),

    PD("PD"),

    PC("PC"),

    OX("OX"),

    OS("OS"),

    ON("ON"),

    OL("OL"),

    OK("OK"),

    OI("OI"),

    OC("OC"),

    NW("NW"),

    NV("NV"),

    NP("NP"),

    NC("NC"),

    MO("MO"),

    MN("MN"),

    ML("ML"),

    MI("MI"),

    MG("MG"),

    MD("MD"),

    LX("LX"),

    LT("LT"),

    LM("LM"),

    LH("LH"),

    LE("LE"),

    LC("LC"),

    LA("LA"),

    JL("JL"),

    IS("IS"),

    IQ("IQ"),

    IM("IM"),

    IJ("IJ"),

    ID("ID"),

    IA("IA"),

    HT("HT"),

    HS("HS"),

    HC("HC"),

    HB("HB"),

    GC("GC"),

    FX("FX"),

    FW("FW"),

    FT("FT"),

    FR("FR"),

    FI("FI"),

    FF("FF"),

    FC("FC"),

    FA("FA"),

    EX("EX"),

    EQ("EQ"),

    EI("EI"),

    EC("EC"),

    DX("DX"),

    DR("DR"),

    DQ("DQ"),

    DP("DP"),

    DM("DM"),

    DL("DL"),

    DE("DE"),

    DD("DD"),

    DC("DC"),

    DA("DA"),

    CX("CX"),

    CT("CT"),

    CS("CS"),

    CR("CR"),

    CP("CP"),

    CO("CO"),

    CM("CM"),

    CL("CL"),

    CI("CI"),

    CH("CH"),

    CF("CF"),

    CE("CE"),

    CD("CD"),

    CC("CC"),

    CB("CB"),

    CA("CA"),

    BW("BW"),

    BD("BD"),

    BC("BC"),

    AX("AX"),

    AW("AW"),

    AV("AV"),

    AS("AS"),

    AR("AR"),

    AP("AP"),

    AD("AD"),

    AB("AB"),

    AA("AA"),

    SP("SP"),

    SV("SV"),

    TU("TU"),

    RO("RO"),

    DS("DS"),

    DK("DK");

    private final String label;
}
