package uk.gov.hmcts.reform.sscs.ccd.domain;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.apache.commons.lang3.EnumUtils;

@AllArgsConstructor
@Getter
public enum Issue {
    AA("Invalid"),
    AB("Sanction For Anti-Social Behaviour"),
    AD("Advance Payment"),
    AP("Assessed Income Periods"),
    AR("Alternative Dispute Resolution"),
    AS("Asylum"),
    AT("All Work Test"),
    AV("Availability For Work"),
    AW("Actively Seeking Work"),
    AX("Assessed As Unable To Pay – Complex"),
    BC("Benefit Cap Calculation"),
    BD("Backdating"),
    BR("Bedroom Reduction"),
    BW("Back To Work Bonus"),
    CA("Child Support Reform Conversion Appeals"),
    CB("Contribution Records"),
    CC("Conditions Of Entitlement - Complex"),
    CD("Care (Dla)"),
    CE("Conditions Of Entitlement"),
    CF("Care/Mobility (Dla)"),
    CH("Childcare Costs"),
    CI("Carer Issue"),
    CL("Capital"),
    CM("Child Maintenance Bonus"),
    CO("Community Order"),
    CP("Civil Penalties"),
    CR("Credits"),
    CS("Chest-Pneumo', Asbestos Etc"),
    CT("Court Action"),
    CX("Complex/Multiple Issues"),
    DA("Disability And Carers"),
    DC("Direct Payment Of Hb - Claimant"),
    DD("Appeal Directly  Lodged"),
    DE("Date Of Entitlement"),
    DK("Recovery Of Debt"),
    DL("Direct Payment Of Hb - Landlord"),
    DM("Diffuse Mesothelioma"),
    DP("Disability Premium/Severe Disability Premium"),
    DS("Disqualification From The Scheme"),
    DQ("Disablement Question"),
    DR("Jobseeker's Direction"),
    DX("Death Of An Appellant"),
    EC("(Echr) European Court Of Human Rights"),
    EI("Exportability Issues"),
    EQ("Enquiry Closure"),
    EX("Ex Legislation"),
    FA("Fraudulent Account"),
    FC("Failure To Comply"),
    FF("Funeral Fund"),
    FI("Financial Provider"),
    FR("Failure To Return The Esa50"),
    FT("Failure To Attend"),
    FW("Forestry Worker"),
    FX("Financially Complex"),
    GC("Good Cause"),
    HB("Stayed Hb Appeals"),
    HC("Housing Costs"),
    HI("Hinchy-Related Stayed Appeals"),
    HS("Supported Housing - What Is Eligible For Hb"),
    HT("Habitual Residence Test"),
    IA("Industrial Accident"),
    ID("Industrial Disease"),
    IJ("Personal Injury"),
    IM("Reg. 35 Stay 2014"),
    IQ("Income Query"),
    IS("Incorrect Statement"),
    JL("Joint Liability"),
    LA("Liberty To Apply"),
    LC("Daily Living Component"),
    LE("Late (Extending Back)"),
    LH("Local Housing Allowance"),
    LM("Labour Market Issues"),
    LT("Living Together"),
    LX("Assessed As Unlikely To Pay – Complex"),
    MD("Mobility (Dla)"),
    MG("Minimum Income Guarantee"),
    MI("Minimum Income Guarantee"),
    ML("Daily Living/Mobility"),
    MN("New Scheme (Meso)"),
    MO("Mobility Component"),
    NC("Non Compliance"),
    NP("Amount Paid"),
    NV("No Voucher"),
    NW("Nhs Waiver Decision"),
    OC("Overpayment - Capital"),
    OI("Overpayment Interest"),
    OK("Osteoarthritis Of The Knee"),
    OL("Overpayment - Seek Recovery From Landlord/Letting"),
    ON("One Project"),
    OS("Overpayment - Straightforward"),
    OX("Overpayment - Complex"),
    PC("Property/Capital Settlement"),
    PD("Stayed Pdd1"),
    PF("Persons From Abroad"),
    PR("Premiums"),
    PT("Hardship Payment"),
    QC("Child Issue"),
    RA("Rate Of Assessment/Payability Issues"),
    RB("Reduced Benefit Direction"),
    RC("Rate Of Assessment/Payability Issues - Complex"),
    RD("Rent Officers Decisions"),
    RE("Refusal Of Employment"),
    RG("Reciprocal Agreement"),
    RI("Rent Issues - Including Old Reg 11"),
    RO("Account Usage"),
    RL("Liability To Pay Rent"),
    RR("Reilly Wilson Stay 2 (Lm) 2015"),
    RS("Residency"),
    RT("Reilly Wilson Stay 3 (Lm) 2016"),
    RY("Nhs Certificate"),
    SA("Standard Allowance"),
    SC("Sanction Applied In One Pilot"),
    SD("Stayed Cases"),
    SF("Funeral"),
    SG("Support Group Placement"),
    SM("Maternity"),
    SP("Supplementary Payment"),
    SR("Second Adult Rebate"),
    SS("Self Employed - Straightforward"),
    SU("Suspensions"),
    SV("Severe Conditions"),
    SX("Self Employed - Complex"),
    TB("Termination Of Benefit - Failure To Provide Furthe"),
    TD("Third Party Deduction"),
    TE("Exceptional Circumstances Payments"),
    TL("Time Limited Entitlement"),
    TO("Exceptional Hardship Payments"),
    TP("Transitional Protection"),
    TT("Term-Time"),
    TU("Top-Up Assessments"),
    UA("Assessed As Unable To Pay - Straightforward"),
    UE("Unearned Income"),
    UL("Assessed As Unlikely To Pay - Straightforward"),
    UM("Multiple Element"),
    US("Single Element"),
    VW("Verbal Withdrawal"),
    WB("Stayed Widow's Benefit"),
    WC("Work Capability Assessment"),
    WF("Social Fund Winter Fuel Payments"),
    WI("Failure To Attend A Wfi"),
    XA("Sexual Abuse");

    private final String name;

    public static Issue getIssue(String issueCode) {
        if (EnumUtils.isValidEnum(Issue.class, issueCode)) {
            return Issue.valueOf(issueCode);
        }
        return null;
    }
}
