package uk.gov.hmcts.reform.sscs.ccd.domain;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_issueCodesIbcaOnly",
        generate = true
)
@RequiredArgsConstructor
@Getter
public enum IssueCodesIbcaOnly implements HasLabel {
    DD("DD"),

    SD("SD"),

    CE("CE"),

    RA("RA"),

    OS("OS"),

    OX("OX"),

    SP("SP");

    private final String label;
}
