package uk.gov.hmcts.reform.sscs.ccd.domain;

import java.util.List;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.ListValue;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "judgeNotePad",
        generate = true
)
public class JudgeNotePad {
    @CCD(
            label = "Note pad"
    )
    private List<ListValue<TcwAppealNote>> tcwNotesCollection;

    @CCD(
            label = "Judge's note pad"
    )
    private List<ListValue<JudgeAppealNote>> judgeNotesCollection;
}
