package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_mentalAssessment",
        generate = true
)
@Getter
@AllArgsConstructor
public enum MentalAssessment implements HasLabel {
    LEARNING_TASKS("11. Learning tasks.", "learningTasks"),

    AWARENESS_OF_HAZARDS("12. Awareness of everyday hazards (such as boiling water or sharp objects).", "awarenessOfHazards"),

    PERSONAL_ACTION("13. Initiating and completing personal action (which means planning, organisation, problem solving, prioritising or switching tasks).", "personalAction"),

    COPING_WITH_CHANGE("14. Coping with change.", "copingWithChange"),

    GETTING_ABOUT("15. Getting about.", "gettingAbout"),

    SOCIAL_ENGAGEMENT("16. Coping with social engagement due to cognitive impairment or mental disorder.", "socialEngagement"),

    APPROPRIATENESS_OF_BEHAVIOUR("17. Appropriateness of behaviour with other people, due to cognitive impairment or mental disorder.", "appropriatenessOfBehaviour");

    private final String label;

    @JsonValue
    private final String code;
}
