package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_moveDocumentTo",
        generate = true
)
@Getter
@AllArgsConstructor
public enum MoveDocumentTo implements HasLabel {
    INTERNAL_DOCUMENT("Move document to Tribunal internal documents tab", "internalDocument"),

    DOCUMENT("Move document to Documents tab", "document");

    private final String label;

    @JsonValue
    private final String code;
}
