package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_nonCompliantRequirements",
        generate = true
)
@Getter
@AllArgsConstructor
public enum NonCompliantRequirements implements HasLabel {
    NON_COMPLIANT_UNSIGNED_APPEAL("The Appeal was not signed by the Appellant/Appointee.", "nonCompliantUnsignedAppeal"),

    NON_COMPLIANT_NO_MRN("No MRN submitted in appeal papers by appellant", "nonCompliantNoMRN"),

    NON_COMPLIANT_OTHER("Other", "nonCompliantOther");

    private final String label;

    @JsonValue
    private final String code;
}
