package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_outcome",
        generate = true
)
@Getter
@AllArgsConstructor
public enum Outcome2 implements HasLabel {
    DISABLEMENT_INCREASED_NO_BENEFIT_AWARDED("% Disablement Increased, <80%, No Benefit Awarded", "disablementIncreasedNoBenefitAwarded"),

    APP_ATTEND_ORAL_REQUESTED_DNANO_REASON("Appellant to attend - oral requested - did not attend - no reason", "appAttendOralRequestedDNANoReason"),

    APP_ATTEND_ORAL_REQUESTED_DNAREASON_GIVEN("Appellant to attend - oral requested - did not attend - reason given", "appAttendOralRequestedDNAReasonGiven"),

    APP_ATTEND_PAPER_REQUESTED("Appellant to attend - paper requested or no Enquiry Form returned", "appAttendPaperRequested"),

    DECISION_IN_FAVOUR_OF_APPELLANT("Decision in favour of appellant", "decisionInFavourOfAppellant"),

    DECISION_RESERVED("Decision reserved", "decisionReserved"),

    DECISION_REVISED_AGAINST_APPELLANT("Decision revised against appellant", "decisionRevisedAgainstAppellant"),

    DECISION_UPHELD("Decision upheld", "decisionUpheld"),

    DOCS_SUPPLIED_NOT_BEFORE_TRIBUNAL_AT_HEARING("Documents supplied but not before the Tribunal at the hearing", "docsSuppliedNotBeforeTribunalAtHearing"),

    EVIDENCE_FURTHER_RESPONSE_FROM_RESPONDT_REQD("Evidence or further Response from Respondent required", "evidenceFurtherResponseFromRespondtReqd"),

    EVIDENCE_SUBMISSION_FROM_APPELLANT_REQUIRED("Evidence or submission from Appellant required", "evidenceSubmissionFromAppellantRequired"),

    FME_ESSENTIAL("Further medical evidence essential", "fmeEssential"),

    INSUFFICIENT_TIME("Insufficient time to deal with case", "insufficientTime"),

    LIST_FOR_SUBSTANTIVE("List For Substantive", "listForSubstantive"),

    PAPER_CASE_NOT_HEARD_LACK_OF_TIME("Listed Paper Case not heard due to lack of time", "paperCaseNotHeardLackOfTime"),

    NO_INTERPRETER("No Interpreter", "noInterpreter"),

    OTHER_ADMIN_ERRORS("Other administrative errors (specify error)", "otherAdminErrors"),

    OTHER_REASONS_FOR_ADJOURNING("Other reasons for adjourning", "otherReasonsForAdjourning"),

    OUTWITH_OUTSIDE_JURISDICTION("Outwith/Outside Jurisdiction", "outwithOutsideJurisdiction"),

    PRESENTING_OFFICER_TO_ATTEND("Presenting Officer to attend", "presentingOfficerToAttend"),

    PROCEED_TO_FULL_HEARING("Proceed to full hearing", "proceedToFullHearing"),

    REFERENCE_REVISED_AGAINST_APPELLANT("Reference, Revised against Appellant", "referenceRevisedAgainstAppellant"),

    REFERENCE_REVISED_FAVOUR_APPELLANT("Reference, Revised in Favour of Appellant", "referenceRevisedFavourAppellant"),

    REMADE_DECISION_UPHELD("Remade Decision Upheld", "remadeDecisionUpheld"),

    RESPONDENT_FAILED_TO_COMPLY("Respondent failed to comply with directions", "respondentFailedToComply"),

    STRUCK_OUT("Struck out", "struckOut"),

    STRUCK_OUT_AT_HEARING("Struck out at Hearing", "struckOutAtHearing"),

    WITHDRAWN_AT_HEARING("Withdrawn at Hearing", "withdrawnAtHearing"),

    NON_COMPLIANT_APPEAL_STRUCKOUT("Non Compliant Appeal, Struck out", "nonCompliantAppealStruckout"),

    REINSTATED("Reinstated", "reinstated"),

    ABATED("Abated", "abated");

    private final String label;

    @JsonValue
    private final String code;
}
