package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_panelDoctorSpecialism",
        generate = true
)
@Getter
@AllArgsConstructor
public enum PanelDoctorSpecialism implements HasLabel {
    UROLOGIST("Urologist", "urologist"),

    RHEUMATIC_PHYSICIAN("Rheumatic Physician", "rheumaticPhysician"),

    RENAL_PHYSICIAN("Renal Physician", "renalPhysician"),

    PSYCHIATRIST("Psychiatrist", "psychiatrist"),

    PLASTIC_SURGEON("Plastic Surgeon", "plasticSurgeon"),

    ORTHOPAEDIC_SURGEON("Orthopaedic Surgeon", "orthopaedicSurgeon"),

    NEUROLOGIST("Neurologist", "neurologist"),

    GENERAL_SURGEON("General Surgeon", "generalSurgeon"),

    GENERAL_PRACTITIONER("General Practitioner", "generalPractitioner"),

    GENERAL_PHYSICIAN("General Physician", "generalPhysician"),

    EYE_SURGEON("Eye Surgeon", "eyeSurgeon"),

    ENT_SURGEON("ENT Surgeon", "entSurgeon"),

    DERMATOLOGIST("Dermatologist", "dermatologist"),

    CHEST_SPECIALIST("Chest Specialist", "chestSpecialist"),

    CHEST_PHYSICIAN("Chest Physician", "chestPhysician"),

    CARER("Carer", "carer"),

    CARDIOLOGIST("Cardiologist", "cardiologist");

    private final String label;

    @JsonValue
    private final String code;
}
