package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_parties",
        generate = true
)
@Getter
@AllArgsConstructor
public enum Parties implements HasLabel {
    DWP("FTA", "dwp"),

    APPELLANT("Appellant (or Appointee)", "appellant"),

    REPRESENTATIVE("Representative", "representative"),

    JOINT_PARTY("Joint party", "jointParty"),

    OTHER_PARTY("Other party", "otherParty"),

    OTHER_PARTY_REP("Other party Representative", "otherPartyRep");

    private final String label;

    @JsonValue
    private final String code;
}
