package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_physicalDisabilities",
        generate = true
)
@Getter
@AllArgsConstructor
public enum PhysicalDisabilities implements HasLabel {
    MOBILISING_UNAIDED("1. Mobilising unaided by another person with or without a walking stick, manual wheelchair or other aid if such aid is normally or could reasonably be worn or used.", "mobilisingUnaided"),

    STANDING_AND_SITTING("2. Standing and sitting.", "standingAndSitting"),

    REACHING("3. Reaching.", "reaching"),

    PICKING_UP("4. Picking up and moving or transferring by the use of the upper body and arms.", "pickingUp"),

    MANUAL_DEXTERITY("5. Manual dexterity.", "manualDexterity"),

    MAKING_SELF_UNDERSTOOD("6. Making self understood through speaking, writing, typing, or other means which are normally or could reasonably be used, unaided by another person.", "makingSelfUnderstood"),

    COMMUNICATION("7. Understanding communication by: (i) verbal means (such as hearing or lip reading) alone; (ii) non-verbal means (such as reading 16 point print or Braille) alone; or (iii) a combination of sub-paragraphs (i) and (ii), using any aid that is normally or could reasonably be used, unaided by another person.", "communication"),

    NAVIGATION("8. Navigation and maintaining safety using a guide dog or other aid if either or both are normally used or could reasonably be used.", "navigation"),

    LOSS_OF_CONTROL("9. Absence or loss of control whilst conscious leading to extensive evacuation of the bowel and/or bladder, other than enuresis (bed- wetting), despite the wearing or use of any aids or adaptations which are normally or could reasonably be worn or used.", "lossOfControl"),

    CONSCIOUSNESS("10. Consciousness during waking moments.", "consciousness");

    private final String label;

    @JsonValue
    private final String code;
}
