package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_pipTypeOfHearing",
        generate = true
)
@Getter
@AllArgsConstructor
public enum PipTypeOfHearing implements HasLabel {
    FACE_TO_FACE("Face to face", "faceToFace"),

    TELEPHONE("Telephone", "telephone"),

    VIDEO("Video", "video"),

    PAPER("Paper", "paper"),

    TRIAGE("Triage", "triage");

    private final String label;

    @JsonValue
    private final String code;
}
