package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_pipWriteFinalDecisionManagingToiletNeedsQuestions",
        generate = true
)
@Getter
@AllArgsConstructor
public enum PipWriteFinalDecisionManagingToiletNeedsQuestions implements HasLabel {
    MANAGING_TOILET_NEEDS5A("5a. Can manage toilet needs or incontinence unaided. (0 points)", "managingToiletNeeds5a"),

    MANAGING_TOILET_NEEDS5B("5b. Needs to use an aid or appliance to be able to manage toilet needs or incontinence. (2 points)", "managingToiletNeeds5b"),

    MANAGING_TOILET_NEEDS5C("5c. Needs supervision or prompting to be able to manage toilet needs. (2 points)", "managingToiletNeeds5c"),

    MANAGING_TOILET_NEEDS5D("5d. Needs assistance to be able to manage toilet needs. (4 points)", "managingToiletNeeds5d"),

    MANAGING_TOILET_NEEDS5E("5e. Needs assistance to be able to manage incontinence of either bladder or bowel. (6 points)", "managingToiletNeeds5e"),

    MANAGING_TOILET_NEEDS5F("5f. Needs assistance to be able to manage incontinence of both bladder and bowel. (8 points)", "managingToiletNeeds5f");

    private final String label;

    @JsonValue
    private final String code;
}
