package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_pipWriteFinalDecisionMovingAroundQuestions",
        generate = true
)
@Getter
@AllArgsConstructor
public enum PipWriteFinalDecisionMovingAroundQuestions implements HasLabel {
    MOVING_AROUND12A("12a. Can stand and then move more than 200 metres, either aided or unaided. (0 points)", "movingAround12a"),

    MOVING_AROUND12B("12b. Can stand and then move more than 50 metres but no more than 200 metres, either aided or unaided. (4 points)", "movingAround12b"),

    MOVING_AROUND12C("12c. Can stand and then move unaided more than 20 metres but no more than 50 metres. (8 points)", "movingAround12c"),

    MOVING_AROUND12D("12d. Can stand and then move using an aid or appliance more than 20 metres but no more than 50 metres. (10 points)", "movingAround12d"),

    MOVING_AROUND12E("12e. Can stand and then move more than 1 metre but no more than 20 metres, either aided or unaided. (12 points)", "movingAround12e"),

    MOVING_AROUND12F("12f. Cannot, either aided or unaided,  stand; or (ii) move more than 1 metre. (12 points)", "movingAround12f");

    private final String label;

    @JsonValue
    private final String code;
}
