package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_pipWriteFinalDecisionCommunicatingQuestions",
        generate = true
)
@Getter
@AllArgsConstructor
public enum PipWriteFinalDecisionCommunicatingQuestions implements HasLabel {
    COMMUNICATING7A("7a. Can express and understand verbal information unaided. (0 points)", "communicating7a"),

    COMMUNICATING7B("7b. Needs to use an aid or appliance to be able to speak or hear. (2 points)", "communicating7b"),

    COMMUNICATING7C("7c. Needs communication support to be able to express or understand complex verbal information. (4 points)", "communicating7c"),

    COMMUNICATING7D("7d. Needs communication support to be able to express or understand basic verbal information. (8 points)", "communicating7d"),

    COMMUNICATING7E("7e. Cannot express or understand verbal information at all even with communication support. (12 points)", "communicating7e");

    private final String label;

    @JsonValue
    private final String code;
}
