package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_pipWriteFinalDecisionPlanningFollowingQuestions",
        generate = true
)
@Getter
@AllArgsConstructor
public enum PipWriteFinalDecisionPlanningFollowingQuestions implements HasLabel {
    PLANNING_AND_FOLLOWING11A("11a. Can plan and follow the route of a journey unaided. (0 points)", "planningAndFollowing11a"),

    PLANNING_AND_FOLLOWING11B("11b. Needs prompting to be able to undertake any journey to avoid overwhelming psychological distress to the claimant. (4 points)", "planningAndFollowing11b"),

    PLANNING_AND_FOLLOWING11C("11c. Cannot plan the route of a journey. (8 points)", "planningAndFollowing11c"),

    PLANNING_AND_FOLLOWING11D("11d. Cannot follow the route of an unfamiliar journey without another person, assistance dog or orientation aid. (10 points)", "planningAndFollowing11d"),

    PLANNING_AND_FOLLOWING11E("11e. Cannot undertake any journey because it would cause overwhelming psychological distress to the claimant. (10 points)", "planningAndFollowing11e"),

    PLANNING_AND_FOLLOWING11F("11f. Cannot follow the route of a familiar journey without another person, an assistance dog or an orientation aid. (12 points)", "planningAndFollowing11f");

    private final String label;

    @JsonValue
    private final String code;
}
