package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_pipWriteFinalDecisionBudgetingDecisionsQuestions",
        generate = true
)
@Getter
@AllArgsConstructor
public enum PipWriteFinalDecisionBudgetingDecisionsQuestions implements HasLabel {
    MAKING_BUDGETING_DECISIONS10A("10a. Can manage complex budgeting decisions unaided. (0 points)", "makingBudgetingDecisions10a"),

    MAKING_BUDGETING_DECISIONS10B("10b. Needs prompting or assistance to be able to make complex budgeting decisions. (2 points)", "makingBudgetingDecisions10b"),

    MAKING_BUDGETING_DECISIONS10C("10c. Needs prompting or assistance to be able to make simple budgeting decisions. (4 points)", "makingBudgetingDecisions10c"),

    MAKING_BUDGETING_DECISIONS10D("10d. Cannot make any budgeting decisions at all. (6 points)", "makingBudgetingDecisions10d");

    private final String label;

    @JsonValue
    private final String code;
}
