package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_postHearingReviewType",
        generate = true
)
@Getter
@AllArgsConstructor
public enum PostHearingReviewType2 implements HasLabel {
    SET_ASIDE("Set Aside", "setAside"),

    CORRECTION("Correction", "correction"),

    STATEMENT_OF_REASONS("Statement of Reasons (Out of Time)", "statementOfReasons"),

    LIBERTY_TO_APPLY("Liberty to Apply", "libertyToApply"),

    PERMISSION_TO_APPEAL("Permission to Appeal", "permissionToAppeal");

    private final String label;

    @JsonValue
    private final String code;
}
