package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_rateAwarded",
        generate = true
)
@Getter
@AllArgsConstructor
public enum RateAwarded implements HasLabel {
    NOT_CONSIDERED("Not considered", "notConsidered"),

    NO_AWARD("No award", "noAward"),

    STANDARD_RATE("Standard rate", "standardRate"),

    ENHANCED_RATE("Enhanced rate", "enhancedRate");

    private final String label;

    @JsonValue
    private final String code;
}
