package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_requestingParty",
        generate = true
)
@Getter
@AllArgsConstructor
public enum RequestingParty implements HasLabel {
    APPELLANT("Appellant", "Appellant"),

    DWP("FTA", "DWP"),

    DISTRICT_JUDGE("District Judge", "districtJudge"),

    ORIGINAL_TRIBUNAL_JUDGE("Original Tribunal Judge", "originalTribunalJudge"),

    REGIONAL_TRIBUNAL_JUDGE("Regional Tribunal Judge", "regionalTribunalJudge");

    private final String label;

    @JsonValue
    private final String code;
}
