package uk.gov.hmcts.reform.sscs.ccd.domain;

import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.Document;
import uk.gov.hmcts.ccd.sdk.type.FieldType;
import uk.gov.hmcts.ccd.sdk.type.YesOrNo;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "sscsWelshDocuments",
        generate = true
)
public class SscsWelshDocuments {
    @CCD(
            label = "Document type",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "documentTypeWelsh"
    )
    private DocumentTypeWelsh documentType;

    @CCD(
            label = "Original document Url"
    )
    private Document documentLink;

    @CCD(
            label = "Language",
            typeOverride = FieldType.FixedList,
            typeParameterOverride = "documentLanguage"
    )
    private DocumentLanguage documentLanguage;

    @CCD(
            label = "Document file name"
    )
    private String documentFileName;

    @CCD(
            label = "Comment"
    )
    private String documentComment;

    @CCD(
            label = "Original Document file name"
    )
    private String originalDocumentFileName;

    @CCD(
            label = "Bundle addition"
    )
    private String bundleAddition;

    @CCD(
            label = "Evidence issued"
    )
    private YesOrNo evidenceIssued;

    @CCD(
            label = "Date added"
    )
    private LocalDate documentDateAdded;
}
