package uk.gov.hmcts.reform.sscs.ccd.domain;

import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.type.FieldType;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@ComplexType(
        name = "tcwAppealNote",
        generate = true
)
public class TcwAppealNote {
    @CCD(
            label = "Date of note"
    )
    private LocalDate tcwNoteDate;

    @CCD(
            label = "Note",
            typeOverride = FieldType.TextArea
    )
    private String tcwNoteDetail;

    @CCD(
            label = "Author"
    )
    private String author;
}
