package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_ucWriteFinalDecisionStandingAndSittingQuestion",
        generate = true
)
@Getter
@AllArgsConstructor
public enum UcWriteFinalDecisionStandingAndSittingQuestion implements HasLabel {
    STANDING_AND_SITTING2A("2a. Cannot move between one seated position and another seated position which are located next to one another without receiving physical assistance from another person. (15 points)", "standingAndSitting2a"),

    STANDING_AND_SITTING2B("2b. Cannot, for the majority of the time, remain at a work station: (i) standing unassisted by another person (even if free to move around); (ii) sitting (even in an adjustable chair); or (iii) a combination of paragraphs (i) and (ii), for more than 30 minutes, before needing to move away in order to avoid significant discomfort or exhaustion. (9 points)", "standingAndSitting2b"),

    STANDING_AND_SITTING2C("2c. Cannot, for the majority of the time, remain at a work station: (i) standing unassisted by another person (even if free to move around); (ii) sitting (even in an adjustable chair); or (iii) a combination of paragraphs (i) and (ii), for more than an hour before needing to move away in order to avoid significant discomfort or exhaustion. (6 points)", "standingAndSitting2c"),

    STANDING_AND_SITTING2D("2d. None of the above applies. (0 points)", "standingAndSitting2d");

    private final String label;

    @JsonValue
    private final String code;
}
