package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_ucWriteFinalDecisionMobilisingUnaidedQuestion",
        generate = true
)
@Getter
@AllArgsConstructor
public enum UcWriteFinalDecisionMobilisingUnaidedQuestion implements HasLabel {
    MOBILISING_UNAIDED1A("1a. Cannot, unaided by another person, either: (i) mobilise more than 50 metres on level ground without stopping in order to avoid significant discomfort or exhaustion; or (ii) repeatedly mobilise 50 metres within a reasonable timescale because of significant discomfort or exhaustion. (15 points)", "mobilisingUnaided1a"),

    MOBILISING_UNAIDED1B("1b. Cannot, unaided by another person, mount or descend two steps even with the support of a handrail. (9 points)", "mobilisingUnaided1b"),

    MOBILISING_UNAIDED1C("1c. Cannot, unaided by another person, either: (i) mobilise more than 100 metres on level ground without stopping in order to avoid significant discomfort or exhaustion; or (ii) repeatedly mobilise 100 metres within a reasonable timescale because of significant discomfort or exhaustion. (9 points)", "mobilisingUnaided1c"),

    MOBILISING_UNAIDED1D("1d. Cannot, unaided by another person, either: mobilise more than 200 metres on level ground without stopping in order to avoid significant discomfort or exhaustion; or (ii) repeatedly mobilise 200 metres within a reasonable timescale because of significant discomfort or exhaustion. (6 points)", "mobilisingUnaided1d"),

    MOBILISING_UNAIDED1E("1e. None of the above applies. (0 points)", "mobilisingUnaided1e");

    private final String label;

    @JsonValue
    private final String code;
}
