package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.Getter;

@Getter
@JsonFormat(shape = JsonFormat.Shape.OBJECT)
public enum UkPortOfEntry {
    ALTHORPE("Althorpe", "Sea traffic", "GBSTTRT00"),
    AMBLE("Amble", "Sea traffic", "GBSTBLY00"),
    APPLEDORE("Appledore", "Sea traffic", "GBSTWAT00"),
    AVONMOUTH("Avonmouth", "Sea traffic", "GBSTAVO00"),
    BALTIC_WHARF_ROCHFORD("Baltic Wharf Rochford", "Sea traffic", "GBSTLON00"),
    BARROW_IN_FURNESS("Barrow-In-Furness", "Sea traffic", "GBSTBAR00"),
    BARROW_ON_HUMBER("Barrow-On-Humber", "Sea traffic", "GBSTIMM00"),
    BARRY_DOCK("Barry Dock", "Sea traffic", "GBSTCDF00"),
    BARTON_ON_HUMBER("Barton-On-Humber", "Sea traffic", "GBSTIMM01"),
    BECKINGHAM("Beckingham", "Sea traffic", "GBSTTRT01"),
    BERWICK("Berwick", "Sea traffic", "GBSTBLY01"),
    BIDEFORD("Bideford", "Sea traffic", "GBSTWAT01"),
    BIRKENHEAD("Birkenhead", "Sea traffic", "GBSTLIV00"),
    BLYTH("Blyth", "Sea traffic", "GBSTBLY02"),
    BOSTON("Boston", "Sea traffic", "GBSTBOS00"),
    BRIDGWATER("Bridgwater", "Sea traffic", "GBSTWAT02"),
    BRIDLINGTON("Bridlington", "Sea traffic", "GBSTHUL00"),
    BRIDPORT("Bridport", "Sea traffic", "GBSTWEY00"),
    BRIGHTLINGSEA("Brightlingsea", "Sea traffic", "GBSTCOL00"),
    BRITON_FERRY("Briton Ferry", "Sea traffic", "GBSTPTB00"),
    BRIXHAM("Brixham", "Sea traffic", "GBSTTNM00"),
    BURNHAM_ON_CROUCH("Burnham-on-Crouch", "Sea traffic", "GBSTCOL01"),
    BURTON_STATHER("Burton Stather", "Sea traffic", "GBSTTRT02"),
    CAERNARFON("Caernarfon", "Sea traffic", "GBSTLLA00"),
    CARDIFF("Cardiff", "Sea traffic", "GBSTCDF01"),
    CHARLESTOWN("Charlestown", "Sea traffic", "GBSTFOY00"),
    CHEPSTOW("Chepstow", "Sea traffic", "GBSTNPT00"),
    COLCHESTER("Colchester", "Sea traffic", "GBSTCOL02"),
    COWES("Cowes", "Sea traffic", "GBSTCOW00"),
    DARTMOUTH("Dartmouth", "Sea traffic", "GBSTTNM01"),
    DOVER("Dover", "Sea traffic", "GBSTDOV00"),
    ELLESMERE_PORT("Ellesmere Port", "Sea traffic", "GBSTELL00"),
    EXETER("Exeter", "Sea traffic", "GBSTEXE00"),
    EXMOUTH("Exmouth", "Sea traffic", "GBSTEXE01"),
    FALMOUTH("Falmouth", "Sea traffic", "GBSTFAL00"),
    FAVERSHAM("Faversham", "Sea traffic", "GBSTWTS00"),
    FELIXSTOWE("Felixstowe", "Sea traffic", "GBSTFXT00"),
    FINGRINGHOE("Fingringhoe", "Sea traffic", "GBSTCOL03"),
    FISHGUARD("Fishguard", "Sea traffic", "GBSTFIS00"),
    FLEETWOOD("Fleetwood", "Sea traffic", "GBSTFLE00"),
    FLIXBOROUGH_WHARF("Flixborough Wharf", "Sea traffic", "GBSTTRT03"),
    FOWEY("Fowey", "Sea traffic", "GBSTFOY01"),
    GAINSBOROUGH("Gainsborough", "Sea traffic", "GBSTTRT04"),
    GARSTON("Garston", "Sea traffic", "GBSTLIV01"),
    GLASSON_DOCK("Glasson Dock", "Sea traffic", "GBSTHEY00"),
    GLOUCESTER("Gloucester", "Sea traffic", "GBSTSSS00"),
    GOOLE("Goole", "Sea traffic", "GBSTGOO00"),
    GREAT_YARMOUTH("Great Yarmouth", "Sea traffic", "GBSTGTY00"),
    GRIMSBY("Grimsby", "Sea traffic", "GBSTGRI00"),
    GROVE_WHARVES("Grove Wharves", "Sea traffic", "GBSTTRT05"),
    GUNESS_WHARF("Guness Wharf", "Sea traffic", "GBSTTRT06"),
    HARTLEPOOL("Hartlepool", "Sea traffic", "GBSTHTP00"),
    HARWICH("Harwich", "Sea traffic", "GBSTHRH00"),
    HEYSHAM("Heysham", "Sea traffic", "GBSTHEY01"),
    HOLEHAVEN("Holehaven", "Sea traffic", "GBSTLON01"),
    HOLYHEAD("Holyhead", "Sea traffic", "GBSTHLD00"),
    HOWDENDYKE("Howdendyke", "Sea traffic", "GBSTGOO01"),
    HULL("Hull", "Sea traffic", "GBSTHUL01"),
    IMMINGHAM("Immingham", "Sea traffic", "GBSTIMM02"),
    IPSWICH("Ipswich", "Sea traffic", "GBSTIPS00"),
    KEADBY("Keadby", "Sea traffic", "GBSTTRT07"),
    KINGS_LYNN("Kings Lynn", "Sea traffic", "GBSTKLN00"),
    LANCASTER("Lancaster", "Sea traffic", "GBSTHEY02"),
    LEIGH_ON_SEA("Leigh-On-Sea", "Sea traffic", "GBSTLON02"),
    LITTLEHAMPTON("Littlehampton", "Sea traffic", "GBSTSHO00"),
    LIVERPOOL("Liverpool", "Sea traffic", "GBSTLIV02"),
    LLANDDULAS("Llanddulas", "Sea traffic", "GBSTLLA01"),
    LLANELLI("Llanelli", "Sea traffic", "GBSTSWA00"),
    LONDON("London", "Sea traffic", "GBSTLON03"),
    LONDON_GATEWAY("London Gateway", "Sea traffic", "GBSTLGP00"),
    LOWESTOFT("Lowestoft", "Sea traffic", "GBSTLOW00"),
    LYMINGTON("Lymington", "Sea traffic", "GBSTSTN00"),
    MALDON("Maldon", "Sea traffic", "GBSTCOL04"),
    MANCHESTER("Manchester", "Sea traffic", "GBSTMNC00"),
    MEDWAY("Medway", "Sea traffic", "GBSTMED00"),
    MIDDLESBROUGH("Middlesbrough", "Sea traffic", "GBSTMID00"),
    MILFORD("Milford", "Sea traffic", "GBSTMIL00"),
    MILLOM("Millom", "Sea traffic", "GBSTBAR01"),
    MISTLEY("Mistley", "Sea traffic", "GBSTHRH01"),
    MOSTYN("Mostyn", "Sea traffic", "GBSTMOS00"),
    NEAP_HOUSE("Neap House", "Sea traffic", "GBSTTRT08"),
    NEATH_ABBEY("Neath Abbey", "Sea traffic", "GBSTPTB01"),
    NEWCASTLE("Newcastle", "Sea traffic", "GBSTTYN00"),
    NEWHAVEN("Newhaven", "Sea traffic", "GBSTNHV00"),
    NEW_HOLLAND("New Holland", "Sea traffic", "GBSTIMM03"),
    NEWLYN("Newlyn", "Sea traffic", "GBSTPEN00"),
    NEWPORT_GWENT("Newport Gwent", "Sea traffic", "GBSTNPT01"),
    NORTH_SHIELDS("North Shields", "Sea traffic", "GBSTTYN01"),
    NORTHWICH("Northwich", "Sea traffic", "GBSTNTH00"),
    NORWICH("Norwich", "Sea traffic", "GBSTNOR00"),
    PADSTOW("Padstow", "Sea traffic", "GBSTPLY00"),
    PAR("Par", "Sea traffic", "GBSTPAR00"),
    PARKESTON_QUAY("Parkeston Quay", "Sea traffic", "GBSTHRH02"),
    PARTINGTON("Partington", "Sea traffic", "GBSTMNC01"),
    PEMBROKE_FERRY("Pembroke Ferry", "Sea traffic", "GBSTMIL01"),
    PEMBROKE_OILS_SO("Pembroke (Oils) So", "Sea traffic", "GBSTMIL02"),
    PEMBROKE_EPU("Pembroke Epu", "Sea traffic", "GBSTMIL03"),
    PENRYN("Penryn", "Sea traffic", "GBSTFAL01"),
    PENZANCE("Penzance", "Sea traffic", "GBSTPEN01"),
    PLYMOUTH("Plymouth", "Sea traffic", "GBSTPLY01"),
    POOLE("Poole", "Sea traffic", "GBSTPOO00"),
    PORT_PENRHYN("Port Penrhyn", "Sea traffic", "GBSTLLA02"),
    PORTISHEAD("Portishead", "Sea traffic", "GBSTAVO01"),
    PORTLAND("Portland", "Sea traffic", "GBSTPTL00"),
    PORTSMOUTH("Portsmouth", "Sea traffic", "GBSTPTM00"),
    PORT_TALBOT("Port Talbot", "Sea traffic", "GBSTPTB02"),
    QUEENBOROUGH("Queenborough", "Sea traffic", "GBSTMED01"),
    RAMSGATE("Ramsgate", "Sea traffic", "GBSTRMG00"),
    RHYL("Rhyl", "Sea traffic", "GBSTMOS01"),
    RIDHAM_DOCK("Ridham Dock", "Sea traffic", "GBSTMED02"),
    ROCHESTER("Rochester", "Sea traffic", "GBSTMED03"),
    ROCHFORD("Rochford", "Sea traffic", "GBSTLON04"),
    ROWHEDGE("Rowhedge", "Sea traffic", "GBSTCOL05"),
    ROYAL_PORTBURY_DOCK("Royal Portbury Dock", "Sea traffic", "GBSTAVO02"),
    RUNCORN("Runcorn", "Sea traffic", "GBSTRUN00"),
    RYE("Rye", "Sea traffic", "GBSTFOL00"),
    SCARBOROUGH("Scarborough", "Sea traffic", "GBSTSCA00"),
    SCUNTHORPE("Scunthorpe", "Sea traffic", "GBSTTRT10"),
    SEAHAM("Seaham", "Sea traffic", "GBSTSUN00"),
    SELBY("Selby", "Sea traffic", "GBSTGOO02"),
    SHARPNESS("Sharpness", "Sea traffic", "GBSTSSS01"),
    SHEERNESS("Sheerness", "Sea traffic", "GBSTMED04"),
    SHOREHAM("Shoreham", "Sea traffic", "GBSTSHO01"),
    SHOTTON("Shotton", "Sea traffic", "GBSTMOS02"),
    SILLOTH("Silloth", "Sea traffic", "GBSTSIL00"),
    SOUTHAMPTON("Southampton", "Sea traffic", "GBSTSTN01"),
    SOUTHEND_CORPORATION_JETTY("Southend (Corporation Jetty)", "Sea traffic", "GBSTLON05"),
    SOUTH_SHIELDS("South Shields", "Sea traffic", "GBSTTYN02"),
    SUNDERLAND("Sunderland", "Sea traffic", "GBSTSUN01"),
    SWANSEA("Swansea", "Sea traffic", "GBSTSWA01"),
    TEESPORT("Teesport", "Sea traffic", "GBSTMID01"),
    TEIGNMOUTH("Teignmouth", "Sea traffic", "GBSTTNM02"),
    TILBURY("Tilbury", "Sea traffic", "GBSTLON06"),
    THAMES_EUROPORT("Thames Europort", "Sea traffic", "GBSTTEP00"),
    THAMESPORT("Thamesport", "Sea traffic", "GBSTTHP00"),
    TOPSHAM("Topsham", "Sea traffic", "GBSTEXE02"),
    TORQUAY("Torquay", "Sea traffic", "GBSTTNM03"),
    TRENT("Trent", "Sea traffic", "GBSTTRT11"),
    TRURO("Truro", "Sea traffic", "GBSTFAL02"),
    TYNE("Tyne", "Sea traffic", "GBSTTYN03"),
    WARRINGTON("Warrington", "Sea traffic", "GBSTRUN01"),
    WATCHET("Watchet", "Sea traffic", "GBSTWAT03"),
    WELLS("Wells", "Sea traffic", "GBSTNOR01"),
    WEYMOUTH("Weymouth", "Sea traffic", "GBSTWEY01"),
    WHITBY("Whitby", "Sea traffic", "GBSTWTB00"),
    WHITEHAVEN("Whitehaven", "Sea traffic", "GBSTWHV00"),
    WHITSTABLE("Whitstable", "Sea traffic", "GBSTWTS01"),
    WISBECH("Wisbech", "Sea traffic", "GBSTWIS00"),
    WIVENHOE("Wivenhoe", "Sea traffic", "GBSTCOL06"),
    WORKINGTON("Workington", "Sea traffic", "GBSTWOR00"),
    ABERDEEN("Aberdeen", "Sea traffic", "GBSTABD00"),
    ANNAN("Annan", "Sea traffic", "GBSTGRK00"),
    ARBROATH("Arbroath", "Sea traffic", "GBSTDUN00"),
    ARDROSSAN("Ardrossan", "Sea traffic", "GBSTARD00"),
    AYR("Ayr", "Sea traffic", "GBSTAYR00"),
    BARCALDINE("Barcaldine", "Sea traffic", "GBSTGRK01"),
    BRAEFOOT_BAY("Braefoot Bay", "Sea traffic", "GBSTGRG00"),
    BOWLING("Bowling", "Sea traffic", "GBSTGLW00"),
    BUCKIE("Buckie", "Sea traffic", "GBSTFRB00"),
    BURGHEAD("Burghead", "Sea traffic", "GBSTINV00"),
    BURNTISLAND("Burntisland", "Sea traffic", "GBSTGRG01"),
    CAMPBELTOWN("Campbeltown", "Sea traffic", "GBSTGRK02"),
    CORPACH_INCL_ANNAT_PIER("Corpach Incl Annat Pier", "Sea traffic", "GBSTINV01"),
    DUNDEE("Dundee", "Sea traffic", "GBSTDUN01"),
    FASLANE("Faslane", "Sea traffic", "GBSTGRK03"),
    FINNART("Finnart", "Sea traffic", "GBSTGRK04"),
    FRASERBURGH("Fraserburgh", "Sea traffic", "GBSTFRB01"),
    FURNACE("Furnace", "Sea traffic", "GBSTGRK05"),
    GARLIESTON("Garlieston", "Sea traffic", "GBSTGRK06"),
    GIRVAN("Girvan", "Sea traffic", "GBSTAYR01"),
    GLASGOW("Glasgow", "Sea traffic", "GBSTGLW01"),
    GRANGEMOUTH("Grangemouth", "Sea traffic", "GBSTGRG02"),
    GREENOCK("Greenock", "Sea traffic", "GBSTGRK07"),
    HOUND_POINT_TERMINAL("Hound Point Terminal", "Sea traffic", "GBSTHPT00"),
    HUNTERSTON("Hunterston", "Sea traffic", "GBSTGRK08"),
    INVERGORDON("Invergordon", "Sea traffic", "GBSTIVG00"),
    INVERKEITHING("Inverkeithing", "Sea traffic", "GBSTGRG03"),
    INVERNESS("Inverness", "Sea traffic", "GBSTINV02"),
    IRVINE("Irvine", "Sea traffic", "GBSTIRV00"),
    ISLAY("Islay", "Sea traffic", "GBSTGRK09"),
    KIRKCALDY("Kirkcaldy", "Sea traffic", "GBSTKKD00"),
    KIRKWALL("Kirkwall", "Sea traffic", "GBSTKWL00"),
    LEITH("Leith", "Sea traffic", "GBSTLEI00"),
    LERWICK("Lerwick", "Sea traffic", "GBSTLER00"),
    LOCHALINE("Lochaline", "Sea traffic", "GBSTINV03"),
    LOSSIEMOUTH("Lossiemouth", "Sea traffic", "GBSTINV04"),
    MACDUFF("Macduff", "Sea traffic", "GBSTFRB02"),
    METHIL("Methil", "Sea traffic", "GBSTGRG04"),
    MONTROSE("Montrose", "Sea traffic", "GBSTMON00"),
    OBAN("Oban", "Sea traffic", "GBSTGRK10"),
    PALNACKIE("Palnackie", "Sea traffic", "GBSTGRK11"),
    PERTH("Perth", "Sea traffic", "GBSTDUN02"),
    PETERHEAD("Peterhead", "Sea traffic", "GBSTPHD00"),
    ROSYTH("Rosyth", "Sea traffic", "GBSTROS00"),
    SCALLOWAY("Scalloway", "Sea traffic", "GBSTLER01"),
    SCRABSTER("Scrabster", "Sea traffic", "GBSTINV05"),
    STORNOWAY("Stornoway", "Sea traffic", "GBSTSTO00"),
    STRANRAER("Stranraer", "Sea traffic", "GBSTGRK12"),
    STROMNESS("Stromness", "Sea traffic", "GBSTKWL01"),
    TAYPORT("Tayport", "Sea traffic", "GBSTDUN03"),
    ULLAPOOL("Ullapool", "Sea traffic", "GBSTINV06"),
    WICK("Wick", "Sea traffic", "GBSTINV07"),
    ABERDEEN_AIRPORT("Aberdeen Airport", "Air traffic", "GBATABZ00"),
    BIGGIN_HILL_AIRPORT("Biggin Hill Airport", "Air traffic", "GBATBQH00"),
    BIRMINGHAM_AIRPORT("Birmingham Airport", "Air traffic", "GBATBHX00"),
    BLACKPOOL_INTERNATIONAL_AIRPORT("Blackpool International Airport", "Air traffic", "GBATBLK00"),
    BOURNEMOUTH_HURN_AIRPORT("Bournemouth (Hurn) Airport", "Air traffic", "GBATBOH00"),
    BRISTOL_AIRPORT("Bristol Airport", "Air traffic", "GBATBRS00"),
    CAMBRIDGE_AIRPORT("Cambridge Airport", "Air traffic", "GBATCBG00"),
    CARDIFF_WALES_AIRPORT("Cardiff (Wales) Airport", "Air traffic", "GBATCWL00"),
    COVENTRY_AIRPORT("Coventry Airport", "Air traffic", "GBATCVT00"),
    DURHAM_TEES_VALLEY_TEESSIDE_AIRPORT("Durham Tees Valley (Teesside) Airport", "Air traffic", "GBATMME00"),
    EAST_MIDLANDS_AIRPORT("East Midlands Airport", "Air traffic", "GBATEMA00"),
    EDINBURGH_AIRPORT("Edinburgh Airport", "Air traffic", "GBATEDI00"),
    EXETER_AIRPORT("Exeter Airport", "Air traffic", "GBATEXT00"),
    FARNBOROUGH_AIRPORT("Farnborough Airport", "Air traffic", "GBATFAB00"),
    FILTON_AERODROME_BRISTOL("Filton Aerodrome (Bristol)", "Air traffic", "GBATFZO00"),
    GLASGOW_AIRPORT("Glasgow Airport", "Air traffic", "GBATGLA00"),
    HUMBERSIDE_INTERNATIONAL_AIRPORT("Humberside International Airport", "Air traffic", "GBATHUY00"),
    LEEDS_BRADFORD_AIRPORT("Leeds Bradford Airport", "Air traffic", "GBATLBA00"),
    LIVERPOOL_JOHN_LENNON_AIRPORT("Liverpool John Lennon Airport", "Air traffic", "GBATLPL00"),
    LONDON_ASHFORD_LYDD_AIRPORT("London Ashford (Lydd) Airport", "Air traffic", "GBATLYD00"),
    LONDON_CITY_AIRPORT("London City Airport", "Air traffic", "GBATLCY00"),
    LONDON_GATWICK_AIRPORT("London Gatwick Airport", "Air traffic", "GBATLGW00"),
    LONDON_HEATHROW_AIRPORT("London Heathrow Airport", "Air traffic", "GBATLHR00"),
    LONDON_LUTON_AIRPORT("London Luton Airport", "Air traffic", "GBATLTN00"),
    LONDON_STANSTED_AIRPORT("London Stansted Airport", "Air traffic", "GBATLSA00"),
    MANCHESTER_AIRPORT("Manchester Airport", "Air traffic", "GBATMAN00"),
    MANSTON_AIRPORT("Manston Airport", "Air traffic", "GBATMSE00"),
    NEWCASTLE_AIRPORT("Newcastle Airport", "Air traffic", "GBATNCL00"),
    NEWQUAY_AIRPORT("Newquay Airport", "Air traffic", "GBATNQY00"),
    NORWICH_AIRPORT("Norwich Airport", "Air traffic", "GBATNWI00"),
    PLYMOUTH_AIRPORT("Plymouth Airport", "Air traffic", "GBATPLH00"),
    PRESTWICK_AIRPORT("Prestwick Airport", "Air traffic", "GBATPIK00"),
    SHOREHAM_AIRPORT("Shoreham Airport", "Air traffic", "GBATESH00"),
    SOUTHAMPTON_EASTLEIGH_AIRPORT("Southampton (Eastleigh) Airport", "Air traffic", "GBATSOU00"),
    SOUTHEND_AIRPORT("Southend Airport", "Air traffic", "GBATSEN00"),
    SUMBURGH_AIRPORT_SHETLAND("Sumburgh Airport (Shetland)", "Air traffic", "GBATLSI00"),
    BECCLES_AIRPORT("Beccles Airport", "Air traffic", "GBATBCC00"),
    GLOUCESTER_STAVERTON_AIRPORT("Gloucester (Staverton) Airport", "Air traffic", "GBATGLO00"),
    KEMBLE_AIRPORT("Kemble Airport", "Air traffic", "GBATKEM00"),
    LASHAM_AIRPORT("Lasham Airport", "Air traffic", "GBATLAS00"),
    OXFORD_AIRPORT_KIDLINGTON("Oxford Airport (Kidlington)", "Air traffic", "GBATOAK00"),
    ROBIN_HOOD_DONCASTER_SHEFFIELD("Robin Hood Doncaster Sheffield", "Air traffic", "GBATDSA00"),
    SYWELL_AERODROME("Sywell Aerodrome", "Air traffic", "GBATSYW00"),
    STORNOWAY_AIRPORT("Stornoway Airport", "Air traffic", "GBATSTY00"),
    WARTON_AERODROME("Warton Aerodrome", "Air traffic", "GBATWAR00"),
    WICK_AIRPORT("Wick Airport", "Air traffic", "GBATWIK00"),
    YEOVIL_AERODROME("Yeovil Aerodrome", "Air traffic", "GBATYVL00"),
    BRIZE_NORTON("Brize Norton", "Air traffic", "GBATBZN00"),
    FAIRFORD("Fairford", "Air traffic", "GBATFFD00"),
    FELTWELL("Feltwell", "Air traffic", "GBATFLT00"),
    LAKENHEATH("Lakenheath", "Air traffic", "GBATLKH00"),
    LYNEHAM("Lyneham", "Air traffic", "GBATLYH00"),
    MENWITH_HILL("Menwith Hill", "Air traffic", "GBATMWH00"),
    MILDENHALL("Mildenhall", "Air traffic", "GBATMDH00"),
    NORTHOLT("Northolt", "Air traffic", "GBATNHT00"),
    WADDINGTON("Waddington", "Air traffic", "GBATWAD00"),
    ASHFORD("Ashford", "Rail traffic", "GBRTASD00"),
    BARKING("Barking", "Rail traffic", "GBRTLBK00"),
    DAGENHAM("Dagenham", "Rail traffic", "GBRTDAG00"),
    DAVENTRY("Daventry", "Rail traffic", "GBRTDVY00"),
    DOLLANDS_MOOR("Dollands Moor", "Rail traffic", "GBRTNGO00"),
    DONCASTER("Doncaster", "Rail traffic", "GBRTDON00"),
    WIDNES("Widnes", "Rail traffic", "GBRTWDN00"),
    DOVER_EUROTUNNEL("Dover / Eurotunnel", "Unknown traffic", "GBUTDEU00"),
    EUROTUNNEL("Eurotunnel", "Unknown traffic", "GBUTEUT00"),
    KILLINGHOLME("Killingholme", "Unknown traffic", "GBUTKIL00"),
    PURFLEET("Purfleet", "Unknown traffic", "GBUTPUF00");



    private final String label;
    private final String trafficType;
    private final String locationCode;

    UkPortOfEntry(String label, String trafficType, String locationCode) {
        this.label = label;
        this.trafficType = trafficType;
        this.locationCode = locationCode;
    }
}
