package uk.gov.hmcts.reform.sscs.ccd.domain;

import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.CCD;
import uk.gov.hmcts.ccd.sdk.api.HasRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@Getter
@AllArgsConstructor
public enum UserRole implements HasRole {
    CASEWORKER_RAS_VALIDATION("caseworker-ras-validation", "R"),

    GS_PROFILE("GS_profile", "R"),

    CASEWORKER_SSCS_ANONYMOUSCITIZEN("caseworker-sscs-anonymouscitizen", "D"),

    CASEWORKER_SSCS_SYSTEMUPDATE("caseworker-sscs-systemupdate", "CRUD"),

    CASEWORKER_SSCS("caseworker-sscs", "D"),

    CASEWORKER_SSCS_CALLAGENT("caseworker-sscs-callagent", "D"),

    CASEWORKER_SSCS_JUDGE("caseworker-sscs-judge", "D"),

    CITIZEN("citizen", "CRUD"),

    CASEWORKER_SSCS_SUPERUSER("caseworker-sscs-superuser", "D"),

    CASEWORKER_WA_TASK_CONFIGURATION("caseworker-wa-task-configuration", "CRU"),

    CASEWORKER_SSCS_PCQEXTRACTOR("caseworker-sscs-pcqextractor", "D"),

    CASEWORKER_SSCS_CLERK("caseworker-sscs-clerk", ""),

    CASEWORKER_SSCS_DWPRESPONSEWRITER("caseworker-sscs-dwpresponsewriter", ""),

    CASEWORKER_SSCS_REGISTRAR("caseworker-sscs-registrar", ""),

    CASEWORKER_SSCS_HMRCRESPONSEWRITER("caseworker-sscs-hmrcresponsewriter", ""),

    CASEWORKER_SSCS_PANELMEMBER("caseworker-sscs-panelmember", ""),

    CASEWORKER_SSCS_IBCARESPONSEWRITER("caseworker-sscs-ibcaresponsewriter", ""),

    CASEWORKER_SSCS_TEAMLEADER("caseworker-sscs-teamleader", ""),

    CASEWORKER_SSCS_BULKSCAN("caseworker-sscs-bulkscan", ""),

    CASEWORKER_SSCS_JUDGE_SALARIED("caseworker-sscs-judge-salaried", ""),

    @CCD(
            label = "Creator",
            hint = "Creator"
    )
    CREATOR("[CREATOR]", "");

    private final String role;

    private final String caseTypePermissions;
}
