package uk.gov.hmcts.reform.sscs.ccd.domain;

import com.fasterxml.jackson.annotation.JsonValue;
import lombok.AllArgsConstructor;
import lombok.Getter;
import uk.gov.hmcts.ccd.sdk.api.ComplexType;
import uk.gov.hmcts.ccd.sdk.api.HasLabel;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 */
@ComplexType(
        name = "FL_withDwpWorkflow",
        generate = true
)
@Getter
@AllArgsConstructor
public enum WithDwpWorkflow implements HasLabel {
    SENT_TO_DWP("Sent to FTA", "sentToDwp"),

    FAILED_SENDING("Failed sending", "failedSending"),

    FAILED_SENDING_FURTHER_EVIDENCE("Failed sending further evidence", "failedSendingFurtherEvidence"),

    FAILED_ROBOTICS("Failed sending to robotics", "failedRobotics"),

    SENT_TO_ROBOTICS("Sent to robotics", "sentToRobotics");

    private final String label;

    @JsonValue
    private final String code;
}
