package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.DocumentGeneration;
import uk.gov.hmcts.reform.sscs.ccd.domain.PostponementRequest;
import uk.gov.hmcts.reform.sscs.ccd.domain.SchedulingAndListingFields;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;
import uk.gov.hmcts.reform.sscs.ccd.domain.WorkAllocationFields;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code 1.0} of event {@code actionPostponementRequest}.
 */
public final class ActionPostponementRequestNonprodPage10 {
    private ActionPostponementRequestNonprodPage10() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("1.0");
        fields.pageLabel("Action Postponement Request");
        fields.complex(SscsCaseData::getWorkAllocationFields)
                    .readonly(WorkAllocationFields::getDaysToHearing)
                    .fieldShowCondition("[STATE]=\"doNotUse\"").done();
        fields.readonly(SscsCaseData::getInterlocReviewState)
                    .fieldShowCondition("[STATE]=\"DoNotShow\"")
                    .publishAs("action");
        fields.complex(SscsCaseData::getSchedulingAndListingFields)
                    .readonly(SchedulingAndListingFields::getHearingRoute)
                    .fieldShowCondition("listingOption=\"DoNotShow\"").done();
        fields.complex(SscsCaseData::getPostponementRequest)
                    .mandatory(PostponementRequest::getActionPostponementRequestSelected)
                    .mandatory(PostponementRequest::getPostponementRequestDetails)
                    .fieldShowCondition("actionPostponementRequestSelected=\"sendToJudge\"").done();
        fields.complex(SscsCaseData::getDocumentGeneration)
                    .mandatory(DocumentGeneration::getBodyContent)
                    .fieldShowCondition("actionPostponementRequestSelected=\"grant\" OR actionPostponementRequestSelected=\"refuse\"").done();
        fields.optional(SscsCaseData::getReservedToJudgeInterloc)
                    .fieldShowCondition("actionPostponementRequestSelected=\"sendToJudge\" OR actionPostponementRequestSelected=\"grant\" OR actionPostponementRequestSelected=\"refuse\"");
        fields.complex(SscsCaseData::getDocumentGeneration)
                    .mandatory(DocumentGeneration::getSignedBy)
                    .fieldShowCondition("actionPostponementRequestSelected=\"grant\" OR actionPostponementRequestSelected=\"refuse\"")
                    .mandatory(DocumentGeneration::getSignedRole)
                    .fieldShowCondition("actionPostponementRequestSelected=\"grant\" OR actionPostponementRequestSelected=\"refuse\"").done();
        fields.complex(SscsCaseData::getPostponementRequest)
                    .mandatory(PostponementRequest::getListingOption)
                    .fieldShowCondition("actionPostponementRequestSelected=\"grant\"").done();
        fields.mandatory(SscsCaseData::getDirectionDueDate)
                    .fieldShowCondition("listingOption=\"notListable\"");
        fields.optional(SscsCaseData::getTribunalDirectPoToAttend)
                    .fieldShowCondition("hearingRoute=\"listAssist\"");
    }
}
