package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.JointParty;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsHearingRecordingCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code selectHearing} of event {@code actionHearingRecordingRequest}.
 */
public final class ActionHearingRecordingRequestSelectHearingPage {
    private ActionHearingRecordingRequestSelectHearingPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("selectHearing");
        fields.pageLabel("Action hearing recording request");
        fields.complex(SscsCaseData::getSscsHearingRecordingCaseData)
                    .mandatory(SscsHearingRecordingCaseData::getSelectHearingDetails).done();
        fields.complex(SscsCaseData::getJointParty)
                    .readonlyNoSummary(JointParty::getHasJointParty)
                    .fieldShowCondition("processHearingRecordingRequest=\"doNotUse\"").done();
        fields.readonlyNoSummary(SscsCaseData::getAppeal)
                    .fieldShowCondition("processHearingRecordingRequest=\"doNotUse\"");
    }
}
