package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.JointParty;
import uk.gov.hmcts.reform.sscs.ccd.domain.ScannedDocument;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;
import uk.gov.hmcts.reform.sscs.ccd.domain.WorkAllocationFields;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code 1.0} of event {@code actionFurtherEvidence}.
 */
public final class ActionFurtherEvidencePage10 {
    private ActionFurtherEvidencePage10() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("1.0");
        fields.pageLabel("Handle Further Evidence");
        fields.complex(SscsCaseData::getWorkAllocationFields)
                    .mandatory(WorkAllocationFields::getScannedDocumentTypes)
                    .fieldShowCondition("[STATE]=\"DoNotShow\"").done();
        fields.mandatory(SscsCaseData::getIssueFinalDecisionDate)
                    .fieldShowCondition("[STATE]=\"DoNotUse\"");
        fields.mandatory(SscsCaseData::getIssueInterlocDecisionDate)
                    .fieldShowCondition("[STATE]=\"DoNotUse\"");
        fields.complex(SscsCaseData::getJointParty)
                    .mandatory(JointParty::getHasJointParty)
                    .fieldShowCondition("[STATE]=\"DoNotUse\"").done();
        fields.mandatory(SscsCaseData::getOtherParties)
                    .fieldShowCondition("[STATE]=\"DoNotUse\"");
        fields.mandatory(SscsCaseData::getFurtherEvidenceAction);
        fields.mandatory(SscsCaseData::getOriginalSender);
        fields.complex(SscsCaseData::getScannedDocuments).done();
        fields.complex(SscsCaseData::getScannedDocuments, ScannedDocument.class)
                    .optional(ScannedDocument::getType)
                    .mandatory(ScannedDocument::getUrl)
                    .optional(ScannedDocument::getEditedUrl)
                    .fieldShowCondition("isConfidentialCase = \"Yes\"")
                    .optional(ScannedDocument::getControlNumber)
                    .mandatory(ScannedDocument::getFileName)
                    .mandatory(ScannedDocument::getScannedDate)
                    .optional(ScannedDocument::getExceptionRecordReference)
                    .readonly(ScannedDocument::getOriginalSenderOtherPartyId)
                    .fieldShowCondition("originalSenderOtherPartyId != \"\"")
                    .readonly(ScannedDocument::getOriginalSenderOtherPartyName)
                    .fieldShowCondition("originalSenderOtherPartyName != \"\"")
                    .optional(ScannedDocument::getSubtype)
                    .optional(ScannedDocument::getIncludeInBundle)
                    .optional(ScannedDocument::getDocumentTabChoice)
                    .fieldShowCondition("documentTabChoice!=\"DONOTSHOW\"").done();
        fields.optional(SscsCaseData::getDirectionDueDate);
    }
}
