package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.Adjournment;
import uk.gov.hmcts.reform.sscs.ccd.domain.SchedulingAndListingFields;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code typeOfAdjournment} of event {@code adjournCase}.
 */
public final class AdjournCaseTypeOfAdjournmentPage {
    private AdjournCaseTypeOfAdjournmentPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("typeOfAdjournment");
        fields.pageLabel("Upload or generate a notice");
        fields.complex(SscsCaseData::getSchedulingAndListingFields)
                    .readonlyNoSummary(SchedulingAndListingFields::getHearingRoute)
                    .fieldShowCondition("adjournCaseGenerateNotice=\"DoNotShow\"").done();
        fields.complex(SscsCaseData::getAdjournment)
                    .mandatory(Adjournment::getGenerateNotice).done();
    }
}
