package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.Adjournment;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code nextHearingListingDuration} of event {@code adjournCase}.
 */
public final class AdjournCaseNextHearingListingDurationPage {
    private AdjournCaseNextHearingListingDurationPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("nextHearingListingDuration");
        fields.pageLabel("How long should the next hearing be listed for?");
        fields.showCondition("adjournCaseTypeOfNextHearing = \"faceToFace\" OR adjournCaseTypeOfNextHearing = \"video\" OR adjournCaseTypeOfNextHearing = \"telephone\"");
        fields.complex(SscsCaseData::getAdjournment)
                    .mandatory(Adjournment::getNextHearingListingDurationType)
                    .mandatory(Adjournment::getNextHearingListingDuration)
                    .fieldShowCondition("adjournCaseNextHearingListingDurationType = \"nonStandardTimeSlot\"")
                    .retainHiddenValue()
                    .readonly(Adjournment::getInterpreterDurationLabel)
                    .fieldShowCondition("adjournCaseNextHearingListingDurationType = \"nonStandardTimeSlot\"")
                    .mandatory(Adjournment::getNextHearingListingDurationUnits)
                    .fieldShowCondition("adjournCaseNextHearingListingDurationType = \"nonStandardTimeSlot\"")
                    .retainHiddenValue().done();
    }
}
