package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.PostponementRequest;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code 3.0} of event {@code adminSendToInterlocutoryReviewState}.
 */
public final class AdminSendToInterlocutoryReviewStatePage30 {
    private AdminSendToInterlocutoryReviewStatePage30() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("3.0");
        fields.pageLabel("Preview postponement request document");
        fields.showCondition("selectWhoReviewsCase=\"postponementRequestInterlocSendToTcw\"");
        fields.complex(SscsCaseData::getPostponementRequest)
                    .mandatory(PostponementRequest::getPostponementPreviewDocument).done();
    }
}
