package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.DocumentGeneration;
import uk.gov.hmcts.reform.sscs.ccd.domain.DocumentStaging;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code 1.0} of event {@code decisionIssued}.
 */
public final class DecisionIssuedPage10 {
    private DecisionIssuedPage10() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("1.0");
        fields.pageLabel("Issue decision");
        fields.optional(SscsCaseData::getReservedToJudgeInterloc);
        fields.mandatory(SscsCaseData::getCreatedInGapsFrom)
                    .fieldShowCondition("bodyContent=\"doNotUse\"")
                    .retainHiddenValue();
        fields.optional(SscsCaseData::getDocumentSentToDwp)
                    .fieldShowCondition("createdInGapsFrom!=\"readyToList\"");
        fields.mandatory(SscsCaseData::getInterlocReviewState);
        fields.mandatory(SscsCaseData::getDecisionType);
        fields.complex(SscsCaseData::getDocumentGeneration)
                    .mandatory(DocumentGeneration::getGenerateNotice).done();
        fields.optional(SscsCaseData::getSscsInterlocDecisionDocument)
                    .fieldShowCondition("generateNotice=\"No\"");
        fields.complex(SscsCaseData::getDocumentGeneration)
                    .optional(DocumentGeneration::getBodyContent)
                    .fieldShowCondition("generateNotice=\"Yes\"")
                    .mandatory(DocumentGeneration::getSignedBy)
                    .fieldShowCondition("generateNotice=\"Yes\"")
                    .mandatory(DocumentGeneration::getSignedRole)
                    .fieldShowCondition("generateNotice=\"Yes\"").done();
        fields.complex(SscsCaseData::getDocumentStaging)
                    .optional(DocumentStaging::getDateAdded)
                    .fieldShowCondition("generateNotice=\"Yes\"").done();
    }
}
