package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code rip1Doc} of event {@code dwpSupplementaryResponse}.
 */
public final class DwpSupplementaryResponseRip1DocPage {
    private DwpSupplementaryResponseRip1DocPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("rip1Doc");
        fields.showCondition("showRip1DocPage=\"Yes\"");
        fields.mandatory(SscsCaseData::getIsRip1Doc);
        fields.optional(SscsCaseData::getRip1Doc)
                    .fieldShowCondition("isRip1Doc = \"Yes\"");
    }
}
