package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;
import uk.gov.hmcts.reform.sscs.ccd.domain.WorkAllocationFields;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code 1.0} of event {@code dwpSupplementaryResponse}.
 */
public final class DwpSupplementaryResponsePage10 {
    private DwpSupplementaryResponsePage10() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("1.0");
        fields.pageLabel("Language Preference Welsh");
        fields.readonly(SscsCaseData::getLanguagePreferenceWelsh)
                    .fieldShowCondition("[STATE]=\"doNotUse\"")
                    .retainHiddenValue();
        fields.complex(SscsCaseData::getWorkAllocationFields)
                    .readonly(WorkAllocationFields::getScannedDocumentTypes)
                    .fieldShowCondition("[STATE]=\"DoNotShow\"").done();
        fields.optional(SscsCaseData::getShowRip1DocPage)
                    .fieldShowCondition("dwpState=\"DoNotUse\"")
                    .retainHiddenValue();
        fields.mandatory(SscsCaseData::getDwpSupplementaryResponseDoc);
        fields.optional(SscsCaseData::getDwpOtherDoc);
        fields.optional(SscsCaseData::getDwpState);
        fields.mandatory(SscsCaseData::getDwpIsOfficerAttending);
    }
}
