package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.AudioVideoEvidence;
import uk.gov.hmcts.reform.sscs.ccd.domain.DwpResponseDocument;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;
import uk.gov.hmcts.reform.sscs.ccd.domain.WorkAllocationFields;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code 1.0} of event {@code dwpUploadResponse}.
 */
public final class DwpUploadResponsePage10 {
    private DwpUploadResponsePage10() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("1.0");
        fields.pageLabel("Document types uploaded");
        fields.complex(SscsCaseData::getWorkAllocationFields)
                    .readonly(WorkAllocationFields::getScannedDocumentTypes)
                    .fieldShowCondition("[STATE]=\"DoNotShow\"")
                    .readonly(WorkAllocationFields::getFtaResponseReviewRequired)
                    .fieldShowCondition("[STATE]=\"DoNotShow\"").done();
        fields.readonlyNoSummary(SscsCaseData::getAppeal)
                    .fieldShowCondition("dwpFurtherInfo=\"DoNotUse\"");
        fields.complex(SscsCaseData::getDwpResponseDocument)
                    .optional(DwpResponseDocument::getDwpResponseDocumentTitle)
                    .fieldShowCondition("appeal.benefitType.code!=\"infectedBloodCompensation\" AND appeal.benefitType.code!=\"guardiansAllowance\" AND appeal.benefitType.code!=\"childBenefit\" AND appeal.benefitType.code!=\"nationalInsuranceCredits\" AND appeal.benefitType.code!=\"guaranteedMinimumPension\" AND appeal.benefitType.code!=\"homeResponsibilitiesProtection\" AND appeal.benefitType.code!=\"taxCredit\" AND appeal.benefitType.code!=\"taxFreeChildcare\" AND appeal.benefitType.code!=\"thirtyHoursFreeChildcare\"")
                    .pageId("1.0")
                    .optional(DwpResponseDocument::getHmrcResponseDocumentTitle)
                    .fieldShowCondition("appeal.benefitType.code=\"guardiansAllowance\" OR appeal.benefitType.code=\"childBenefit\" OR appeal.benefitType.code=\"nationalInsuranceCredits\" OR appeal.benefitType.code=\"guaranteedMinimumPension\" OR appeal.benefitType.code=\"homeResponsibilitiesProtection\" OR appeal.benefitType.code=\"taxCredit\" OR appeal.benefitType.code=\"taxFreeChildcare\" OR appeal.benefitType.code=\"thirtyHoursFreeChildcare\"")
                    .pageId("1.0")
                    .optional(DwpResponseDocument::getIbcaResponseDocumentTitle)
                    .fieldShowCondition("appeal.benefitType.code=\"infectedBloodCompensation\"")
                    .pageId("1.0")
                    .mandatory(DwpResponseDocument::getDocumentFileName)
                    .pageId("1.0")
                    .mandatory(DwpResponseDocument::getDocumentLink)
                    .noHintText()
                    .pageId("1.0").done();
        fields.optional(SscsCaseData::getDwpAT38Document);
        fields.mandatory(SscsCaseData::getDwpEvidenceBundleDocument);
        fields.optional(SscsCaseData::getDwpEditedEvidenceReason);
        fields.complex(SscsCaseData::getDwpEditedResponseDocument)
                    .optional(DwpResponseDocument::getDwpResponseDocumentTitle)
                    .fieldShowCondition("(dwpEditedEvidenceReason=\"phme\" OR dwpEditedEvidenceReason=\"childSupportConfidentiality\") AND appeal.benefitType.code!=\"infectedBloodCompensation\" AND appeal.benefitType.code!=\"guardiansAllowance\" AND appeal.benefitType.code!=\"childBenefit\" AND appeal.benefitType.code!=\"nationalInsuranceCredits\" AND appeal.benefitType.code!=\"guaranteedMinimumPension\" AND appeal.benefitType.code!=\"homeResponsibilitiesProtection\" AND appeal.benefitType.code!=\"taxCredit\" AND appeal.benefitType.code!=\"taxFreeChildcare\" AND appeal.benefitType.code!=\"thirtyHoursFreeChildcare\"")
                    .pageId("1.0")
                    .optional(DwpResponseDocument::getHmrcResponseDocumentTitle)
                    .fieldShowCondition("(dwpEditedEvidenceReason=\"phme\" OR dwpEditedEvidenceReason=\"childSupportConfidentiality\") AND appeal.benefitType.code=\"guardiansAllowance\" OR appeal.benefitType.code=\"childBenefit\" OR appeal.benefitType.code=\"nationalInsuranceCredits\" OR appeal.benefitType.code=\"guaranteedMinimumPension\" OR appeal.benefitType.code=\"homeResponsibilitiesProtection\" OR appeal.benefitType.code=\"taxCredit\" OR appeal.benefitType.code=\"taxFreeChildcare\" OR appeal.benefitType.code=\"thirtyHoursFreeChildcare\"")
                    .pageId("1.0")
                    .optional(DwpResponseDocument::getIbcaResponseDocumentTitle)
                    .fieldShowCondition("(dwpEditedEvidenceReason=\"phme\" OR dwpEditedEvidenceReason=\"childSupportConfidentiality\") AND appeal.benefitType.code=\"infectedBloodCompensation\"")
                    .pageId("1.0")
                    .optional(DwpResponseDocument::getDocumentFileName)
                    .fieldShowCondition("dwpEditedEvidenceReason=\"phme\" OR dwpEditedEvidenceReason=\"childSupportConfidentiality\"")
                    .pageId("1.0")
                    .optional(DwpResponseDocument::getDocumentLink)
                    .fieldShowCondition("dwpEditedEvidenceReason=\"phme\" OR dwpEditedEvidenceReason=\"childSupportConfidentiality\"")
                    .noHintText()
                    .pageId("1.0").done()
                    .fieldShowCondition("dwpEditedEvidenceReason=\"phme\" OR dwpEditedEvidenceReason=\"childSupportConfidentiality\"");
        fields.optional(SscsCaseData::getDwpEditedEvidenceBundleDocument)
                    .fieldShowCondition("dwpEditedEvidenceReason=\"phme\" OR dwpEditedEvidenceReason=\"childSupportConfidentiality\"");
        fields.optional(SscsCaseData::getAppendix12Doc)
                    .fieldShowCondition("dwpEditedEvidenceReason=\"phme\" OR dwpEditedEvidenceReason=\"childSupportConfidentiality\"");
        fields.complex(SscsCaseData::getDwpUploadAudioVideoEvidence).done();
        fields.complex(SscsCaseData::getDwpUploadAudioVideoEvidence, AudioVideoEvidence.class)
                    .optional(AudioVideoEvidence::getDocumentLink)
                    .optional(AudioVideoEvidence::getRip1Document)
                    .noHintText().done();
        fields.mandatory(SscsCaseData::getBenefitCode)
                    .fieldShowCondition("appeal.benefitType.code!=\"UC\" AND appeal.benefitType.code!=\"infectedBloodCompensation\"");
        fields.mandatory(SscsCaseData::getBenefitCodeIbcaOnly)
                    .fieldShowCondition("appeal.benefitType.code=\"infectedBloodCompensation\"");
        fields.mandatory(SscsCaseData::getIssueCode)
                    .fieldShowCondition("appeal.benefitType.code!=\"UC\" AND appeal.benefitType.code!=\"infectedBloodCompensation\"");
        fields.mandatory(SscsCaseData::getIssueCodeIbcaOnly)
                    .fieldShowCondition("appeal.benefitType.code=\"infectedBloodCompensation\"");
        fields.mandatory(SscsCaseData::getDwpFurtherInfo)
                    .fieldShowCondition("appeal.benefitType.code!=\"industrialInjuriesDisablement\"");
        fields.optional(SscsCaseData::getDwpUcb);
        fields.mandatory(SscsCaseData::getDwpUcbEvidenceDocument)
                    .fieldShowCondition("dwpUCB=\"Yes\"");
        fields.optional(SscsCaseData::getDwpFurtherEvidenceStates)
                    .fieldShowCondition("appeal.benefitType.code!=\"UC\"");
        fields.mandatory(SscsCaseData::getDynamicDwpState)
                    .fieldShowCondition("appeal.benefitType.code!=\"UC\"");
        fields.mandatory(SscsCaseData::getDwpIsOfficerAttending);
    }
}
