package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.JointParty;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code jointPartyAddress} of event {@code dwpUploadResponse}.
 */
public final class DwpUploadResponseJointPartyAddressPage {
    private DwpUploadResponseJointPartyAddressPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("jointPartyAddress");
        fields.pageLabel("Joint party address");
        fields.showCondition("appeal.benefitType.code=\"UC\" AND jointParty=\"Yes\"");
        fields.complex(SscsCaseData::getJointParty)
                    .mandatory(JointParty::getJointPartyAddressSameAsAppellant)
                    .optional(JointParty::getAddress)
                    .fieldShowCondition("jointPartyAddressSameAsAppellant=\"No\"").done();
    }
}
