package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.AudioVideoEvidenceDetails;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;
import uk.gov.hmcts.reform.sscs.ccd.domain.WorkAllocationFields;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code 1.0} of event {@code dwpUploadResponse}.
 */
public final class DwpUploadResponsePage10 {
    private DwpUploadResponsePage10() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("1.0");
        fields.pageLabel("Document types uploaded");
        fields.complex(SscsCaseData::getWorkAllocationFields)
                    .readonly(WorkAllocationFields::getScannedDocumentTypes)
                    .fieldShowCondition("[STATE]=\"DoNotShow\"")
                    .readonly(WorkAllocationFields::getFtaResponseReviewRequired)
                    .fieldShowCondition("[STATE]=\"DoNotShow\"").done();
        fields.readonlyNoSummary(SscsCaseData::getAppeal)
                    .fieldShowCondition("dwpFurtherInfo=\"DoNotUse\"");
        fields.complex(SscsCaseData::getDwpResponseDocument).done();
        fields.optional(SscsCaseData::getDwpAT38Document);
        fields.mandatory(SscsCaseData::getDwpEvidenceBundleDocument);
        fields.optional(SscsCaseData::getDwpEditedEvidenceReason);
        fields.complex(SscsCaseData::getDwpEditedResponseDocument).done()
                    .fieldShowCondition("dwpEditedEvidenceReason=\"phme\" OR dwpEditedEvidenceReason=\"childSupportConfidentiality\"");
        fields.optional(SscsCaseData::getDwpEditedEvidenceBundleDocument)
                    .fieldShowCondition("dwpEditedEvidenceReason=\"phme\" OR dwpEditedEvidenceReason=\"childSupportConfidentiality\"");
        fields.optional(SscsCaseData::getAppendix12Doc)
                    .fieldShowCondition("dwpEditedEvidenceReason=\"phme\" OR dwpEditedEvidenceReason=\"childSupportConfidentiality\"");
        fields.complex(SscsCaseData::getDwpUploadAudioVideoEvidence).done();
        fields.complex(SscsCaseData::getDwpUploadAudioVideoEvidence, AudioVideoEvidenceDetails.class)
                    .optional(AudioVideoEvidenceDetails::getDocumentLink)
                    .optional(AudioVideoEvidenceDetails::getRip1Document).done();
        fields.mandatory(SscsCaseData::getBenefitCode)
                    .fieldShowCondition("appeal.benefitType.code!=\"UC\" AND appeal.benefitType.code!=\"infectedBloodCompensation\"");
        fields.mandatory(SscsCaseData::getBenefitCodeIbcaOnly)
                    .fieldShowCondition("appeal.benefitType.code=\"infectedBloodCompensation\"");
        fields.mandatory(SscsCaseData::getIssueCode)
                    .fieldShowCondition("appeal.benefitType.code!=\"UC\" AND appeal.benefitType.code!=\"infectedBloodCompensation\"");
        fields.mandatory(SscsCaseData::getIssueCodeIbcaOnly)
                    .fieldShowCondition("appeal.benefitType.code=\"infectedBloodCompensation\"");
        fields.mandatory(SscsCaseData::getDwpFurtherInfo)
                    .fieldShowCondition("appeal.benefitType.code!=\"industrialInjuriesDisablement\"");
        fields.optional(SscsCaseData::getDwpUcb);
        fields.mandatory(SscsCaseData::getDwpUcbEvidenceDocument)
                    .fieldShowCondition("dwpUCB=\"Yes\"");
        fields.optional(SscsCaseData::getDwpFurtherEvidenceStates)
                    .fieldShowCondition("appeal.benefitType.code!=\"UC\"");
        fields.mandatory(SscsCaseData::getDynamicDwpState)
                    .fieldShowCondition("appeal.benefitType.code!=\"UC\"");
        fields.mandatory(SscsCaseData::getDwpIsOfficerAttending);
    }
}
