package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.ElementDisputedDetails;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code elementsDisputedId} of event {@code dwpUploadResponse}.
 */
public final class DwpUploadResponseElementsDisputedIdPage {
    private DwpUploadResponseElementsDisputedIdPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("elementsDisputedId");
        fields.pageLabel("Issue codes");
        fields.showCondition("appeal.benefitType.code=\"UC\"");
        fields.complex(SscsCaseData::getElementsDisputedGeneral).done()
                    .fieldShowCondition("elementsDisputedList CONTAINS \"general\"");
        fields.complex(SscsCaseData::getElementsDisputedGeneral, ElementDisputedDetails.class)
                    .mandatory(ElementDisputedDetails::getIssueCode)
                    .pageId("elementsDisputedId").done();
        fields.complex(SscsCaseData::getElementsDisputedSanctions).done()
                    .fieldShowCondition("elementsDisputedList CONTAINS \"standardAllowanceSanctions\"");
        fields.complex(SscsCaseData::getElementsDisputedSanctions, ElementDisputedDetails.class)
                    .mandatory(ElementDisputedDetails::getIssueCode)
                    .pageId("elementsDisputedId").done();
        fields.complex(SscsCaseData::getElementsDisputedHousing).done()
                    .fieldShowCondition("elementsDisputedList CONTAINS \"housing\"");
        fields.complex(SscsCaseData::getElementsDisputedHousing, ElementDisputedDetails.class)
                    .mandatory(ElementDisputedDetails::getIssueCode)
                    .pageId("elementsDisputedId").done();
        fields.complex(SscsCaseData::getElementsDisputedChildCare).done()
                    .fieldShowCondition("elementsDisputedList CONTAINS \"childcare\"");
        fields.complex(SscsCaseData::getElementsDisputedChildCare, ElementDisputedDetails.class)
                    .mandatory(ElementDisputedDetails::getIssueCode)
                    .pageId("elementsDisputedId").done();
        fields.complex(SscsCaseData::getElementsDisputedCare).done()
                    .fieldShowCondition("elementsDisputedList CONTAINS \"carerElement\"");
        fields.complex(SscsCaseData::getElementsDisputedCare, ElementDisputedDetails.class)
                    .mandatory(ElementDisputedDetails::getIssueCode)
                    .pageId("elementsDisputedId").done();
        fields.complex(SscsCaseData::getElementsDisputedChildElement).done()
                    .fieldShowCondition("elementsDisputedList CONTAINS \"childElement\"");
        fields.complex(SscsCaseData::getElementsDisputedChildElement, ElementDisputedDetails.class)
                    .mandatory(ElementDisputedDetails::getIssueCode)
                    .pageId("elementsDisputedId").done();
        fields.complex(SscsCaseData::getElementsDisputedChildDisabled).done()
                    .fieldShowCondition("elementsDisputedList CONTAINS \"disabledChildren\"");
        fields.complex(SscsCaseData::getElementsDisputedChildDisabled, ElementDisputedDetails.class)
                    .mandatory(ElementDisputedDetails::getIssueCode)
                    .pageId("elementsDisputedId").done();
        fields.complex(SscsCaseData::getElementsDisputedLimitedWork).done()
                    .fieldShowCondition("elementsDisputedList CONTAINS \"limitedCapabilityWork\"");
        fields.complex(SscsCaseData::getElementsDisputedLimitedWork, ElementDisputedDetails.class)
                    .mandatory(ElementDisputedDetails::getIssueCode)
                    .pageId("elementsDisputedId").done();
    }
}
