package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.Adjournment;
import uk.gov.hmcts.reform.sscs.ccd.domain.FtaCommunicationFields;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code replyToFtaQuery} of event {@code ftaCommunication}.
 */
public final class FtaCommunicationReplyToFtaQueryPage {
    private FtaCommunicationReplyToFtaQueryPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("replyToFtaQuery");
        fields.pageLabel("Write a reply to FTA Query");
        fields.showCondition("ftaRequestType=\"replyToFtaQuery\"");
        fields.complex(SscsCaseData::getCommunicationFields)
                    .readonly(FtaCommunicationFields::getFtaRequestNoResponseQuery)
                    .optional(FtaCommunicationFields::getCommRequestResponseTextArea).done();
        fields.complex(SscsCaseData::getAdjournment)
                    .readonly(Adjournment::getCommunicationNoActionLabel).done();
        fields.complex(SscsCaseData::getCommunicationFields)
                    .optional(FtaCommunicationFields::getCommRequestResponseNoAction).done();
    }
}
