package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.Adjournment;
import uk.gov.hmcts.reform.sscs.ccd.domain.DwpResponseDocument;
import uk.gov.hmcts.reform.sscs.ccd.domain.ExtendedSscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsIndustrialInjuriesData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code 1.0} of event {@code hmctsResponseReviewed}.
 */
public final class HmctsResponseReviewedPage10 {
    private HmctsResponseReviewedPage10() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("1.0");
        fields.pageLabel("Hmcts review response");
        fields.readonlyNoSummary(SscsCaseData::getAppeal)
                    .fieldShowCondition("issueCode=\"doNotUse\"");
        fields.readonly(SscsCaseData::getCreatedInGapsFrom)
                    .fieldShowCondition("issueCode=\"doNotUse\"");
        fields.complex(SscsCaseData::getDwpResponseDocument)
                    .optional(DwpResponseDocument::getDwpResponseDocumentTitle)
                    .fieldShowCondition("appeal.benefitType.code!=\"infectedBloodCompensation\" AND appeal.benefitType.code!=\"guardiansAllowance\" AND appeal.benefitType.code!=\"childBenefit\" AND appeal.benefitType.code!=\"nationalInsuranceCredits\" AND appeal.benefitType.code!=\"guaranteedMinimumPension\" AND appeal.benefitType.code!=\"homeResponsibilitiesProtection\" AND appeal.benefitType.code!=\"taxCredit\" AND appeal.benefitType.code!=\"taxFreeChildcare\" AND appeal.benefitType.code!=\"thirtyHoursFreeChildcare\"")
                    .pageId("1.0")
                    .optional(DwpResponseDocument::getHmrcResponseDocumentTitle)
                    .fieldShowCondition("appeal.benefitType.code=\"guardiansAllowance\" OR appeal.benefitType.code=\"childBenefit\" OR appeal.benefitType.code=\"nationalInsuranceCredits\" OR appeal.benefitType.code=\"guaranteedMinimumPension\" OR appeal.benefitType.code=\"homeResponsibilitiesProtection\" OR appeal.benefitType.code=\"taxCredit\" OR appeal.benefitType.code=\"taxFreeChildcare\" OR appeal.benefitType.code=\"thirtyHoursFreeChildcare\"")
                    .pageId("1.0")
                    .optional(DwpResponseDocument::getIbcaResponseDocumentTitle)
                    .fieldShowCondition("appeal.benefitType.code=\"infectedBloodCompensation\"")
                    .pageId("1.0")
                    .readonly(DwpResponseDocument::getDocumentFileName)
                    .pageId("1.0")
                    .readonly(DwpResponseDocument::getDocumentLink)
                    .noHintText()
                    .pageId("1.0").done();
        fields.readonly(SscsCaseData::getDwpAT38Document);
        fields.readonly(SscsCaseData::getDwpEvidenceBundleDocument);
        fields.optional(SscsCaseData::getDwpEditedEvidenceReason)
                    .fieldShowCondition("dwpEvidenceBundleDocument=\"DONOTSSHOW\"")
                    .retainHiddenValue();
        fields.complex(SscsCaseData::getAdjournment)
                    .readonly(Adjournment::getDwpEditedEvidenceReasonLabel)
                    .fieldShowCondition("dwpEditedEvidenceReason!=\"\"").done();
        fields.complex(SscsCaseData::getDwpEditedResponseDocument)
                    .optional(DwpResponseDocument::getDwpResponseDocumentTitle)
                    .fieldShowCondition("dwpEditedEvidenceReason!=\"\" AND appeal.benefitType.code!=\"infectedBloodCompensation\" AND appeal.benefitType.code!=\"guardiansAllowance\" AND appeal.benefitType.code!=\"childBenefit\" AND appeal.benefitType.code!=\"nationalInsuranceCredits\" AND appeal.benefitType.code!=\"guaranteedMinimumPension\" AND appeal.benefitType.code!=\"homeResponsibilitiesProtection\" AND appeal.benefitType.code!=\"taxCredit\" AND appeal.benefitType.code!=\"taxFreeChildcare\" AND appeal.benefitType.code!=\"thirtyHoursFreeChildcare\"")
                    .pageId("1.0")
                    .optional(DwpResponseDocument::getHmrcResponseDocumentTitle)
                    .fieldShowCondition("dwpEditedEvidenceReason!=\"\" AND appeal.benefitType.code=\"guardiansAllowance\" OR appeal.benefitType.code=\"childBenefit\" OR appeal.benefitType.code=\"nationalInsuranceCredits\" OR appeal.benefitType.code=\"guaranteedMinimumPension\" OR appeal.benefitType.code=\"homeResponsibilitiesProtection\" OR appeal.benefitType.code=\"taxCredit\" OR appeal.benefitType.code=\"taxFreeChildcare\" OR appeal.benefitType.code=\"thirtyHoursFreeChildcare\"")
                    .pageId("1.0")
                    .optional(DwpResponseDocument::getIbcaResponseDocumentTitle)
                    .fieldShowCondition("dwpEditedEvidenceReason!=\"\" AND appeal.benefitType.code=\"infectedBloodCompensation\"")
                    .pageId("1.0")
                    .readonly(DwpResponseDocument::getDocumentFileName)
                    .fieldShowCondition("dwpEditedEvidenceReason!=\"\"")
                    .pageId("1.0")
                    .readonly(DwpResponseDocument::getDocumentLink)
                    .fieldShowCondition("dwpEditedEvidenceReason!=\"\"")
                    .noHintText()
                    .pageId("1.0").done()
                    .fieldShowCondition("dwpEditedEvidenceReason!=\"\"");
        fields.readonly(SscsCaseData::getDwpEditedEvidenceBundleDocument)
                    .fieldShowCondition("dwpEditedEvidenceReason!=\"\"");
        fields.readonly(SscsCaseData::getAppendix12Doc)
                    .fieldShowCondition("dwpEditedEvidenceReason!=\"\"");
        fields.readonly(SscsCaseData::getDwpUcb);
        fields.readonly(SscsCaseData::getDwpUcbEvidenceDocument)
                    .fieldShowCondition("dwpUCB=\"Yes\"");
        fields.mandatory(SscsCaseData::getBenefitCode)
                    .fieldShowCondition("appeal.benefitType.code!=\"infectedBloodCompensation\" AND appeal.benefitType.code!=\"UC\" OR createdInGapsFrom!=\"readyToList\"");
        fields.mandatory(SscsCaseData::getBenefitCodeIbcaOnly)
                    .fieldShowCondition("appeal.benefitType.code=\"infectedBloodCompensation\"");
        fields.mandatory(SscsCaseData::getIssueCode)
                    .fieldShowCondition("appeal.benefitType.code!=\"infectedBloodCompensation\" AND appeal.benefitType.code!=\"UC\" OR createdInGapsFrom!=\"readyToList\"");
        fields.mandatory(SscsCaseData::getIssueCodeIbcaOnly)
                    .fieldShowCondition("appeal.benefitType.code=\"infectedBloodCompensation\"");
        fields.mandatory(SscsCaseData::getDwpOriginatingOffice)
                    .fieldShowCondition("appeal.benefitType.code!=\"UC\" OR createdInGapsFrom!=\"readyToList\"");
        fields.mandatory(SscsCaseData::getDwpPresentingOffice)
                    .fieldShowCondition("appeal.benefitType.code!=\"UC\" OR createdInGapsFrom!=\"readyToList\"");
        fields.mandatory(SscsCaseData::getDwpIsOfficerAttending);
        fields.mandatory(SscsCaseData::getDwpResponseDate);
        fields.mandatory(SscsCaseData::getIsInterlocRequired);
        fields.mandatory(SscsCaseData::getSelectWhoReviewsCase)
                    .fieldShowCondition("isInterlocRequired=\"Yes\"")
                    .publishAs("action");
        fields.mandatory(SscsCaseData::getInterlocReferralReason)
                    .fieldShowCondition("isInterlocRequired=\"Yes\"")
                    .retainHiddenValue();
        fields.optional(SscsCaseData::getTempNoteDetail)
                    .fieldShowCondition("isInterlocRequired=\"Yes\"")
                    .caseEventFieldLabel("Reason referred to interloc - extra information");
        fields.complex(SscsCaseData::getSscsIndustrialInjuriesData)
                    .optional(SscsIndustrialInjuriesData::getPanelDoctorSpecialism)
                    .fieldShowCondition("appeal.benefitType.code=\"industrialInjuriesDisablement\" OR appeal.benefitType.code=\"industrialDeathBenefit\"")
                    .optional(SscsIndustrialInjuriesData::getSecondPanelDoctorSpecialism)
                    .fieldShowCondition("appeal.benefitType.code=\"industrialInjuriesDisablement\" OR appeal.benefitType.code=\"industrialDeathBenefit\"").done();
        fields.complex(SscsCaseData::getExtendedSscsCaseData)
                    .mandatory(ExtendedSscsCaseData::getSelectedConfidentialityParty)
                    .fieldShowCondition("isInterlocRequired=\"Yes\" AND interlocReferralReason=\"confidentiality\" AND (appeal.benefitType.code=\"childSupport\" OR appeal.benefitType.code=\"UC\")")
                    .caseEventFieldLabel("Select Party")
                    .retainHiddenValue().done();
    }
}
