package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code linkedAppealRef} of event {@code hmctsResponseReviewed}.
 */
public final class HmctsResponseReviewedLinkedAppealRefPage {
    private HmctsResponseReviewedLinkedAppealRefPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("linkedAppealRef");
        fields.pageLabel("Linked appeal reference");
        fields.showCondition("appeal.benefitType.code=\"UC\" AND elementsDisputedIsDecisionDisputedByOthers=\"Yes\"");
        fields.mandatoryNoSummary(SscsCaseData::getElementsDisputedIsDecisionDisputedByOthers)
                    .fieldShowCondition("elementsDisputedList=\"DoNotUse\"")
                    .retainHiddenValue();
        fields.readonlyNoSummary(SscsCaseData::getElementsDisputedLinkedAppealRef);
    }
}
