package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Field placements for page {@code 1.0} of event {@code incompleteApplicationReceived} (part 2 of 2).
 */
public final class IncompleteApplicationReceivedPage10Fields2 {
    private IncompleteApplicationReceivedPage10Fields2() {
    }

    /**
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.optional(SscsCaseData::getCaseCreated);
        fields.optional(SscsCaseData::getCaseReference)
                    .fieldShowCondition("appeal.benefitType.descriptionSelection!=\"093\"");
        fields.optional(SscsCaseData::getRegion);
        fields.optional(SscsCaseData::getIsScottishCase);
    }
}
