package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code 1.0} of event {@code issueGenericLetter}.
 */
public final class IssueGenericLetterPage10 {
    private IssueGenericLetterPage10() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("1.0");
        fields.pageLabel("Issue generic letter");
        fields.mandatoryNoSummary(SscsCaseData::getSendToAllParties);
        fields.readonlyNoSummary(SscsCaseData::getHasJointParty)
                    .fieldShowCondition("sendToAllParties=\"DUMMY_VALUE_TO_HIDE_FIELD\"");
        fields.readonlyNoSummary(SscsCaseData::getHasOtherParties)
                    .fieldShowCondition("sendToAllParties=\"DUMMY_VALUE_TO_HIDE_FIELD\"");
        fields.readonlyNoSummary(SscsCaseData::getHasRepresentative)
                    .fieldShowCondition("sendToAllParties=\"DUMMY_VALUE_TO_HIDE_FIELD\"");
        fields.mandatoryNoSummary(SscsCaseData::getSendToApellant)
                    .fieldShowCondition("sendToAllParties = \"No\"");
        fields.mandatoryNoSummary(SscsCaseData::getSendToRepresentative)
                    .fieldShowCondition("sendToAllParties = \"No\" AND hasRepresentative = \"Yes\"");
        fields.mandatoryNoSummary(SscsCaseData::getSendToJointParty)
                    .fieldShowCondition("sendToAllParties = \"No\" AND hasJointParty = \"Yes\"");
        fields.mandatoryNoSummary(SscsCaseData::getSendToOtherParties)
                    .fieldShowCondition("sendToAllParties = \"No\" AND hasOtherParties = \"Yes\"");
        fields.mandatory(SscsCaseData::getOtherPartySelection)
                    .fieldShowCondition("sendToAllParties = \"No\" AND sendToOtherParties = \"Yes\"");
    }
}
