package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.DocumentGeneration;
import uk.gov.hmcts.reform.sscs.ccd.domain.PostHearing;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code Permission_To_Appeal} of event {@code postHearingRequest}.
 */
public final class PostHearingRequestPermissionToAppealPage {
    private PostHearingRequestPermissionToAppealPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("Permission_To_Appeal");
        fields.pageLabel("Permission to Appeal");
        fields.showCondition("postHearingRequestType=\"permissionToAppeal\"");
        fields.complex(SscsCaseData::getPostHearing)
                    .optional(PostHearing::getPermissionToAppeal).done();
        fields.complex(SscsCaseData::getDocumentGeneration)
                    .mandatory(DocumentGeneration::getPermissionToAppealBodyContent)
                    .fieldShowCondition("permissionToAppeal.requestFormat = \"generate\"")
                    .caseEventFieldLabel("Reason for Permission to Appeal").done();
    }
}
