package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.DocumentGeneration;
import uk.gov.hmcts.reform.sscs.ccd.domain.PostHearing;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code Statement_Of_Reasons} of event {@code postHearingReview}.
 */
public final class PostHearingReviewStatementOfReasonsPage {
    private PostHearingReviewStatementOfReasonsPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("Statement_Of_Reasons");
        fields.pageLabel("Statement of Reasons");
        fields.showCondition("postHearingReviewType=\"statementOfReasons\"");
        fields.complex(SscsCaseData::getPostHearing)
                    .optional(PostHearing::getStatementOfReasons).done();
        fields.complex(SscsCaseData::getDocumentGeneration)
                    .mandatory(DocumentGeneration::getStatementOfReasonsGenerateNotice)
                    .fieldShowCondition("statementOfReasons.action = \"*\"")
                    .mandatory(DocumentGeneration::getStatementOfReasonsBodyContent)
                    .fieldShowCondition("statementOfReasons.action = \"*\" AND statementOfReasonsGenerateNotice = \"Yes\"")
                    .mandatory(DocumentGeneration::getStatementOfReasonsSignedBy)
                    .fieldShowCondition("statementOfReasons.action = \"*\" AND statementOfReasonsGenerateNotice = \"Yes\"")
                    .mandatory(DocumentGeneration::getStatementOfReasonsSignedRole)
                    .fieldShowCondition("statementOfReasons.action = \"*\" AND statementOfReasonsGenerateNotice = \"Yes\"").done();
    }
}
