package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.DocumentGeneration;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code Write_Statement_Of_Reasons} of event {@code sORWrite}.
 */
public final class SORWriteWriteStatementOfReasonsPage {
    private SORWriteWriteStatementOfReasonsPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("Write_Statement_Of_Reasons");
        fields.pageLabel("Write Statement of Reasons");
        fields.complex(SscsCaseData::getDocumentGeneration)
                    .mandatory(DocumentGeneration::getGenerateNotice)
                    .caseEventFieldLabel("Generate statement of reasons?")
                    .mandatory(DocumentGeneration::getBodyContent)
                    .fieldShowCondition("generateNotice = \"Yes\"")
                    .caseEventFieldLabel("Body Content")
                    .mandatory(DocumentGeneration::getSignedBy)
                    .fieldShowCondition("generateNotice = \"Yes\"")
                    .mandatory(DocumentGeneration::getSignedRole)
                    .fieldShowCondition("generateNotice = \"Yes\"").done();
    }
}
