package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code systemFlags} of event {@code superUserFullEdit}.
 */
public final class SuperUserFullEditSystemFlagsPage {
    private SuperUserFullEditSystemFlagsPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("systemFlags");
        fields.pageLabel("System Flags");
        fields.optional(SscsCaseData::getCreatedInGapsFrom);
        fields.optional(SscsCaseData::getIsProgressingViaGaps);
        fields.optional(SscsCaseData::getHmctsDwpState);
        fields.optional(SscsCaseData::getInterlocReviewState);
        fields.optional(SscsCaseData::getDirectionResponse);
    }
}
