package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code confidentialityAndAdjustments} of event {@code superUserFullEdit}.
 */
public final class SuperUserFullEditConfidentialityAndAdjustmentsPage {
    private SuperUserFullEditConfidentialityAndAdjustmentsPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("confidentialityAndAdjustments");
        fields.pageLabel("Confidentiality & Adjustments");
        fields.optional(SscsCaseData::getIsConfidentialCase);
        fields.optional(SscsCaseData::getConfidentialityType);
        fields.optional(SscsCaseData::getReasonableAdjustmentChoice);
        fields.optional(SscsCaseData::getReasonableAdjustments);
        fields.optional(SscsCaseData::getLanguagePreferenceWelsh);
    }
}
