package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.FtaCommunicationFields;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code 2.0} of event {@code tribunalCommunication}.
 */
public final class TribunalCommunicationPage20 {
    private TribunalCommunicationPage20() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("2.0");
        fields.pageLabel("Send a Communication Request to the Tribunal");
        fields.showCondition("tribunalRequestType=\"newRequest\"");
        fields.complex(SscsCaseData::getCommunicationFields)
                    .mandatory(FtaCommunicationFields::getCommRequestTopic)
                    .mandatory(FtaCommunicationFields::getCommRequestQuestion).done();
    }
}
