package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.PanelMemberComposition;
import uk.gov.hmcts.reform.sscs.ccd.domain.SchedulingAndListingFields;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code 1.0} of event {@code updateListingRequirements}.
 */
public final class UpdateListingRequirementsPage10 {
    private UpdateListingRequirementsPage10() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("1.0");
        fields.pageLabel("Select Override Values");
        fields.complex(SscsCaseData::getPanelMemberComposition)
                    .optional(PanelMemberComposition::getPanelCompositionJudge)
                    .fieldShowCondition("reserveTo.reservedDistrictTribunalJudge != \"Yes\"")
                    .pageId("1.0")
                    .optional(PanelMemberComposition::getDistrictTribunalJudge)
                    .fieldShowCondition("panelMemberComposition.districtTribunalJudge = \"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .pageId("1.0")
                    .optional(PanelMemberComposition::getPanelCompositionMemberMedical1)
                    .pageId("1.0")
                    .optional(PanelMemberComposition::getPanelCompositionMemberMedical2)
                    .fieldShowCondition("panelMemberComposition.panelCompositionMemberMedical2 = \"DUMMY_VALUE_TO_HIDE_FIELD\"")
                    .pageId("1.0")
                    .optional(PanelMemberComposition::getPanelCompositionDisabilityAndFqMember)
                    .pageId("1.0").done();
        fields.complex(SscsCaseData::getSchedulingAndListingFields)
                    .readonly(SchedulingAndListingFields::getHearingRoute)
                    .fieldShowCondition("overrideFields=\"DoNotShow\"")
                    .optional(SchedulingAndListingFields::getOverrideFields)
                    .optional(SchedulingAndListingFields::getReserveTo)
                    .optional(SchedulingAndListingFields::getPanelMemberExclusions).done();
        fields.optional(SscsCaseData::getTribunalDirectPoToAttend)
                    .fieldShowCondition("hearingRoute=\"listAssist\"");
    }
}
