package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code updateNotListableInterlocReview} of event {@code updateNotListable}.
 */
public final class UpdateNotListableUpdateNotListableInterlocReviewPage {
    private UpdateNotListableUpdateNotListableInterlocReviewPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("updateNotListableInterlocReview");
        fields.pageLabel("Interlocutory review");
        fields.showCondition("updateNotListableDirectionsFulfilled=\"No\"");
        fields.optionalNoSummary(SscsCaseData::getInterlocReviewState)
                    .fieldShowCondition("[STATE]=\"doNotUse\"")
                    .publishAs("action");
        fields.mandatory(SscsCaseData::getUpdateNotListableInterlocReview);
        fields.mandatory(SscsCaseData::getUpdateNotListableWhoReviewsCase)
                    .fieldShowCondition("updateNotListableInterlocReview=\"Yes\"");
    }
}
