package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.InternalCaseDocumentData;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsDocument;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code moveDocuments} of event {@code uploadDocument}.
 */
public final class UploadDocumentMoveDocumentsPage {
    private UploadDocumentMoveDocumentsPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("moveDocuments");
        fields.complex(SscsCaseData::getSscsDocument).done()
                    .fieldShowCondition("uploadRemoveOrMoveDocument=\"uploadRemove\" AND uploadRemoveDocumentType=\"document\"")
                    .retainHiddenValue();
        fields.complex(SscsCaseData::getSscsDocument, SscsDocument.class)
                    .optional(SscsDocument::getDocumentType)
                    .pageId("moveDocuments")
                    .optional(SscsDocument::getDocumentEmailContent)
                    .pageId("moveDocuments")
                    .optional(SscsDocument::getDocumentLink)
                    .pageId("moveDocuments")
                    .optional(SscsDocument::getEditedDocumentLink)
                    .pageId("moveDocuments")
                    .optional(SscsDocument::getDocumentDateAdded)
                    .pageId("moveDocuments")
                    .optional(SscsDocument::getDocumentFileName)
                    .pageId("moveDocuments")
                    .optional(SscsDocument::getControlNumber)
                    .pageId("moveDocuments")
                    .optional(SscsDocument::getDocumentComment)
                    .pageId("moveDocuments")
                    .optional(SscsDocument::getEvidenceIssued)
                    .pageId("moveDocuments")
                    .optional(SscsDocument::getBundleAddition)
                    .pageId("moveDocuments")
                    .optional(SscsDocument::getDocumentTranslationStatus)
                    .pageId("moveDocuments")
                    .optional(SscsDocument::getResizedDocumentLink)
                    .pageId("moveDocuments")
                    .optional(SscsDocument::getDateApproved)
                    .pageId("moveDocuments")
                    .optional(SscsDocument::getPartyUploaded)
                    .pageId("moveDocuments")
                    .optional(SscsDocument::getOriginalPartySender)
                    .pageId("moveDocuments")
                    .optional(SscsDocument::getAvDocumentLink)
                    .pageId("moveDocuments")
                    .readonly(SscsDocument::getOriginalSenderOtherPartyId)
                    .pageId("moveDocuments")
                    .optional(SscsDocument::getOriginalSenderOtherPartyName)
                    .pageId("moveDocuments").done();
        fields.complex(SscsCaseData::getInternalCaseDocumentData)
                    .optional(InternalCaseDocumentData::getSscsInternalDocument)
                    .fieldShowCondition("uploadRemoveOrMoveDocument=\"uploadRemove\" AND uploadRemoveDocumentType=\"internalDocument\"")
                    .retainHiddenValue()
                    .optional(InternalCaseDocumentData::getMoveDocumentToInternalDocumentsTabDL)
                    .fieldShowCondition("uploadRemoveOrMoveDocument=\"move\" AND moveDocumentTo=\"internalDocument\"")
                    .retainHiddenValue()
                    .optional(InternalCaseDocumentData::getMoveDocumentToDocumentsTabDL)
                    .fieldShowCondition("uploadRemoveOrMoveDocument=\"move\" AND moveDocumentTo=\"document\"")
                    .retainHiddenValue()
                    .mandatory(InternalCaseDocumentData::getShouldBeIssued)
                    .fieldShowCondition("uploadRemoveOrMoveDocument=\"move\" AND moveDocumentTo=\"document\"").done();
    }
}
