package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsUcCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code schedule7Activities} of event {@code writeFinalDecision}.
 */
public final class WriteFinalDecisionSchedule7ActivitiesPage {
    private WriteFinalDecisionSchedule7ActivitiesPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("schedule7Activities");
        fields.pageLabel("Schedule 7 activities");
        fields.showCondition("showSchedule7ActivitiesPage=\"Yes\" AND wcaAppeal = \"Yes\" AND writeFinalDecisionSevereYesNo != \"Yes\"");
        fields.complex(SscsCaseData::getSscsUcCaseData)
                    .mandatory(SscsUcCaseData::getShowSchedule7ActivitiesPage)
                    .fieldShowCondition("appeal.benefitType.code=\"DoNotShow\"")
                    .retainHiddenValue()
                    .mandatory(SscsUcCaseData::getUcWriteFinalDecisionSchedule7ActivitiesApply)
                    .mandatory(SscsUcCaseData::getUcWriteFinalDecisionSchedule7ActivitiesQuestion)
                    .fieldShowCondition("ucWriteFinalDecisionSchedule7ActivitiesApply != \"No\"")
                    .retainHiddenValue()
                    .mandatory(SscsUcCaseData::getDoesSchedule9Paragraph4Apply)
                    .fieldShowCondition("ucWriteFinalDecisionSchedule7ActivitiesApply = \"No\"")
                    .retainHiddenValue().done();
    }
}
