package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code allowedOrRefused} of event {@code writeFinalDecision}.
 */
public final class WriteFinalDecisionAllowedOrRefusedPage {
    private WriteFinalDecisionAllowedOrRefusedPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("allowedOrRefused");
        fields.pageLabel("Allowed or refused");
        fields.showCondition("writeFinalDecisionIsDescriptorFlow != \"Yes\" OR writeFinalDecisionGenerateNotice != \"Yes\"");
    }
}
