package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsUcCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code schedule8Paragraph4} of event {@code writeFinalDecision}.
 */
public final class WriteFinalDecisionSchedule8Paragraph4Page {
    private WriteFinalDecisionSchedule8Paragraph4Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("schedule8Paragraph4");
        fields.pageLabel("Schedule 8 Paragraph 4");
        fields.showCondition("appeal.benefitType.code=\"UC\" AND wcaAppeal = \"Yes\" AND showSchedule8Paragraph4Page=\"Yes\" AND writeFinalDecisionSevereYesNo != \"Yes\"");
        fields.complex(SscsCaseData::getSscsUcCaseData)
                    .mandatory(SscsUcCaseData::getShowSchedule8Paragraph4Page)
                    .fieldShowCondition("appeal.benefitType.code=\"DoNotShow\"")
                    .retainHiddenValue()
                    .mandatory(SscsUcCaseData::getDoesSchedule8Paragraph4Apply).done();
    }
}
