package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.ExtendedSscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code esaSevereCriteria} of event {@code writeFinalDecision}.
 */
public final class WriteFinalDecisionEsaSevereCriteriaPage {
    private WriteFinalDecisionEsaSevereCriteriaPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("esaSevereCriteria");
        fields.pageLabel("Severe Conditions Criteria");
        fields.showCondition("(showSchedule3ActivitiesPage = \"Yes\" AND esaWriteFinalDecisionSchedule3ActivitiesApply=\"Yes\" AND writeFinalDecisionAllowedOrRefused = \"allowed\" AND wcaAppeal = \"Yes\" AND writeFinalDecisionDateOfDecisionIsAfterSvDate=\"Yes\") OR (appeal.benefitType.code = \"ESA\" AND writeFinalDecisionSevereYesNo = \"Yes\")");
        fields.complex(SscsCaseData::getExtendedSscsCaseData)
                    .mandatory(ExtendedSscsCaseData::getEsaWriteFinalDecisionSevereCriteriaApply).done();
    }
}
