package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsUcCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code schedule6} of event {@code writeFinalDecision}.
 */
public final class WriteFinalDecisionSchedule6Page {
    private WriteFinalDecisionSchedule6Page() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("schedule6");
        fields.pageLabel("Select Schedule 6 activities");
        fields.showCondition("appeal.benefitType.code=\"UC\" AND wcaAppeal = \"Yes\" AND supportGroupOnlyAppeal=\"No\" AND writeFinalDecisionGenerateNotice = \"Yes\"  AND writeFinalDecisionSevereYesNo != \"Yes\"");
        fields.complex(SscsCaseData::getSscsUcCaseData)
                    .optional(SscsUcCaseData::getUcWriteFinalDecisionPhysicalDisabilitiesQuestion)
                    .optional(SscsUcCaseData::getUcWriteFinalDecisionMentalAssessmentQuestion).done();
    }
}
