package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.ExtendedSscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsEsaCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsUcCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code workCapabilityAssessment} of event {@code writeFinalDecision}.
 */
public final class WriteFinalDecisionWorkCapabilityAssessmentPage {
    private WriteFinalDecisionWorkCapabilityAssessmentPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("workCapabilityAssessment");
        fields.pageLabel("Work capability assessment");
        fields.showCondition("showWorkCapabilityAssessmentPage=\"Yes\"");
        fields.mandatory(SscsCaseData::getShowWorkCapabilityAssessmentPage)
                    .fieldShowCondition("appeal.benefitType.code=\"DoNotShow\"")
                    .retainHiddenValue();
        fields.mandatory(SscsCaseData::getWcaAppeal);
        fields.mandatory(SscsCaseData::getSupportGroupOnlyAppeal)
                    .fieldShowCondition("wcaAppeal=\"Yes\"")
                    .retainHiddenValue();
        fields.readonlyNoSummary(SscsCaseData::getIssueCode)
                    .fieldShowCondition("wcaAppeal=\"DoNotUse\"")
                    .retainHiddenValue();
        fields.complex(SscsCaseData::getSscsUcCaseData)
                    .readonlyNoSummary(SscsUcCaseData::getUcWriteFinalDecisionHasSVIssueCode)
                    .fieldShowCondition("writeFinalDecisionGenerateNotice=\"DoNotUse\"")
                    .retainHiddenValue().done();
        fields.complex(SscsCaseData::getExtendedSscsCaseData)
                    .mandatory(ExtendedSscsCaseData::getWriteFinalDecisionSevereYesNo)
                    .fieldShowCondition("wcaAppeal=\"Yes\" AND (appeal.benefitType.code=\"ESA\" OR appeal.benefitType.code=\"UC\") AND (issueCode=\"SV\" OR ucWriteFinalDecisionHasSVIssueCode = \"Yes\")")
                    .retainHiddenValue().done();
        fields.complex(SscsCaseData::getSscsUcCaseData)
                    .mandatory(SscsUcCaseData::getUcWriteFinalDecisionWorkCapabilityAssessmentStartDate)
                    .fieldShowCondition("appeal.benefitType.code=\"UC\" AND wcaAppeal=\"Yes\" AND writeFinalDecisionAllowedOrRefused = \"allowed\"")
                    .retainHiddenValue().done();
        fields.complex(SscsCaseData::getSscsEsaCaseData)
                    .mandatory(SscsEsaCaseData::getWhichEsaRegulationsApply)
                    .fieldShowCondition("wcaAppeal=\"Yes\" AND appeal.benefitType.code=\"ESA\"")
                    .retainHiddenValue().done();
    }
}
