package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsEsaCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code mobilisingUnaided} of event {@code writeFinalDecision}.
 */
public final class WriteFinalDecisionMobilisingUnaidedPage {
    private WriteFinalDecisionMobilisingUnaidedPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("mobilisingUnaided");
        fields.pageLabel("Physical disabilities: Mobilising unaided");
        fields.showCondition("esaWriteFinalDecisionPhysicalDisabilitiesQuestion CONTAINS \"mobilisingUnaided\" AND wcaAppeal = \"Yes\" AND supportGroupOnlyAppeal != \"Yes\"");
        fields.complex(SscsCaseData::getSscsEsaCaseData)
                    .mandatory(SscsEsaCaseData::getEsaWriteFinalDecisionMobilisingUnaidedQuestion).done();
    }
}
