package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsEsaCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code personalAction} of event {@code writeFinalDecision}.
 */
public final class WriteFinalDecisionPersonalActionPage {
    private WriteFinalDecisionPersonalActionPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("personalAction");
        fields.pageLabel("Mental, cognitive and intellectual function assessment: Initiating and completing personal action");
        fields.showCondition("esaWriteFinalDecisionMentalAssessmentQuestion CONTAINS \"personalAction\" AND wcaAppeal = \"Yes\" AND supportGroupOnlyAppeal != \"Yes\"");
        fields.complex(SscsCaseData::getSscsEsaCaseData)
                    .mandatory(SscsEsaCaseData::getEsaWriteFinalDecisionPersonalActionQuestion).done();
    }
}
