package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code dwpReassessTheAward} of event {@code writeFinalDecision}.
 */
public final class WriteFinalDecisionDwpReassessTheAwardPage {
    private WriteFinalDecisionDwpReassessTheAwardPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("dwpReassessTheAward");
        fields.pageLabel("When should DWP reassess the award?");
        fields.showCondition("showDwpReassessAwardPage = \"Yes\"");
        fields.readonly(SscsCaseData::getShowDwpReassessAwardPage)
                    .fieldShowCondition("writeFinalDecisionGenerateNotice=\"DoNotUse\"");
        fields.mandatory(SscsCaseData::getDwpReassessTheAward);
    }
}
