package uk.gov.hmcts.reform.sscs.ccd.event.page;

import uk.gov.hmcts.ccd.sdk.api.Event;
import uk.gov.hmcts.ccd.sdk.api.FieldCollection;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsEsaCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Wizard page {@code esaDecisionNoticeOptions} of event {@code writeFinalDecision}.
 */
public final class WriteFinalDecisionEsaDecisionNoticeOptionsPage {
    private WriteFinalDecisionEsaDecisionNoticeOptionsPage() {
    }

    /**
     * Applies this page's fields to the event.
     *
     * @param fields the event's field-collection builder
     */
    public static void apply(
            FieldCollection.FieldCollectionBuilder<SscsCaseData, State, Event.EventBuilder<SscsCaseData, UserRole, State>> fields) {
        fields.page("esaDecisionNoticeOptions");
        fields.pageLabel("Select Schedule 2 activities");
        fields.showCondition("appeal.benefitType.code=\"ESA\" AND wcaAppeal = \"Yes\" AND writeFinalDecisionGenerateNotice = \"Yes\" AND supportGroupOnlyAppeal != \"Yes\" AND writeFinalDecisionSevereYesNo != \"Yes\"");
        fields.complex(SscsCaseData::getSscsEsaCaseData)
                    .optional(SscsEsaCaseData::getEsaWriteFinalDecisionPhysicalDisabilitiesQuestion)
                    .optional(SscsEsaCaseData::getEsaWriteFinalDecisionMentalAssessmentQuestion).done();
    }
}
