package uk.gov.hmcts.reform.sscs.ccd.domain.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.Address;
import uk.gov.hmcts.reform.sscs.ccd.domain.Appointee;
import uk.gov.hmcts.reform.sscs.ccd.domain.Contact;
import uk.gov.hmcts.reform.sscs.ccd.domain.Identity;
import uk.gov.hmcts.reform.sscs.ccd.domain.JointParty;
import uk.gov.hmcts.reform.sscs.ccd.domain.Name;
import uk.gov.hmcts.reform.sscs.ccd.domain.OtherParty;
import uk.gov.hmcts.reform.sscs.ccd.domain.Representative;
import uk.gov.hmcts.reform.sscs.ccd.domain.Role;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;
import uk.gov.hmcts.reform.sscs.ccd.domain.ccd.event.page.DwpUploadResponseDecisionDisputedByOthersPage;
import uk.gov.hmcts.reform.sscs.ccd.domain.ccd.event.page.DwpUploadResponseElementsDisputedIdPage;
import uk.gov.hmcts.reform.sscs.ccd.domain.ccd.event.page.DwpUploadResponseElementsDisputedPage;
import uk.gov.hmcts.reform.sscs.ccd.domain.ccd.event.page.DwpUploadResponseJointPartyAddressPage;
import uk.gov.hmcts.reform.sscs.ccd.domain.ccd.event.page.DwpUploadResponseJointPartyIdentityPage;
import uk.gov.hmcts.reform.sscs.ccd.domain.ccd.event.page.DwpUploadResponseJointPartyNamePage;
import uk.gov.hmcts.reform.sscs.ccd.domain.ccd.event.page.DwpUploadResponseJointPartyPage;
import uk.gov.hmcts.reform.sscs.ccd.domain.ccd.event.page.DwpUploadResponsePage10;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code dwpUploadResponse} for case type {@code Benefit}.
 */
@Component
public class DwpUploadResponse implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String DWP_UPLOAD_RESPONSE = "dwpUploadResponse";

    /**
     * Registers event {@code dwpUploadResponse}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(DWP_UPLOAD_RESPONSE)
            .forStateTransition(EnumSet.of(State.WITH_DWP, State.READY_TO_LIST, State.NOT_LISTABLE, State.AWAIT_CONFIDENTIALITY_REQUIREMENTS, State.AWAIT_OTHER_PARTY_DATA), State.RESPONSE_RECEIVED)
            .name("Upload response")
            .description("Upload a response")
            .displayOrder(1760)
            .showSummary()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_DWPRESPONSEWRITER, UserRole.CASEWORKER_SSCS_HMRCRESPONSEWRITER, UserRole.CASEWORKER_SSCS_IBCARESPONSEWRITER, UserRole.CASEWORKER_SSCS_SUPERUSER, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS, UserRole.CASEWORKER_SSCS_CALLAGENT, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_JUDGE, UserRole.CASEWORKER_SSCS_REGISTRAR)
            .fields();
        DwpUploadResponsePage10.apply(fields);
        DwpUploadResponseElementsDisputedPage.apply(fields);
        DwpUploadResponseElementsDisputedIdPage.apply(fields);
        DwpUploadResponseDecisionDisputedByOthersPage.apply(fields);
        DwpUploadResponseJointPartyPage.apply(fields);
        DwpUploadResponseJointPartyNamePage.apply(fields);
        DwpUploadResponseJointPartyIdentityPage.apply(fields);
        DwpUploadResponseJointPartyAddressPage.apply(fields);
        fields.complex(SscsCaseData::getJointParty)
                    .complexScope(JointParty::getIdentity)
                    .mandatory(Identity::getDob)
                    .pageId("jointPartyIdentity")
                    .mandatory(Identity::getNino)
                    .fieldShowCondition("appeal.benefitType.code!=\"infectedBloodCompensation\"")
                    .pageId("jointPartyIdentity")
                    .mandatory(Identity::getIbcaReference)
                    .fieldShowCondition("appeal.benefitType.code=\"infectedBloodCompensation\"")
                    .pageId("jointPartyIdentity").done().done();
        fields.complex(SscsCaseData::getJointParty)
                    .complexScope(JointParty::getAddress)
                    .mandatory(Address::getLine1)
                    .pageId("jointPartyAddress")
                    .optional(Address::getLine2)
                    .pageId("jointPartyAddress")
                    .mandatory(Address::getTown)
                    .pageId("jointPartyAddress")
                    .mandatory(Address::getCounty)
                    .pageId("jointPartyAddress")
                    .mandatory(Address::getPostcode)
                    .pageId("jointPartyAddress").done().done();
        fields.complex(SscsCaseData::getOtherParties, OtherParty.class)
                    .mandatory(OtherParty::getName)
                    .pageId("otherPartyData")
                    .complex(OtherParty::getName)
                    .optional(Name::getTitle)
                    .pageId("otherPartyData").done()
                    .complex(OtherParty::getName)
                    .mandatory(Name::getFirstName)
                    .pageId("otherPartyData").done()
                    .complex(OtherParty::getName)
                    .mandatory(Name::getLastName)
                    .pageId("otherPartyData").done()
                    .mandatory(OtherParty::getAddress)
                    .pageId("otherPartyData")
                    .complex(OtherParty::getAddress)
                    .mandatory(Address::getLine1)
                    .pageId("otherPartyData").done()
                    .complex(OtherParty::getAddress)
                    .optional(Address::getLine2)
                    .pageId("otherPartyData").done()
                    .complex(OtherParty::getAddress)
                    .mandatory(Address::getTown)
                    .pageId("otherPartyData").done()
                    .complex(OtherParty::getAddress)
                    .optional(Address::getCounty)
                    .pageId("otherPartyData").done()
                    .complex(OtherParty::getAddress)
                    .mandatory(Address::getPostcode)
                    .pageId("otherPartyData").done()
                    .optional(OtherParty::getContact)
                    .pageId("otherPartyData")
                    .complex(OtherParty::getContact)
                    .optional(Contact::getPhone)
                    .pageId("otherPartyData").done()
                    .complex(OtherParty::getContact)
                    .optional(Contact::getMobile)
                    .pageId("otherPartyData").done()
                    .complex(OtherParty::getContact)
                    .optional(Contact::getEmail)
                    .pageId("1.0").done()
                    .mandatory(OtherParty::getConfidentialityRequired)
                    .pageId("otherPartyData")
                    .mandatory(OtherParty::getUnacceptableCustomerBehaviour)
                    .pageId("otherPartyData")
                    .mandatory(OtherParty::getRole)
                    .pageId("otherPartyData")
                    .complex(OtherParty::getRole)
                    .mandatory(Role::getName)
                    .pageId("otherPartyData").done()
                    .complex(OtherParty::getRole)
                    .mandatory(Role::getDescription)
                    .pageId("otherPartyData").done()
                    .optional(OtherParty::getIsAppointee)
                    .pageId("otherPartyData")
                    .optional(OtherParty::getAppointee)
                    .fieldShowCondition("otherParties.isAppointee = \"Yes\"")
                    .pageId("otherPartyData")
                    .complex(OtherParty::getAppointee)
                    .optional(Appointee::getName)
                    .pageId("otherPartyData").done()
                    .complex(OtherParty::getAppointee)
                    .complex(Appointee::getName)
                    .optional(Name::getTitle)
                    .pageId("otherPartyData").done().done()
                    .complex(OtherParty::getAppointee)
                    .complex(Appointee::getName)
                    .optional(Name::getFirstName)
                    .pageId("otherPartyData").done().done()
                    .complex(OtherParty::getAppointee)
                    .complex(Appointee::getName)
                    .optional(Name::getLastName)
                    .pageId("otherPartyData").done().done()
                    .complex(OtherParty::getAppointee)
                    .optional(Appointee::getAddress)
                    .pageId("otherPartyData").done()
                    .complex(OtherParty::getAppointee)
                    .complex(Appointee::getAddress)
                    .optional(Address::getLine1)
                    .pageId("otherPartyData").done().done()
                    .complex(OtherParty::getAppointee)
                    .complex(Appointee::getAddress)
                    .optional(Address::getLine2)
                    .pageId("otherPartyData").done().done()
                    .complex(OtherParty::getAppointee)
                    .complex(Appointee::getAddress)
                    .optional(Address::getTown)
                    .pageId("otherPartyData").done().done()
                    .complex(OtherParty::getAppointee)
                    .complex(Appointee::getAddress)
                    .optional(Address::getCounty)
                    .pageId("otherPartyData").done().done()
                    .complex(OtherParty::getAppointee)
                    .complex(Appointee::getAddress)
                    .optional(Address::getPostcode)
                    .pageId("otherPartyData").done().done()
                    .complex(OtherParty::getAppointee)
                    .optional(Appointee::getContact)
                    .pageId("otherPartyData").done()
                    .complex(OtherParty::getAppointee)
                    .complex(Appointee::getContact)
                    .optional(Contact::getPhone)
                    .pageId("otherPartyData").done().done()
                    .complex(OtherParty::getAppointee)
                    .complex(Appointee::getContact)
                    .optional(Contact::getMobile)
                    .pageId("otherPartyData").done().done()
                    .complex(OtherParty::getAppointee)
                    .complex(Appointee::getContact)
                    .optional(Contact::getEmail)
                    .pageId("otherPartyData").done().done()
                    .optional(OtherParty::getRep)
                    .pageId("otherPartyData")
                    .complex(OtherParty::getRep)
                    .optional(Representative::getHasRepresentative)
                    .pageId("otherPartyData").done()
                    .complex(OtherParty::getRep)
                    .optional(Representative::getOrganisation)
                    .pageId("otherPartyData").done()
                    .complex(OtherParty::getRep)
                    .optional(Representative::getName)
                    .pageId("otherPartyData").done()
                    .complex(OtherParty::getRep)
                    .complex(Representative::getName)
                    .optional(Name::getTitle)
                    .pageId("otherPartyData").done().done()
                    .complex(OtherParty::getRep)
                    .complex(Representative::getName)
                    .optional(Name::getFirstName)
                    .pageId("otherPartyData").done().done()
                    .complex(OtherParty::getRep)
                    .complex(Representative::getName)
                    .optional(Name::getLastName)
                    .pageId("otherPartyData").done().done()
                    .complex(OtherParty::getRep)
                    .optional(Representative::getAddress)
                    .pageId("otherPartyData").done()
                    .complex(OtherParty::getRep)
                    .complex(Representative::getAddress)
                    .optional(Address::getLine1)
                    .pageId("otherPartyData").done().done()
                    .complex(OtherParty::getRep)
                    .complex(Representative::getAddress)
                    .optional(Address::getLine2)
                    .pageId("otherPartyData").done().done()
                    .complex(OtherParty::getRep)
                    .complex(Representative::getAddress)
                    .optional(Address::getTown)
                    .pageId("otherPartyData").done().done()
                    .complex(OtherParty::getRep)
                    .complex(Representative::getAddress)
                    .optional(Address::getCounty)
                    .pageId("otherPartyData").done().done()
                    .complex(OtherParty::getRep)
                    .complex(Representative::getAddress)
                    .optional(Address::getPostcode)
                    .pageId("otherPartyData").done().done()
                    .complex(OtherParty::getRep)
                    .optional(Representative::getContact)
                    .pageId("otherPartyData").done()
                    .complex(OtherParty::getRep)
                    .complex(Representative::getContact)
                    .optional(Contact::getPhone)
                    .pageId("otherPartyData").done().done()
                    .complex(OtherParty::getRep)
                    .complex(Representative::getContact)
                    .optional(Contact::getMobile)
                    .pageId("otherPartyData").done().done()
                    .complex(OtherParty::getRep)
                    .complex(Representative::getContact)
                    .optional(Contact::getEmail)
                    .pageId("otherPartyData").done().done().done();
    }
}
