package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;
import uk.gov.hmcts.reform.sscs.ccd.event.page.ActionHearingRecordingRequestPage10;
import uk.gov.hmcts.reform.sscs.ccd.event.page.ActionHearingRecordingRequestSelectHearingPage;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code actionHearingRecordingRequest} for case type {@code Benefit}.
 */
@Component
public class ActionHearingRecordingRequest implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ACTION_HEARING_RECORDING_REQUEST = "actionHearingRecordingRequest";

    /**
     * Registers event {@code actionHearingRecordingRequest}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(ACTION_HEARING_RECORDING_REQUEST)
            .forAllStates()
            .name("Action hearing recording req")
            .description("Action hearing recording request")
            .displayOrder(60)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS)
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_SUPERUSER)
            .fields();
        ActionHearingRecordingRequestSelectHearingPage.apply(fields);
        ActionHearingRecordingRequestPage10.apply(fields);
    }
}
