package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.EnvironmentFlags;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;
import uk.gov.hmcts.reform.sscs.ccd.event.page.ActionPostponementRequestNonprodPage10;
import uk.gov.hmcts.reform.sscs.ccd.event.page.ActionPostponementRequestNonprodPage20;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code actionPostponementRequest} for case type {@code Benefit}.
 */
@Component
public class ActionPostponementRequestNonprod implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ACTION_POSTPONEMENT_REQUEST = "actionPostponementRequest";

    /**
     * Registers overlay event {@code actionPostponementRequest} (active when CCD_DEF_ENV=prod).
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        if (EnvironmentFlags.flag("CCD_DEF_ENV", "prod")) return;
        var fields = builder.event(ACTION_POSTPONEMENT_REQUEST)
            .forAllStates()
            .name("Action Postponement Request")
            .displayOrder(80)
            .showCondition("unprocessedPostponementRequest=\"Yes\" AND interlocReviewState!=\"none\" AND interlocReviewState!=\"awaitingAdminAction\" AND interlocReviewState!=\"welshTranslation\" AND interlocReviewState!=\"\"")
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_JUDGE, UserRole.CASEWORKER_SSCS_REGISTRAR, UserRole.CASEWORKER_SSCS_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS)
            .fields();
        ActionPostponementRequestNonprodPage10.apply(fields);
        ActionPostponementRequestNonprodPage20.apply(fields);
    }
}
