package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;
import uk.gov.hmcts.reform.sscs.ccd.event.page.AdjournCaseAdditionalDirectionsPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.AdjournCaseAreDirectionsBeingMadeToPartiesPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.AdjournCaseCanCaseBeListedRightAwayPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.AdjournCaseDirectionsDueDatePage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.AdjournCaseInterpreterRequiredPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.AdjournCaseNextHearingListingDurationPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.AdjournCaseNextHearingVenuePage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.AdjournCasePanelMemberNamesPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.AdjournCasePanelMembersExcludedPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.AdjournCasePreviewAdjournCasePage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.AdjournCaseReasonsPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.AdjournCaseTribunalDirectPoToAttendPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.AdjournCaseTypeOfAdjournmentPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.AdjournCaseTypeOfHearingPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.AdjournCaseTypeOfNextHearingPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.AdjournCaseWhenShouldNextHearingBePage;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code adjournCase} for case type {@code Benefit}.
 */
@Component
public class AdjournCase implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ADJOURN_CASE = "adjournCase";

    /**
     * Registers event {@code adjournCase}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(ADJOURN_CASE)
            .forAllStates()
            .name("Write adjournment notice")
            .displayOrder(1840)
            .showSummary()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS)
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_JUDGE, UserRole.CASEWORKER_SSCS_SUPERUSER)
            .fields();
        AdjournCasePanelMemberNamesPage.apply(fields);
        AdjournCaseTypeOfHearingPage.apply(fields);
        AdjournCaseCanCaseBeListedRightAwayPage.apply(fields);
        AdjournCaseAreDirectionsBeingMadeToPartiesPage.apply(fields);
        AdjournCaseDirectionsDueDatePage.apply(fields);
        AdjournCaseTypeOfNextHearingPage.apply(fields);
        AdjournCaseNextHearingVenuePage.apply(fields);
        AdjournCaseTribunalDirectPoToAttendPage.apply(fields);
        AdjournCaseNextHearingListingDurationPage.apply(fields);
        AdjournCaseInterpreterRequiredPage.apply(fields);
        AdjournCaseWhenShouldNextHearingBePage.apply(fields);
        AdjournCaseReasonsPage.apply(fields);
        AdjournCaseAdditionalDirectionsPage.apply(fields);
        AdjournCasePreviewAdjournCasePage.apply(fields);
        AdjournCaseTypeOfAdjournmentPage.apply(fields);
        AdjournCasePanelMembersExcludedPage.apply(fields);
    }
}
