package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code adminUpdateEvent} for case type {@code Benefit}.
 */
@Component
public class AdminUpdateEvent implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ADMIN_UPDATE_EVENT = "adminUpdateEvent";

    /**
     * Registers event {@code adminUpdateEvent}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(ADMIN_UPDATE_EVENT)
            .forAllStates()
            .name("Admin - update event")
            .displayOrder(280)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS)
            .fields();
        fields.page("1.0");
        fields.pageLabel("Update case");
        fields.optional(SscsCaseData::getCreatedInGapsFrom);
        fields.optional(SscsCaseData::getDirectionResponse);
        fields.optional(SscsCaseData::getDwpRegionalCentre);
        fields.optional(SscsCaseData::getUrgentCase);
        fields.optional(SscsCaseData::getUrgentHearingRegistered);
        fields.optional(SscsCaseData::getUrgentHearingOutcome);
        fields.optional(SscsCaseData::getDwpUcb);
        fields.optional(SscsCaseData::getIsInc5249521);
        fields.optional(SscsCaseData::getDateOfAppellantDeath);
        fields.optional(SscsCaseData::getHmctsDwpState);
        fields.optional(SscsCaseData::getIsProgressingViaGaps);
    }
}
