package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code adminCorrectionBody} for case type {@code Benefit}.
 */
@Component
public class AdminCorrectionBody implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ADMIN_CORRECTION_BODY = "adminCorrectionBody";

    /**
     * Registers event {@code adminCorrectionBody}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        builder.event(ADMIN_CORRECTION_BODY)
            .forStateTransition(EnumSet.allOf(State.class), State.POST_HEARING)
            .name("Correction Sent to Judge")
            .displayOrder(500)
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS);
    }
}
