package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code adminSendToDormantAppealState} for case type {@code Benefit}.
 */
@Component
public class AdminSendToDormantAppealState implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ADMIN_SEND_TO_DORMANT_APPEAL_STATE = "adminSendToDormantAppealState";

    /**
     * Registers event {@code adminSendToDormantAppealState}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        builder.event(ADMIN_SEND_TO_DORMANT_APPEAL_STATE)
            .forStateTransition(EnumSet.of(State.APPEAL_CREATED, State.DRAFT, State.DRAFT_ARCHIVED, State.HEARING, State.INCOMPLETE_APPLICATION, State.INCOMPLETE_APPLICATION_INFORMATION_REQUESTED, State.INTERLOCUTORY_REVIEW_STATE, State.READY_TO_LIST, State.RESPONSE_RECEIVED, State.VALID_APPEAL, State.VOID_STATE, State.WITH_DWP, State.NOT_LISTABLE, State.HANDLING_ERROR, State.POST_HEARING, State.WITH_UT, State.AWAIT_CONFIDENTIALITY_REQUIREMENTS, State.AWAIT_OTHER_PARTY_DATA), State.DORMANT_APPEAL_STATE)
            .name("Admin - send to Dormant")
            .displayOrder(160)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_SSCS_SUPERUSER, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS);
    }
}
