package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code attachRoboticsJson} for case type {@code Benefit}.
 */
@Component
public class AttachRoboticsJson implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ATTACH_ROBOTICS_JSON = "attachRoboticsJson";

    /**
     * Registers event {@code attachRoboticsJson}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        builder.event(ATTACH_ROBOTICS_JSON)
            .forState(State.APPEAL_CREATED)
            .name("Attach robotics jSON")
            .description("The Robotics JSON has been attached to the case")
            .displayOrder(490)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_SUPERUSER, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS);
    }
}
