package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.CaseOutcome;
import uk.gov.hmcts.reform.sscs.ccd.domain.JointParty;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code caseUpdated} for case type {@code Benefit}.
 */
@Component
public class CaseUpdated implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CASE_UPDATED = "caseUpdated";

    /**
     * Registers event {@code caseUpdated}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(CASE_UPDATED)
            .forAllStates()
            .name("Update to case data")
            .description("Automatic update of data from GAPS 2 - no notification")
            .displayOrder(1680)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS)
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_REGISTRAR, UserRole.CASEWORKER_SSCS_SUPERUSER, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE)
            .fields();
        fields.page("1.0");
        fields.pageLabel("Update case data");
        fields.optional(SscsCaseData::getCaseReference)
                    .fieldShowCondition("appeal.benefitType.descriptionSelection!=\"093\"");
        fields.optional(SscsCaseData::getCaseCreated);
        fields.optional(SscsCaseData::getRegion);
        fields.complex(SscsCaseData::getAppeal).done();
        fields.optional(SscsCaseData::getRegionalProcessingCenter);
        fields.mandatory(SscsCaseData::getBenefitCode)
                    .fieldShowCondition("appeal =\"DO_NOT_SHOW\"");
        fields.mandatory(SscsCaseData::getIssueCode);
        fields.mandatory(SscsCaseData::getChildMaintenanceNumber)
                    .fieldShowCondition("appeal.benefitType.code = \"childSupport\"");
        fields.complex(SscsCaseData::getJointParty)
                    .optional(JointParty::getHasJointParty)
                    .fieldShowCondition("appeal.benefitType.descriptionSelection=\"001\"")
                    .optional(JointParty::getName)
                    .fieldShowCondition("jointParty=\"Yes\"")
                    .optional(JointParty::getJointPartyAddressSameAsAppellant)
                    .fieldShowCondition("jointParty=\"Yes\"")
                    .optional(JointParty::getAddress)
                    .fieldShowCondition("jointParty=\"Yes\"")
                    .optional(JointParty::getIdentity)
                    .fieldShowCondition("jointParty=\"Yes\"")
                    .optional(JointParty::getContact)
                    .fieldShowCondition("jointParty=\"Yes\"").done();
        fields.complex(SscsCaseData::getCaseOutcome)
                    .optional(CaseOutcome::getCaseOutcome)
                    .optional(CaseOutcome::getDidPoAttend).done();
    }
}
