package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.Address;
import uk.gov.hmcts.reform.sscs.ccd.domain.Contact;
import uk.gov.hmcts.reform.sscs.ccd.domain.Identity;
import uk.gov.hmcts.reform.sscs.ccd.domain.JointParty;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;
import uk.gov.hmcts.reform.sscs.ccd.event.page.CaseUpdatedPage10Fields1;
import uk.gov.hmcts.reform.sscs.ccd.event.page.CaseUpdatedPage10Fields2;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code caseUpdated} for case type {@code Benefit}.
 */
@Component
public class CaseUpdated implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CASE_UPDATED = "caseUpdated";

    /**
     * Registers event {@code caseUpdated}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(CASE_UPDATED)
            .forAllStates()
            .name("Update to case data")
            .description("Automatic update of data from GAPS 2 - no notification")
            .displayOrder(1680)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS)
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_REGISTRAR, UserRole.CASEWORKER_SSCS_SUPERUSER, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE)
            .fields();
        fields.page("1.0");
        fields.pageLabel("Update case data");
        CaseUpdatedPage10Fields1.apply(fields);
        CaseUpdatedPage10Fields2.apply(fields);
        fields.complex(SscsCaseData::getJointParty)
                    .complexScope(JointParty::getAddress)
                    .optional(Address::getLine1)
                    .pageId("1.0")
                    .optional(Address::getLine2)
                    .pageId("1.0")
                    .optional(Address::getTown)
                    .pageId("1.0")
                    .optional(Address::getCounty)
                    .pageId("1.0")
                    .optional(Address::getPostcode)
                    .pageId("1.0").done().done();
        fields.complex(SscsCaseData::getJointParty)
                    .complexScope(JointParty::getIdentity)
                    .optional(Identity::getDob)
                    .fieldShowCondition("jointParty=\"Yes\"")
                    .pageId("1.0")
                    .optional(Identity::getNino)
                    .fieldShowCondition("jointParty=\"Yes\" AND appeal.benefitType.descriptionSelection!=\"093\"")
                    .pageId("1.0")
                    .optional(Identity::getIbcaReference)
                    .fieldShowCondition("jointParty=\"Yes\" AND appeal.benefitType.descriptionSelection=\"093\"")
                    .pageId("1.0").done().done();
        fields.complex(SscsCaseData::getJointParty)
                    .complexScope(JointParty::getContact)
                    .optional(Contact::getEmail)
                    .pageId("1.0")
                    .optional(Contact::getPhone)
                    .pageId("1.0")
                    .optional(Contact::getMobile)
                    .pageId("1.0").done().done();
    }
}
