package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code CCD_ADMIN} for case type {@code Benefit}.
 */
@Component
public class CCDADMIN implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CCD_ADMIN = "CCD_ADMIN";

    /**
     * Registers event {@code CCD_ADMIN}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        builder.event(CCD_ADMIN)
            .forAllStates()
            .name("CCD Admin")
            .displayOrder(520)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS, UserRole.CASEWORKER_SSCS_CALLAGENT, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_DWPRESPONSEWRITER, UserRole.CASEWORKER_SSCS_HMRCRESPONSEWRITER, UserRole.CASEWORKER_SSCS_JUDGE, UserRole.CASEWORKER_SSCS_REGISTRAR, UserRole.CASEWORKER_SSCS_SUPERUSER, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE);
    }
}
