package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code citizenRequestHearingRecording} for case type {@code Benefit}.
 */
@Component
public class CitizenRequestHearingRecording implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CITIZEN_REQUEST_HEARING_RECORDING = "citizenRequestHearingRecording";

    /**
     * Registers event {@code citizenRequestHearingRecording}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        builder.event(CITIZEN_REQUEST_HEARING_RECORDING)
            .forAllStates()
            .name("MYA Request hearing recording")
            .description("Request a hearing recording")
            .displayOrder(1110)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS, UserRole.CITIZEN)
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE);
    }
}
