package uk.gov.hmcts.reform.sscs.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code clearFailedFeFilter} for case type {@code Benefit}.
 */
@Component
public class ClearFailedFeFilter implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CLEAR_FAILED_FE_FILTER = "clearFailedFeFilter";

    /**
     * Registers event {@code clearFailedFeFilter}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        builder.event(CLEAR_FAILED_FE_FILTER)
            .forAllStates()
            .name("Clear failed sending FE filter")
            .displayOrder(531)
            .showCondition("hmctsDwpState=\"failedSendingFurtherEvidence\"")
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_SUPERUSER, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE);
    }
}
