package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code createWithDwpTestCase} for case type {@code Benefit}.
 */
@Component
public class CreateWithDwpTestCase implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CREATE_WITH_DWP_TEST_CASE = "createWithDwpTestCase";

    /**
     * Registers event {@code createWithDwpTestCase}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        builder.event(CREATE_WITH_DWP_TEST_CASE)
            .initialState(State.WITH_DWP)
            .name("Create with FTA test test")
            .description("Create a test case in withDwp state")
            .displayOrder(9970)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS);
    }
}
