package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;
import uk.gov.hmcts.reform.sscs.ccd.domain.WorkAllocationFields;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code createBundle} for case type {@code Benefit}.
 */
@Component
public class CreateBundle implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CREATE_BUNDLE = "createBundle";

    /**
     * Registers event {@code createBundle}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(CREATE_BUNDLE)
            .forAllStates()
            .name("Create a bundle")
            .description("Create a bundle in the case")
            .displayOrder(660)
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS)
            .grant(Permission.CRU, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_SUPERUSER, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE)
            .fields();
        fields.page("1.0");
        fields.pageLabel("Create Bundle");
        fields.showCondition("[STATE]=\"DoNotShow\"");
        fields.mandatory(SscsCaseData::getPanel)
                    .fieldShowCondition("[STATE]=\"DoNotShow\"")
                    .publishAs("panel");
        fields.complex(SscsCaseData::getWorkAllocationFields)
                    .optional(WorkAllocationFields::getAssignedCaseRoles)
                    .fieldShowCondition("[STATE]=\"DoNotShow\"").done();
    }
}
