package uk.gov.hmcts.reform.sscs.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code createWelshNotice} for case type {@code Benefit}.
 */
@Component
public class CreateWelshNotice implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CREATE_WELSH_NOTICE = "createWelshNotice";

    /**
     * Registers event {@code createWelshNotice}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(CREATE_WELSH_NOTICE)
            .forAllStates()
            .name("Welsh - create notice")
            .displayOrder(1870)
            .showCondition("languagePreferenceWelsh=\"Yes\"")
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_SUPERUSER, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE)
            .fields();
        fields.page("1.0");
        fields.pageLabel("Create Welsh Notice");
        fields.mandatory(SscsCaseData::getOriginalNoticeDocuments);
        fields.mandatory(SscsCaseData::getDocumentTypes);
        fields.mandatory(SscsCaseData::getEnglishBodyContent);
        fields.mandatory(SscsCaseData::getWelshBodyContent);
    }
}
