package uk.gov.hmcts.reform.sscs.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.EnvironmentFlags;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code createBundleAndAllocateCaseRolesRequired} for case type {@code Benefit}.
 */
@Component
public class CreateBundleAndAllocateCaseRolesRequiredNonprod implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String CREATE_BUNDLE_AND_ALLOCATE_CASE_ROLES_REQUIRED = "createBundleAndAllocateCaseRolesRequired";

    /**
     * Registers overlay event {@code createBundleAndAllocateCaseRolesRequired} (active when CCD_DEF_ENV=prod).
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        if (EnvironmentFlags.flag("CCD_DEF_ENV", "prod")) return;
        builder.event(CREATE_BUNDLE_AND_ALLOCATE_CASE_ROLES_REQUIRED)
            .forAllStates()
            .name("Bundle and Case Roles Required")
            .description("Create a bundle in the case")
            .displayOrder(9996)
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE);
    }
}
