package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code deathOfAppellantActioned} for case type {@code Benefit}.
 */
@Component
public class DeathOfAppellantActioned implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String DEATH_OF_APPELLANT_ACTIONED = "deathOfAppellantActioned";

    /**
     * Registers event {@code deathOfAppellantActioned}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        builder.event(DEATH_OF_APPELLANT_ACTIONED)
            .forAllStates()
            .name("Death of appellant actioned")
            .description("Action the death of an appellant")
            .displayOrder(697)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS)
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_SUPERUSER);
    }
}
