package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code decisionIssuedWelsh} for case type {@code Benefit}.
 */
@Component
public class DecisionIssuedWelsh implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String DECISION_ISSUED_WELSH = "decisionIssuedWelsh";

    /**
     * Registers event {@code decisionIssuedWelsh}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        builder.event(DECISION_ISSUED_WELSH)
            .forStateTransition(EnumSet.of(State.INCOMPLETE_APPLICATION, State.INCOMPLETE_APPLICATION_INFORMATION_REQUESTED, State.INTERLOCUTORY_REVIEW_STATE, State.APPEAL_CREATED, State.DORMANT_APPEAL_STATE, State.POST_HEARING, State.WITH_UT, State.HEARING, State.READY_TO_LIST, State.RESPONSE_RECEIVED, State.VALID_APPEAL, State.WITH_DWP, State.NOT_LISTABLE, State.HANDLING_ERROR, State.AWAIT_CONFIDENTIALITY_REQUIREMENTS, State.AWAIT_OTHER_PARTY_DATA), State.DORMANT_APPEAL_STATE)
            .name("Welsh - issue decision")
            .description("Send a welsh decision notice")
            .displayOrder(1900)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS, UserRole.CASEWORKER_SSCS_SUPERUSER);
    }
}
