package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code dwpActionRepAdded} for case type {@code Benefit}.
 */
@Component
public class DwpActionRepAdded implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String DWP_ACTION_REP_ADDED = "dwpActionRepAdded";

    /**
     * Registers event {@code dwpActionRepAdded}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(DWP_ACTION_REP_ADDED)
            .forAllStates()
            .name("Action new representative")
            .displayOrder(70)
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_DWPRESPONSEWRITER, UserRole.CASEWORKER_SSCS_HMRCRESPONSEWRITER, UserRole.CASEWORKER_SSCS_IBCARESPONSEWRITER, UserRole.CASEWORKER_SSCS_SUPERUSER, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS, UserRole.CASEWORKER_SSCS_ANONYMOUSCITIZEN, UserRole.CASEWORKER_SSCS_BULKSCAN, UserRole.CASEWORKER_SSCS_CALLAGENT, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_JUDGE, UserRole.CASEWORKER_SSCS_PANELMEMBER, UserRole.CASEWORKER_SSCS_REGISTRAR, UserRole.CASEWORKER_SSCS_TEAMLEADER)
            .fields();
        fields.page("1.0");
        fields.pageLabel("Action a new representative");
        fields.mandatoryNoSummary(SscsCaseData::getDwpState);
    }
}
