package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code dwpCaseInProgress} for case type {@code Benefit}.
 */
@Component
public class DwpCaseInProgress implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String DWP_CASE_IN_PROGRESS = "dwpCaseInProgress";

    /**
     * Registers event {@code dwpCaseInProgress}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(DWP_CASE_IN_PROGRESS)
            .forState(State.WITH_DWP)
            .name("Case in-progress")
            .description("Flag case as in-progress")
            .displayOrder(510)
            .showSummary()
            .explicitGrants()
            .grant(Set.of(Permission.R, Permission.U), UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_REGISTRAR)
            .grant(Permission.CRU, UserRole.CASEWORKER_SSCS_DWPRESPONSEWRITER, UserRole.CASEWORKER_SSCS_HMRCRESPONSEWRITER, UserRole.CASEWORKER_SSCS_IBCARESPONSEWRITER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS, UserRole.CASEWORKER_SSCS_JUDGE)
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_SUPERUSER, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE)
            .fields();
        fields.page("1.0");
        fields.pageLabel("Log case progress");
        fields.optionalNoSummary(SscsCaseData::getDwpFurtherEvidenceStates);
        fields.mandatoryNoSummary(SscsCaseData::getDwpState);
    }
}
