package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.DwpResponseDocument;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code dwpChallengeValidity} for case type {@code Benefit}.
 */
@Component
public class DwpChallengeValidity implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String DWP_CHALLENGE_VALIDITY = "dwpChallengeValidity";

    /**
     * Registers event {@code dwpChallengeValidity}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(DWP_CHALLENGE_VALIDITY)
            .forState(State.WITH_DWP)
            .name("Challenge validity")
            .displayOrder(530)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_SSCS_DWPRESPONSEWRITER, UserRole.CASEWORKER_SSCS_HMRCRESPONSEWRITER, UserRole.CASEWORKER_SSCS_IBCARESPONSEWRITER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS, UserRole.CASEWORKER_SSCS_CALLAGENT, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_JUDGE, UserRole.CASEWORKER_SSCS_REGISTRAR, UserRole.CASEWORKER_SSCS_SUPERUSER, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE)
            .fields();
        fields.page("1.0");
        fields.pageLabel("Challenge validity");
        fields.readonlyNoSummary(SscsCaseData::getAppeal)
                    .fieldShowCondition("[STATE]=\"DoNotUse\"");
        fields.complex(SscsCaseData::getDwpChallengeValidityDocument)
                    .optional(DwpResponseDocument::getDwpResponseDocumentTitle)
                    .fieldShowCondition("appeal.benefitType.code!=\"infectedBloodCompensation\" AND appeal.benefitType.code!=\"guardiansAllowance\" AND appeal.benefitType.code!=\"childBenefit\" AND appeal.benefitType.code!=\"nationalInsuranceCredits\" AND appeal.benefitType.code!=\"guaranteedMinimumPension\" AND appeal.benefitType.code!=\"homeResponsibilitiesProtection\" AND appeal.benefitType.code!=\"taxCredit\" AND appeal.benefitType.code!=\"taxFreeChildcare\" AND appeal.benefitType.code!=\"thirtyHoursFreeChildcare\"")
                    .pageId("1.0")
                    .optional(DwpResponseDocument::getHmrcResponseDocumentTitle)
                    .fieldShowCondition("appeal.benefitType.code=\"guardiansAllowance\" OR appeal.benefitType.code=\"childBenefit\" OR appeal.benefitType.code=\"nationalInsuranceCredits\" OR appeal.benefitType.code=\"guaranteedMinimumPension\" OR appeal.benefitType.code=\"homeResponsibilitiesProtection\" OR appeal.benefitType.code=\"taxCredit\" OR appeal.benefitType.code=\"taxFreeChildcare\" OR appeal.benefitType.code=\"thirtyHoursFreeChildcare\"")
                    .pageId("1.0")
                    .optional(DwpResponseDocument::getIbcaResponseDocumentTitle)
                    .fieldShowCondition("appeal.benefitType.code=\"infectedBloodCompensation\"")
                    .pageId("1.0")
                    .mandatory(DwpResponseDocument::getDocumentFileName)
                    .pageId("1.0")
                    .mandatory(DwpResponseDocument::getDocumentLink)
                    .noHintText()
                    .pageId("1.0").done();
        fields.mandatory(SscsCaseData::getDwpState);
    }
}
