package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;
import uk.gov.hmcts.reform.sscs.ccd.event.page.FtaCommunicationDeleteRequestPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.FtaCommunicationNewFtaRequestPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.FtaCommunicationReplyToFtaQueryPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.FtaCommunicationSelectFtaCommunicationActionPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.FtaCommunicationSelectFtaReplyPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.FtaCommunicationSelectFtaRequestPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.FtaCommunicationSelectRequestToDeletePage;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code ftaCommunication} for case type {@code Benefit}.
 */
@Component
public class FtaCommunication implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String FTA_COMMUNICATION = "ftaCommunication";

    /**
     * Registers event {@code ftaCommunication}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(FTA_COMMUNICATION)
            .forAllStates()
            .name("Communication with FTA")
            .displayOrder(544)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS)
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_REGISTRAR, UserRole.CASEWORKER_SSCS_SUPERUSER)
            .fields();
        FtaCommunicationSelectFtaCommunicationActionPage.apply(fields);
        FtaCommunicationNewFtaRequestPage.apply(fields);
        FtaCommunicationSelectFtaRequestPage.apply(fields);
        FtaCommunicationReplyToFtaQueryPage.apply(fields);
        FtaCommunicationSelectFtaReplyPage.apply(fields);
        FtaCommunicationSelectRequestToDeletePage.apply(fields);
        FtaCommunicationDeleteRequestPage.apply(fields);
    }
}
