package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code hmctsLapseCase} for case type {@code Benefit}.
 */
@Component
public class HmctsLapseCase implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String HMCTS_LAPSE_CASE = "hmctsLapseCase";

    /**
     * Registers event {@code hmctsLapseCase}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        builder.event(HMCTS_LAPSE_CASE)
            .forStateTransition(State.RESPONSE_RECEIVED, State.DORMANT_APPEAL_STATE)
            .name("Lapse case")
            .displayOrder(1020)
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_SUPERUSER, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS);
    }
}
