package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;
import uk.gov.hmcts.reform.sscs.ccd.event.page.HmctsResponseReviewedElementsDisputedIdPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.HmctsResponseReviewedElementsDisputedPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.HmctsResponseReviewedLinkedAppealRefPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.HmctsResponseReviewedPage10;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code hmctsResponseReviewed} for case type {@code Benefit}.
 */
@Component
public class HmctsResponseReviewed implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String HMCTS_RESPONSE_REVIEWED = "hmctsResponseReviewed";

    /**
     * Registers event {@code hmctsResponseReviewed}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(HMCTS_RESPONSE_REVIEWED)
            .forStates(State.RESPONSE_RECEIVED, State.INTERLOCUTORY_REVIEW_STATE)
            .name("Response reviewed")
            .description("FTA response has been reviewed")
            .displayOrder(1350)
            .showSummary(false)
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_SUPERUSER, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS)
            .fields();
        HmctsResponseReviewedPage10.apply(fields);
        HmctsResponseReviewedElementsDisputedPage.apply(fields);
        HmctsResponseReviewedElementsDisputedIdPage.apply(fields);
        HmctsResponseReviewedLinkedAppealRefPage.apply(fields);
    }
}
