package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.EnvironmentFlags;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code interlocSendToTcw} for case type {@code Benefit}.
 */
@Component
public class InterlocSendToTcwNonprod implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String INTERLOC_SEND_TO_TCW = "interlocSendToTcw";

    /**
     * Registers overlay event {@code interlocSendToTcw} (active when CCD_DEF_ENV=prod).
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        if (EnvironmentFlags.flag("CCD_DEF_ENV", "prod")) return;
        var fields = builder.event(INTERLOC_SEND_TO_TCW)
            .forAllStates()
            .name("Send case to TCW")
            .displayOrder(1390)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_JUDGE)
            .grant(Permission.CRU, UserRole.CASEWORKER_SSCS_REGISTRAR)
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_SUPERUSER, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE)
            .fields();
        fields.page("1.0");
        fields.pageLabel("Log case progress");
        fields.mandatory(SscsCaseData::getInterlocReviewState);
        fields.mandatory(SscsCaseData::getTempNoteDetail);
    }
}
