package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code interlocValidAppeal} for case type {@code Benefit}.
 */
@Component
public class InterlocValidAppeal implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String INTERLOC_VALID_APPEAL = "interlocValidAppeal";

    /**
     * Registers event {@code interlocValidAppeal}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(INTERLOC_VALID_APPEAL)
            .forStateTransition(State.INTERLOCUTORY_REVIEW_STATE, State.VALID_APPEAL)
            .name("Validate appeal")
            .description("Makes an appeal valid")
            .displayOrder(1790)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_SUPERUSER, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE)
            .fields();
        fields.page("1.0");
        fields.pageLabel("Validate appeal");
        fields.mandatory(SscsCaseData::getClerkAppealSatisfactionText)
                    .fieldShowCondition("isWaiverNeeded=\"Yes\"");
        fields.mandatory(SscsCaseData::getClerkConfirmationOfMrn)
                    .fieldShowCondition("isWaiverNeeded=\"Yes\"");
        fields.optional(SscsCaseData::getClerkConfirmationOther)
                    .fieldShowCondition("isWaiverNeeded=\"Yes\" AND clerkOtherReason=\"Yes\"");
        fields.mandatory(SscsCaseData::getClerkDelegatedAuthority)
                    .fieldShowCondition("isWaiverNeeded=\"Yes\"");
        fields.mandatory(SscsCaseData::getClerkOtherReason)
                    .fieldShowCondition("isWaiverNeeded=\"Yes\"");
        fields.mandatory(SscsCaseData::getIsWaiverNeeded);
        fields.mandatory(SscsCaseData::getWaiverDeclaration)
                    .fieldShowCondition("isWaiverNeeded=\"Yes\"");
        fields.mandatory(SscsCaseData::getWaiverReason)
                    .fieldShowCondition("isWaiverNeeded=\"Yes\"");
        fields.optional(SscsCaseData::getWaiverReasonOther)
                    .fieldShowCondition("isWaiverNeeded=\"Yes\"");
    }
}
