package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code issueFinalDecisionWelsh} for case type {@code Benefit}.
 */
@Component
public class IssueFinalDecisionWelsh implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ISSUE_FINAL_DECISION_WELSH = "issueFinalDecisionWelsh";

    /**
     * Registers event {@code issueFinalDecisionWelsh}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        builder.event(ISSUE_FINAL_DECISION_WELSH)
            .forStateTransition(EnumSet.of(State.DORMANT_APPEAL_STATE, State.POST_HEARING, State.WITH_UT), State.DORMANT_APPEAL_STATE)
            .name("Welsh - issue final decision")
            .description("Issue a Welsh final decision notice")
            .displayOrder(1920)
            .showSummary(false)
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS)
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE);
    }
}
