package uk.gov.hmcts.reform.sscs.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;
import uk.gov.hmcts.reform.sscs.ccd.event.page.IssueGenericLetterPage10;
import uk.gov.hmcts.reform.sscs.ccd.event.page.IssueGenericLetterPage20;
import uk.gov.hmcts.reform.sscs.ccd.event.page.IssueGenericLetterPage30;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code issueGenericLetter} for case type {@code Benefit}.
 */
@Component
public class IssueGenericLetter implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ISSUE_GENERIC_LETTER = "issueGenericLetter";

    /**
     * Registers event {@code issueGenericLetter}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(ISSUE_GENERIC_LETTER)
            .forAllStates()
            .name("Issue generic letter")
            .displayOrder(991)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_SUPERUSER, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE)
            .fields();
        IssueGenericLetterPage10.apply(fields);
        IssueGenericLetterPage20.apply(fields);
        IssueGenericLetterPage30.apply(fields);
    }
}
