package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code issueAdjournmentNoticeWelsh} for case type {@code Benefit}.
 */
@Component
public class IssueAdjournmentNoticeWelsh implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ISSUE_ADJOURNMENT_NOTICE_WELSH = "issueAdjournmentNoticeWelsh";

    /**
     * Registers event {@code issueAdjournmentNoticeWelsh}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        builder.event(ISSUE_ADJOURNMENT_NOTICE_WELSH)
            .forStateTransition(State.HEARING, State.READY_TO_LIST)
            .name("Welsh - adjournment notice")
            .description("Send a welsh adjournment notice")
            .displayOrder(1890)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS)
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_SUPERUSER, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE);
    }
}
