package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code issueFinalDecision} for case type {@code Benefit}.
 */
@Component
public class IssueFinalDecision implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ISSUE_FINAL_DECISION = "issueFinalDecision";

    /**
     * Registers event {@code issueFinalDecision}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(ISSUE_FINAL_DECISION)
            .forStateTransition(EnumSet.of(State.INCOMPLETE_APPLICATION, State.INCOMPLETE_APPLICATION_INFORMATION_REQUESTED, State.INTERLOCUTORY_REVIEW_STATE, State.APPEAL_CREATED, State.DORMANT_APPEAL_STATE, State.POST_HEARING, State.WITH_UT, State.HEARING, State.READY_TO_LIST, State.RESPONSE_RECEIVED, State.VALID_APPEAL, State.WITH_DWP, State.NOT_LISTABLE, State.HANDLING_ERROR, State.AWAIT_CONFIDENTIALITY_REQUIREMENTS, State.AWAIT_OTHER_PARTY_DATA), State.DORMANT_APPEAL_STATE)
            .name("Issue final decision")
            .description("Issue a final decision notice for a case")
            .displayOrder(980)
            .showSummary(false)
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS)
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_JUDGE, UserRole.CASEWORKER_SSCS_SUPERUSER)
            .fields();
        fields.page("previewDecisionNotice");
        fields.pageLabel("Preview Decision Notice");
    }
}
