package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.Adjournment;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code issueAdjournmentNotice} for case type {@code Benefit}.
 */
@Component
public class IssueAdjournmentNotice implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ISSUE_ADJOURNMENT_NOTICE = "issueAdjournmentNotice";

    /**
     * Registers event {@code issueAdjournmentNotice}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(ISSUE_ADJOURNMENT_NOTICE)
            .forAllStates()
            .name("Issue adjournment notice")
            .description("Send an adjournment notice")
            .displayOrder(930)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS)
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_JUDGE, UserRole.CASEWORKER_SSCS_SUPERUSER)
            .fields();
        fields.page("previewAdjournmentNotice");
        fields.pageLabel("Preview Adjournment Notice");
        fields.complex(SscsCaseData::getAdjournment)
                    .mandatory(Adjournment::getPreviewDocument).done();
    }
}
