package uk.gov.hmcts.reform.sscs.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;
import uk.gov.hmcts.reform.sscs.ccd.event.page.IssueHearingEnquiryFormPage10;
import uk.gov.hmcts.reform.sscs.ccd.event.page.IssueHearingEnquiryFormPage20;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code issueHearingEnquiryForm} for case type {@code Benefit}.
 */
@Component
public class IssueHearingEnquiryForm implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String ISSUE_HEARING_ENQUIRY_FORM = "issueHearingEnquiryForm";

    /**
     * Registers event {@code issueHearingEnquiryForm}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(ISSUE_HEARING_ENQUIRY_FORM)
            .forAllStates()
            .name("Issue hearing enquiry form")
            .displayOrder(992)
            .showCondition("appeal.benefitType.code=\"childSupport\" OR appeal.benefitType.code=\"UC\"")
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_SUPERUSER)
            .fields();
        IssueHearingEnquiryFormPage10.apply(fields);
        IssueHearingEnquiryFormPage20.apply(fields);
    }
}
