package uk.gov.hmcts.reform.sscs.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code judgeDecisionStrikeout} for case type {@code Benefit}.
 */
@Component
public class JudgeDecisionStrikeout implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String JUDGE_DECISION_STRIKEOUT = "judgeDecisionStrikeout";

    /**
     * Registers event {@code judgeDecisionStrikeout}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        builder.event(JUDGE_DECISION_STRIKEOUT)
            .forStateTransition(State.INTERLOCUTORY_REVIEW_STATE, State.DORMANT_APPEAL_STATE)
            .name("Strike out (Judge)")
            .displayOrder(1530)
            .showEventNotes()
            .explicitGrants();
    }
}
