package uk.gov.hmcts.reform.sscs.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code manageDwpDocuments} for case type {@code Benefit}.
 */
@Component
public class ManageDwpDocuments implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String MANAGE_DWP_DOCUMENTS = "manageDwpDocuments";

    /**
     * Registers event {@code manageDwpDocuments}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(MANAGE_DWP_DOCUMENTS)
            .forAllStates()
            .name("Manage FTA document(s)")
            .displayOrder(1080)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_SUPERUSER)
            .fields();
        fields.page("1.0");
        fields.pageLabel("Upload FTA documents");
        fields.optional(SscsCaseData::getDwpDocuments);
    }
}
