package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code manageScannedDocuments} for case type {@code Benefit}.
 */
@Component
public class ManageScannedDocuments implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String MANAGE_SCANNED_DOCUMENTS = "manageScannedDocuments";

    /**
     * Registers event {@code manageScannedDocuments}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(MANAGE_SCANNED_DOCUMENTS)
            .forAllStates()
            .name("Manage Unprocessed Corres")
            .description("Manage unprocessed correspondence")
            .displayOrder(1120)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS)
            .fields();
        fields.page("1.0");
        fields.pageLabel("Manage unprocessed correspondence");
        fields.optional(SscsCaseData::getScannedDocuments);
    }
}
