package uk.gov.hmcts.reform.sscs.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;
import uk.gov.hmcts.reform.sscs.ccd.domain.WorkAllocationFields;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code manageWelshDocuments} for case type {@code Benefit}.
 */
@Component
public class ManageWelshDocuments implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String MANAGE_WELSH_DOCUMENTS = "manageWelshDocuments";

    /**
     * Registers event {@code manageWelshDocuments}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(MANAGE_WELSH_DOCUMENTS)
            .forAllStates()
            .name("Welsh – manage Welsh doc(s)")
            .description("Manage Welsh document(s)")
            .displayOrder(1930)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_SUPERUSER)
            .fields();
        fields.page("1.0");
        fields.pageLabel("Manage Welsh Doc(s)");
        fields.complex(SscsCaseData::getWorkAllocationFields)
                    .mandatory(WorkAllocationFields::getUploadedWelshDocumentTypes)
                    .fieldShowCondition("[STATE]=\"DoNotShow\"")
                    .publishAs("scannedDocumentTypes").done();
        fields.optional(SscsCaseData::getSscsWelshDocuments);
    }
}
