package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code manageAudioVideo} for case type {@code Benefit}.
 */
@Component
public class ManageAudioVideo implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String MANAGE_AUDIO_VIDEO = "manageAudioVideo";

    /**
     * Registers event {@code manageAudioVideo}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(MANAGE_AUDIO_VIDEO)
            .forAllStates()
            .name("Manage audio/video evidence")
            .description("Manage audio video unprocessed list")
            .displayOrder(1070)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS)
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_SUPERUSER)
            .fields();
        fields.page("1.0");
        fields.pageLabel("Manage Audio/Video evidence");
        fields.optional(SscsCaseData::getAudioVideoEvidence);
    }
}
