package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code moveToAppealCreated} for case type {@code Benefit}.
 */
@Component
public class MoveToAppealCreated implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String MOVE_TO_APPEAL_CREATED = "moveToAppealCreated";

    /**
     * Registers event {@code moveToAppealCreated}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        builder.event(MOVE_TO_APPEAL_CREATED)
            .forStateTransition(State.VALID_APPEAL, State.APPEAL_CREATED)
            .name("Move to appeal created")
            .description("Deprecated - Moves case to appeal created")
            .displayOrder(1100)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS);
    }
}
