package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;
import uk.gov.hmcts.reform.sscs.ccd.event.page.NonCompliantSendToInterlocPage10;
import uk.gov.hmcts.reform.sscs.ccd.event.page.NonCompliantSendToInterlocPage20;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code nonCompliantSendToInterloc} for case type {@code Benefit}.
 */
@Component
public class NonCompliantSendToInterloc implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String NON_COMPLIANT_SEND_TO_INTERLOC = "nonCompliantSendToInterloc";

    /**
     * Registers event {@code nonCompliantSendToInterloc}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(NON_COMPLIANT_SEND_TO_INTERLOC)
            .forStateTransition(EnumSet.of(State.INCOMPLETE_APPLICATION, State.INCOMPLETE_APPLICATION_INFORMATION_REQUESTED), State.INTERLOCUTORY_REVIEW_STATE)
            .name("Send to interloc - pre-valid")
            .description("Send a case to a judge for review")
            .displayOrder(1460)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS, UserRole.CASEWORKER_SSCS_JUDGE, UserRole.CASEWORKER_SSCS_REGISTRAR)
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_SUPERUSER, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE)
            .fields();
        NonCompliantSendToInterlocPage10.apply(fields);
        NonCompliantSendToInterlocPage20.apply(fields);
    }
}
