package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code panelUpdate} for case type {@code Benefit}.
 */
@Component
public class PanelUpdate implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String PANEL_UPDATE = "panelUpdate";

    /**
     * Registers event {@code panelUpdate}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(PANEL_UPDATE)
            .forStates(State.APPEAL_CREATED, State.VOID_STATE, State.INTERLOCUTORY_REVIEW_STATE)
            .name("Create/update Panel")
            .description("Add Judge, Medical member and Disability qualified member")
            .displayOrder(690)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_JUDGE, UserRole.CASEWORKER_SSCS_SUPERUSER)
            .fields();
        fields.page("1.0");
        fields.pageLabel("Panel");
        fields.optional(SscsCaseData::getPanel);
    }
}
