package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;
import uk.gov.hmcts.reform.sscs.ccd.event.page.PostHearingReviewCorrectionPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.PostHearingReviewLibertyToApplyPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.PostHearingReviewNoticeStagingPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.PostHearingReviewPermissionToAppealPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.PostHearingReviewSetAsidePage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.PostHearingReviewStatementOfReasonsPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.PostHearingReviewTypeSelectionPage;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code postHearingReview} for case type {@code Benefit}.
 */
@Component
public class PostHearingReview implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String POST_HEARING_REVIEW = "postHearingReview";

    /**
     * Registers event {@code postHearingReview}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(POST_HEARING_REVIEW)
            .forStates(State.DORMANT_APPEAL_STATE, State.POST_HEARING)
            .name("Review Post Hearing App")
            .description("Review Post Hearing Application")
            .displayOrder(1381)
            .showCondition("hearingRoute=\"listAssist\"")
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_JUDGE, UserRole.CASEWORKER_SSCS_JUDGE_SALARIED, UserRole.CASEWORKER_SSCS_SUPERUSER, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS)
            .fields();
        PostHearingReviewTypeSelectionPage.apply(fields);
        PostHearingReviewSetAsidePage.apply(fields);
        PostHearingReviewCorrectionPage.apply(fields);
        PostHearingReviewStatementOfReasonsPage.apply(fields);
        PostHearingReviewNoticeStagingPage.apply(fields);
        PostHearingReviewLibertyToApplyPage.apply(fields);
        PostHearingReviewPermissionToAppealPage.apply(fields);
    }
}
