package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;
import uk.gov.hmcts.reform.sscs.ccd.event.page.PostHearingRequestCorrectionPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.PostHearingRequestLibertyToApplyPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.PostHearingRequestPermissionToAppealPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.PostHearingRequestRequestStagingPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.PostHearingRequestSetAsidePage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.PostHearingRequestStatementOfReasonsPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.PostHearingRequestTypeSelectionPage;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code postHearingRequest} for case type {@code Benefit}.
 */
@Component
public class PostHearingRequest implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String POST_HEARING_REQUEST = "postHearingRequest";

    /**
     * Registers event {@code postHearingRequest}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(POST_HEARING_REQUEST)
            .forStates(State.DORMANT_APPEAL_STATE, State.POST_HEARING, State.WITH_UT)
            .name("Post Hearing Request")
            .displayOrder(1199)
            .showCondition("hearingRoute=\"listAssist\"")
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_DWPRESPONSEWRITER, UserRole.CASEWORKER_SSCS_HMRCRESPONSEWRITER, UserRole.CASEWORKER_SSCS_IBCARESPONSEWRITER, UserRole.CASEWORKER_SSCS_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS)
            .fields();
        PostHearingRequestTypeSelectionPage.apply(fields);
        PostHearingRequestSetAsidePage.apply(fields);
        PostHearingRequestCorrectionPage.apply(fields);
        PostHearingRequestStatementOfReasonsPage.apply(fields);
        PostHearingRequestRequestStagingPage.apply(fields);
        PostHearingRequestLibertyToApplyPage.apply(fields);
        PostHearingRequestPermissionToAppealPage.apply(fields);
    }
}
