package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;
import uk.gov.hmcts.reform.sscs.ccd.event.page.ProcessAudioVideoPage10;
import uk.gov.hmcts.reform.sscs.ccd.event.page.ProcessAudioVideoPage20;
import uk.gov.hmcts.reform.sscs.ccd.event.page.ProcessAudioVideoPage30;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code processAudioVideo} for case type {@code Benefit}.
 */
@Component
public class ProcessAudioVideo implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String PROCESS_AUDIO_VIDEO = "processAudioVideo";

    /**
     * Registers event {@code processAudioVideo}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(PROCESS_AUDIO_VIDEO)
            .forAllStates()
            .name("Process audio/video evidence")
            .description("Issue a direction notice based on audio and video evidence")
            .displayOrder(1200)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_JUDGE, UserRole.CASEWORKER_SSCS_REGISTRAR, UserRole.CASEWORKER_SSCS_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS)
            .fields();
        ProcessAudioVideoPage10.apply(fields);
        ProcessAudioVideoPage20.apply(fields);
        ProcessAudioVideoPage30.apply(fields);
    }
}
