package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code reinstateAppeal} for case type {@code Benefit}.
 */
@Component
public class ReinstateAppeal implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String REINSTATE_APPEAL = "reinstateAppeal";

    /**
     * Registers event {@code reinstateAppeal}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        builder.event(REINSTATE_APPEAL)
            .forStateTransition(EnumSet.of(State.DORMANT_APPEAL_STATE, State.POST_HEARING, State.WITH_UT), State.INTERLOCUTORY_REVIEW_STATE)
            .name("Re-open appeal")
            .description("Reinstate case to interloc state")
            .displayOrder(1240)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS)
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_SUPERUSER, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE);
    }
}
