package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code reinstateVoidAppeal} for case type {@code Benefit}.
 */
@Component
public class ReinstateVoidAppeal implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String REINSTATE_VOID_APPEAL = "reinstateVoidAppeal";

    /**
     * Registers event {@code reinstateVoidAppeal}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        builder.event(REINSTATE_VOID_APPEAL)
            .forStateTransition(State.VOID_STATE, State.APPEAL_CREATED)
            .name("Reinstate case")
            .description("Deprecated - Resinstates a Void case to valid")
            .displayOrder(1990)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS);
    }
}
