package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code reserveToInterlocJudge} for case type {@code Benefit}.
 */
@Component
public class ReserveToInterlocJudge implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String RESERVE_TO_INTERLOC_JUDGE = "reserveToInterlocJudge";

    /**
     * Registers event {@code reserveToInterlocJudge}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(RESERVE_TO_INTERLOC_JUDGE)
            .forAllStates()
            .name("Reserve to Judge Interloc")
            .displayOrder(1281)
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_JUDGE, UserRole.CASEWORKER_SSCS_REGISTRAR, UserRole.CASEWORKER_SSCS_SUPERUSER, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS)
            .fields();
        fields.page("1.0");
        fields.pageLabel("Reserve to Judge Interloc");
        fields.mandatory(SscsCaseData::getJudgeReserved);
        fields.mandatory(SscsCaseData::getReservedToJudgeInterloc)
                    .fieldShowCondition("judgeReserved = \"Yes\"");
    }
}
