package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code reviewConfidentialityRequest} for case type {@code Benefit}.
 */
@Component
public class ReviewConfidentialityRequest implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String REVIEW_CONFIDENTIALITY_REQUEST = "reviewConfidentialityRequest";

    /**
     * Registers event {@code reviewConfidentialityRequest}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(REVIEW_CONFIDENTIALITY_REQUEST)
            .forAllStates()
            .name("Review confidentiality request")
            .displayOrder(1360)
            .showSummary()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_JUDGE, UserRole.CASEWORKER_SSCS_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS)
            .fields();
        fields.page("1.0");
        fields.pageLabel("Review confidentiality request");
        fields.readonly(SscsCaseData::getConfidentialityRequestOutcomeAppellant)
                    .fieldShowCondition("confidentialityRequestAppellantGrantedOrRefused = \"doNotUse\"");
        fields.readonly(SscsCaseData::getConfidentialityRequestOutcomeJointParty)
                    .fieldShowCondition("confidentialityRequestJointPartyGrantedOrRefused = \"doNotUse\"");
        fields.mandatory(SscsCaseData::getConfidentialityRequestAppellantGrantedOrRefused)
                    .fieldShowCondition("confidentialityRequestOutcomeAppellant.requestOutcome = \"inProgress\"")
                    .retainHiddenValue()
                    .showSummaryContentOption(0);
        fields.mandatory(SscsCaseData::getConfidentialityRequestJointPartyGrantedOrRefused)
                    .fieldShowCondition("confidentialityRequestOutcomeJointParty.requestOutcome = \"inProgress\"")
                    .retainHiddenValue()
                    .showSummaryContentOption(0);
    }
}
