package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code sendToDwpError} for case type {@code Benefit}.
 */
@Component
public class SendToDwpError implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SEND_TO_DWP_ERROR = "sendToDwpError";

    /**
     * Registers event {@code sendToDwpError}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        builder.event(SEND_TO_DWP_ERROR)
            .forState(State.VALID_APPEAL)
            .name("Send to FTA error")
            .description("Flag error to Send to FTA")
            .displayOrder(1430)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS)
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_SUPERUSER, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE)
            .grant(Set.of(Permission.R, Permission.U), UserRole.CASEWORKER_SSCS_DWPRESPONSEWRITER, UserRole.CASEWORKER_SSCS_HMRCRESPONSEWRITER);
    }
}
