package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code sendToAdmin} for case type {@code Benefit}.
 */
@Component
public class SendToAdmin implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SEND_TO_ADMIN = "sendToAdmin";

    /**
     * Registers event {@code sendToAdmin}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(SEND_TO_ADMIN)
            .forAllStates()
            .name("Send to admin")
            .description("Return the case to an admin with a note")
            .displayOrder(1410)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CR, UserRole.CASEWORKER_SSCS_JUDGE, UserRole.CASEWORKER_SSCS_REGISTRAR, UserRole.CASEWORKER_SSCS_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS, UserRole.CASEWORKER_SSCS_CALLAGENT, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_DWPRESPONSEWRITER, UserRole.CASEWORKER_SSCS_HMRCRESPONSEWRITER, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE)
            .fields();
        fields.page("1.0");
        fields.pageLabel("Send to admin");
        fields.mandatory(SscsCaseData::getTempNoteDetail);
    }
}
