package uk.gov.hmcts.reform.sscs.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code sendValidCaseToInterloc} for case type {@code Benefit}.
 */
@Component
public class SendValidCaseToInterloc implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SEND_VALID_CASE_TO_INTERLOC = "sendValidCaseToInterloc";

    /**
     * Registers event {@code sendValidCaseToInterloc}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        builder.event(SEND_VALID_CASE_TO_INTERLOC)
            .forState(State.WITH_DWP)
            .name("Send valid case to interloc")
            .displayOrder(1490)
            .showSummary()
            .showEventNotes()
            .explicitGrants();
    }
}
