package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.CaseAccessManagementFields;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code sendToDwp} for case type {@code Benefit}.
 */
@Component
public class SendToDwp implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SEND_TO_DWP = "sendToDwp";

    /**
     * Registers event {@code sendToDwp}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(SEND_TO_DWP)
            .forState(State.VALID_APPEAL)
            .name("Send to FTA")
            .displayOrder(1420)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS)
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE)
            .fields();
        fields.page("1.0");
        fields.pageLabel("Sent to FTA state");
        fields.complex(SscsCaseData::getCaseAccessManagementFields)
                    .mandatory(CaseAccessManagementFields::getCaseManagementCategory)
                    .fieldShowCondition("[STATE]=\"doNotUse\"")
                    .retainHiddenValue().done();
        fields.mandatory(SscsCaseData::getHmctsDwpState);
    }
}
