package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code setAsideRefusedSOR} for case type {@code Benefit}.
 */
@Component
public class SetAsideRefusedSOR implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SET_ASIDE_REFUSED_SOR = "setAsideRefusedSOR";

    /**
     * Registers event {@code setAsideRefusedSOR}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(SET_ASIDE_REFUSED_SOR)
            .forAllStates()
            .name("Set Aside Refused - SOR")
            .displayOrder(500)
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS)
            .fields();
        fields.page("1.0");
        fields.pageLabel("Set Aside Refused - SOR");
        fields.readonly(SscsCaseData::getIssueFinalDecisionDate)
                    .fieldShowCondition("[STATE]=\"DoNotUse\"");
    }
}
