package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;
import uk.gov.hmcts.reform.sscs.ccd.event.page.SORWriteSORStagingPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.SORWriteWriteStatementOfReasonsPage;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code sORWrite} for case type {@code Benefit}.
 */
@Component
public class SORWrite implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String S_ORWRITE = "sORWrite";

    /**
     * Registers event {@code sORWrite}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(S_ORWRITE)
            .forStateTransition(EnumSet.of(State.POST_HEARING, State.DORMANT_APPEAL_STATE, State.WITH_UT), State.DORMANT_APPEAL_STATE)
            .name("Write and Issue SOR")
            .displayOrder(1855)
            .showCondition("hearingRoute=\"listAssist\"")
            .showSummary(false)
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_JUDGE, UserRole.CASEWORKER_SSCS_SUPERUSER, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS)
            .fields();
        SORWriteWriteStatementOfReasonsPage.apply(fields);
        SORWriteSORStagingPage.apply(fields);
    }
}
