package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;
import uk.gov.hmcts.reform.sscs.ccd.event.page.SuperUserFullEditAdjournmentDetailsPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.SuperUserFullEditAppealDetailsPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.SuperUserFullEditCaseClassificationPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.SuperUserFullEditCaseStatusAndNotesPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.SuperUserFullEditConfidentialityAndAdjustmentsPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.SuperUserFullEditDwpFlagsPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.SuperUserFullEditJointPartyDetailsPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.SuperUserFullEditOtherPartiesDetailsPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.SuperUserFullEditSystemFlagsPage;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code superUserFullEdit} for case type {@code Benefit}.
 */
@Component
public class SuperUserFullEdit implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String SUPER_USER_FULL_EDIT = "superUserFullEdit";

    /**
     * Registers event {@code superUserFullEdit}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(SUPER_USER_FULL_EDIT)
            .forAllStates()
            .name("Super User - Full Case Edit")
            .description("Allows super user to edit any core case field for data correction")
            .displayOrder(281)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRU, UserRole.CASEWORKER_SSCS_SUPERUSER)
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS)
            .fields();
        SuperUserFullEditAppealDetailsPage.apply(fields);
        SuperUserFullEditJointPartyDetailsPage.apply(fields);
        SuperUserFullEditOtherPartiesDetailsPage.apply(fields);
        SuperUserFullEditCaseClassificationPage.apply(fields);
        SuperUserFullEditDwpFlagsPage.apply(fields);
        SuperUserFullEditConfidentialityAndAdjustmentsPage.apply(fields);
        SuperUserFullEditCaseStatusAndNotesPage.apply(fields);
        SuperUserFullEditSystemFlagsPage.apply(fields);
        SuperUserFullEditAdjournmentDetailsPage.apply(fields);
    }
}
