package uk.gov.hmcts.reform.sscs.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code tcwDecisionStrikeOut} for case type {@code Benefit}.
 */
@Component
public class TcwDecisionStrikeOut implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String TCW_DECISION_STRIKE_OUT = "tcwDecisionStrikeOut";

    /**
     * Registers event {@code tcwDecisionStrikeOut}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        builder.event(TCW_DECISION_STRIKE_OUT)
            .forStateTransition(State.INTERLOCUTORY_REVIEW_STATE, State.DORMANT_APPEAL_STATE)
            .name("Strike out (TCW)")
            .displayOrder(1540)
            .showEventNotes()
            .explicitGrants();
    }
}
