package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code tcwReferToJudge} for case type {@code Benefit}.
 */
@Component
public class TcwReferToJudge implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String TCW_REFER_TO_JUDGE = "tcwReferToJudge";

    /**
     * Registers event {@code tcwReferToJudge}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(TCW_REFER_TO_JUDGE)
            .forAllStates()
            .name("Send to Judge")
            .displayOrder(1470)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_JUDGE)
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_REGISTRAR, UserRole.CASEWORKER_SSCS_SUPERUSER, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE)
            .fields();
        fields.page("1.0");
        fields.pageLabel("Leave a note for the judge");
        fields.mandatory(SscsCaseData::getPrePostHearing)
                    .publishAs("workType");
        fields.optional(SscsCaseData::getTempNoteDetail);
        fields.mandatory(SscsCaseData::getInterlocReviewState);
    }
}
