package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;
import uk.gov.hmcts.reform.sscs.ccd.event.page.TribunalCommunicationPage20;
import uk.gov.hmcts.reform.sscs.ccd.event.page.TribunalCommunicationReplyToTribunalQueryPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.TribunalCommunicationSelectTribunalCommunicationActionPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.TribunalCommunicationSelectTribunalReplyPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.TribunalCommunicationSelectTribunalRequestPage;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code tribunalCommunication} for case type {@code Benefit}.
 */
@Component
public class TribunalCommunication implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String TRIBUNAL_COMMUNICATION = "tribunalCommunication";

    /**
     * Registers event {@code tribunalCommunication}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(TRIBUNAL_COMMUNICATION)
            .forAllStates()
            .name("Communication with Tribunal")
            .displayOrder(545)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS)
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_DWPRESPONSEWRITER, UserRole.CASEWORKER_SSCS_HMRCRESPONSEWRITER, UserRole.CASEWORKER_SSCS_IBCARESPONSEWRITER, UserRole.CASEWORKER_SSCS_SUPERUSER)
            .fields();
        TribunalCommunicationSelectTribunalCommunicationActionPage.apply(fields);
        TribunalCommunicationPage20.apply(fields);
        TribunalCommunicationSelectTribunalRequestPage.apply(fields);
        TribunalCommunicationReplyToTribunalQueryPage.apply(fields);
        TribunalCommunicationSelectTribunalReplyPage.apply(fields);
    }
}
