package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.Appeal;
import uk.gov.hmcts.reform.sscs.ccd.domain.DateRange;
import uk.gov.hmcts.reform.sscs.ccd.domain.HearingOptions;
import uk.gov.hmcts.reform.sscs.ccd.domain.HearingSubtype;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code updateHearingType} for case type {@code Benefit}.
 */
@Component
public class UpdateHearingType implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String UPDATE_HEARING_TYPE = "updateHearingType";

    /**
     * Registers event {@code updateHearingType}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(UPDATE_HEARING_TYPE)
            .forStates(State.APPEAL_CREATED, State.VOID_STATE, State.INTERLOCUTORY_REVIEW_STATE, State.VALID_APPEAL, State.READY_TO_LIST, State.RESPONSE_RECEIVED, State.NOT_LISTABLE, State.HANDLING_ERROR, State.AWAIT_CONFIDENTIALITY_REQUIREMENTS, State.AWAIT_OTHER_PARTY_DATA)
            .name("Update hearing type")
            .description("Update Hearing Type")
            .displayOrder(1620)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS, UserRole.CASEWORKER_SSCS_JUDGE, UserRole.CASEWORKER_SSCS_REGISTRAR)
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_SUPERUSER, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE)
            .fields();
        fields.page("1.0");
        fields.pageLabel("Select hearing type");
        fields.complex(SscsCaseData::getAppeal)
                    .optional(Appeal::getHearingType)
                    .pageId("1.0")
                    .optional(Appeal::getHearingSubtype)
                    .pageId("1.0")
                    .complex(Appeal::getHearingSubtype)
                    .optional(HearingSubtype::getWantsHearingTypeTelephone)
                    .pageId("1.0").done()
                    .complex(Appeal::getHearingSubtype)
                    .optional(HearingSubtype::getHearingTelephoneNumber)
                    .pageId("1.0").done()
                    .complex(Appeal::getHearingSubtype)
                    .optional(HearingSubtype::getWantsHearingTypeVideo)
                    .pageId("1.0").done()
                    .complex(Appeal::getHearingSubtype)
                    .optional(HearingSubtype::getHearingVideoEmail)
                    .pageId("1.0").done()
                    .complex(Appeal::getHearingSubtype)
                    .optional(HearingSubtype::getWantsHearingTypeFaceToFace)
                    .pageId("1.0").done()
                    .optional(Appeal::getHearingOptions)
                    .pageId("1.0")
                    .complex(Appeal::getHearingOptions)
                    .optional(HearingOptions::getWantsToAttend)
                    .pageId("1.0").done()
                    .complex(Appeal::getHearingOptions)
                    .optional(HearingOptions::getWantsSupport)
                    .pageId("1.0").done()
                    .complex(Appeal::getHearingOptions)
                    .optional(HearingOptions::getLanguageInterpreter)
                    .fieldShowCondition("appeal.hearingOptions.wantsToAttend=\"Yes\" AND appeal.hearingOptions.wantsSupport=\"Yes\"")
                    .pageId("1.0").done()
                    .complex(Appeal::getHearingOptions)
                    .optional(HearingOptions::getLanguages)
                    .fieldShowCondition("appeal.hearingOptions.wantsToAttend=\"Yes\" AND appeal.hearingOptions.wantsSupport=\"Yes\" AND appeal.hearingOptions.languageInterpreter=\"Yes\"")
                    .pageId("1.0").done()
                    .complex(Appeal::getHearingOptions)
                    .optional(HearingOptions::getSignLanguageType)
                    .fieldShowCondition("appeal.hearingOptions.wantsToAttend=\"Yes\" AND appeal.hearingOptions.wantsSupport=\"Yes\"")
                    .pageId("1.0").done()
                    .complex(Appeal::getHearingOptions)
                    .optional(HearingOptions::getArrangements)
                    .fieldShowCondition("appeal.hearingOptions.wantsToAttend=\"Yes\" AND appeal.hearingOptions.wantsSupport=\"Yes\"")
                    .pageId("1.0").done()
                    .complex(Appeal::getHearingOptions)
                    .optional(HearingOptions::getOther)
                    .fieldShowCondition("appeal.hearingOptions.wantsToAttend=\"Yes\" AND appeal.hearingOptions.wantsSupport=\"Yes\"")
                    .pageId("1.0").done()
                    .complex(Appeal::getHearingOptions)
                    .optional(HearingOptions::getAgreeLessNotice)
                    .pageId("1.0").done()
                    .complex(Appeal::getHearingOptions)
                    .optional(HearingOptions::getScheduleHearing)
                    .pageId("1.0").done()
                    .complex(Appeal::getHearingOptions)
                    .optional(HearingOptions::getExcludeDates)
                    .fieldShowCondition("appeal.hearingOptions.wantsToAttend=\"Yes\" AND appeal.hearingOptions.scheduleHearing=\"Yes\"")
                    .pageId("1.0").done()
                    .complex(Appeal::getHearingOptions)
                    .complex(HearingOptions::getExcludeDates, DateRange.class)
                    .optional(DateRange::getStart)
                    .fieldShowCondition("appeal.hearingOptions.wantsToAttend=\"Yes\" AND appeal.hearingOptions.scheduleHearing=\"Yes\"")
                    .pageId("1.0").done().done()
                    .complex(Appeal::getHearingOptions)
                    .complex(HearingOptions::getExcludeDates, DateRange.class)
                    .optional(DateRange::getEnd)
                    .fieldShowCondition("appeal.hearingOptions.wantsToAttend=\"Yes\" AND appeal.hearingOptions.scheduleHearing=\"Yes\"")
                    .pageId("1.0").done().done().done();
    }
}
