package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;
import uk.gov.hmcts.reform.sscs.ccd.event.page.UpdateNotListableUpdateNotListableDirectionsFulfilledPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.UpdateNotListableUpdateNotListableDueDatePage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.UpdateNotListableUpdateNotListableInterlocReviewPage;
import uk.gov.hmcts.reform.sscs.ccd.event.page.UpdateNotListableUpdateNotListableNextStatePage;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code updateNotListable} for case type {@code Benefit}.
 */
@Component
public class UpdateNotListable implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String UPDATE_NOT_LISTABLE = "updateNotListable";

    /**
     * Registers event {@code updateNotListable}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(UPDATE_NOT_LISTABLE)
            .forState(State.NOT_LISTABLE)
            .name("Update not listable case")
            .displayOrder(1640)
            .showSummary()
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS)
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_SUPERUSER)
            .fields();
        UpdateNotListableUpdateNotListableInterlocReviewPage.apply(fields);
        UpdateNotListableUpdateNotListableDirectionsFulfilledPage.apply(fields);
        UpdateNotListableUpdateNotListableDueDatePage.apply(fields);
        UpdateNotListableUpdateNotListableNextStatePage.apply(fields);
    }
}
