package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.Appointee;
import uk.gov.hmcts.reform.sscs.ccd.domain.JointParty;
import uk.gov.hmcts.reform.sscs.ccd.domain.Name;
import uk.gov.hmcts.reform.sscs.ccd.domain.OtherParty;
import uk.gov.hmcts.reform.sscs.ccd.domain.ReasonableAdjustmentDetails;
import uk.gov.hmcts.reform.sscs.ccd.domain.ReasonableAdjustments;
import uk.gov.hmcts.reform.sscs.ccd.domain.Representative;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code updateReasonableAdjustment} for case type {@code Benefit}.
 */
@Component
public class UpdateReasonableAdjustment implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String UPDATE_REASONABLE_ADJUSTMENT = "updateReasonableAdjustment";

    /**
     * Registers event {@code updateReasonableAdjustment}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(UPDATE_REASONABLE_ADJUSTMENT)
            .forAllStates()
            .name("Update reasonable adjustment")
            .displayOrder(1660)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS)
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_SUPERUSER)
            .fields();
        fields.page("1.0");
        fields.mandatory(SscsCaseData::getReasonableAdjustmentChoice);
        fields.readonly(SscsCaseData::getAppeal)
                    .fieldShowCondition("reasonableAdjustmentChoice = \"DONOTSHOW\"");
        fields.complex(SscsCaseData::getJointParty)
                    .readonly(JointParty::getHasJointParty)
                    .fieldShowCondition("reasonableAdjustmentChoice = \"DONOTSHOW\"").done();
        fields.complex(SscsCaseData::getReasonableAdjustments)
                    .complex(ReasonableAdjustments::getAppellant)
                    .mandatory(ReasonableAdjustmentDetails::getWantsReasonableAdjustment)
                    .fieldShowCondition("reasonableAdjustmentChoice = \"alternativeLetterFormat\" AND appeal.appellant.isAppointee != \"Yes\"").done()
                    .complex(ReasonableAdjustments::getAppellant)
                    .mandatory(ReasonableAdjustmentDetails::getReasonableAdjustmentRequirements).done()
                    .complex(ReasonableAdjustments::getAppointee)
                    .mandatory(ReasonableAdjustmentDetails::getWantsReasonableAdjustment)
                    .fieldShowCondition("reasonableAdjustmentChoice = \"alternativeLetterFormat\" AND appeal.appellant.isAppointee = \"Yes\"").done()
                    .complex(ReasonableAdjustments::getAppointee)
                    .mandatory(ReasonableAdjustmentDetails::getReasonableAdjustmentRequirements).done()
                    .complex(ReasonableAdjustments::getRepresentative)
                    .mandatory(ReasonableAdjustmentDetails::getWantsReasonableAdjustment)
                    .fieldShowCondition("reasonableAdjustmentChoice = \"alternativeLetterFormat\" AND appeal.rep.hasRepresentative = \"Yes\"").done()
                    .complex(ReasonableAdjustments::getRepresentative)
                    .mandatory(ReasonableAdjustmentDetails::getReasonableAdjustmentRequirements).done()
                    .complex(ReasonableAdjustments::getJointParty)
                    .mandatory(ReasonableAdjustmentDetails::getWantsReasonableAdjustment)
                    .fieldShowCondition("reasonableAdjustmentChoice = \"alternativeLetterFormat\" AND jointParty = \"Yes\"").done()
                    .complex(ReasonableAdjustments::getJointParty)
                    .mandatory(ReasonableAdjustmentDetails::getReasonableAdjustmentRequirements).done().done()
                    .fieldShowCondition("reasonableAdjustmentChoice = \"alternativeLetterFormat\"");
        fields.mandatory(SscsCaseData::getShowOtherPartyDetails)
                    .fieldShowCondition("reasonableAdjustments=\"DoNotShow\"");
        fields.complex(SscsCaseData::getOtherParties).done()
                    .fieldShowCondition("reasonableAdjustmentChoice = \"alternativeLetterFormat\" AND showOtherPartyDetails=\"Yes\"");
        fields.complex(SscsCaseData::getOtherParties, OtherParty.class)
                    .readonly(OtherParty::getIsAppointee)
                    .fieldShowCondition("isAppointee = \"DONOTSHOW\"")
                    .readonly(OtherParty::getName)
                    .fieldShowCondition("isAppointee != \"Yes\"")
                    .complex(OtherParty::getName)
                    .readonly(Name::getFirstName).done()
                    .complex(OtherParty::getName)
                    .readonly(Name::getLastName).done()
                    .mandatory(OtherParty::getReasonableAdjustment)
                    .fieldShowCondition("isAppointee != \"Yes\"")
                    .complex(OtherParty::getReasonableAdjustment)
                    .mandatory(ReasonableAdjustmentDetails::getWantsReasonableAdjustment).done()
                    .complex(OtherParty::getReasonableAdjustment)
                    .mandatory(ReasonableAdjustmentDetails::getReasonableAdjustmentRequirements).done()
                    .optional(OtherParty::getAppointee)
                    .fieldShowCondition("isAppointee = \"Yes\"")
                    .complex(OtherParty::getAppointee)
                    .readonly(Appointee::getName).done()
                    .complex(OtherParty::getAppointee)
                    .complex(Appointee::getName)
                    .readonly(Name::getFirstName).done().done()
                    .complex(OtherParty::getAppointee)
                    .complex(Appointee::getName)
                    .readonly(Name::getLastName).done().done()
                    .mandatory(OtherParty::getAppointeeReasonableAdjustment)
                    .fieldShowCondition("isAppointee = \"Yes\"")
                    .complex(OtherParty::getAppointeeReasonableAdjustment)
                    .mandatory(ReasonableAdjustmentDetails::getWantsReasonableAdjustment).done()
                    .complex(OtherParty::getAppointeeReasonableAdjustment)
                    .mandatory(ReasonableAdjustmentDetails::getReasonableAdjustmentRequirements).done()
                    .complex(OtherParty::getAppointee)
                    .readonly(Appointee::getAddress)
                    .fieldShowCondition("reasonableAdjustmentChoice = \"DO NOT SHOW\"").done()
                    .complex(OtherParty::getAppointee)
                    .readonly(Appointee::getContact)
                    .fieldShowCondition("reasonableAdjustmentChoice = \"DO NOT SHOW\"").done()
                    .optional(OtherParty::getRep)
                    .fieldShowCondition("otherParties.rep.hasRepresentative = \"Yes\"")
                    .complex(OtherParty::getRep)
                    .readonly(Representative::getName).done()
                    .complex(OtherParty::getRep)
                    .complex(Representative::getName)
                    .readonly(Name::getFirstName).done().done()
                    .complex(OtherParty::getRep)
                    .complex(Representative::getName)
                    .readonly(Name::getLastName).done().done()
                    .mandatory(OtherParty::getRepReasonableAdjustment)
                    .fieldShowCondition("otherParties.rep.hasRepresentative = \"Yes\"")
                    .complex(OtherParty::getRepReasonableAdjustment)
                    .mandatory(ReasonableAdjustmentDetails::getWantsReasonableAdjustment).done()
                    .complex(OtherParty::getRepReasonableAdjustment)
                    .mandatory(ReasonableAdjustmentDetails::getReasonableAdjustmentRequirements).done()
                    .complex(OtherParty::getRep)
                    .readonly(Representative::getAddress)
                    .fieldShowCondition("reasonableAdjustmentChoice = \"DO NOT SHOW\"").done()
                    .complex(OtherParty::getRep)
                    .readonly(Representative::getContact)
                    .fieldShowCondition("reasonableAdjustmentChoice = \"DO NOT SHOW\"").done().done();
    }
}
