package uk.gov.hmcts.reform.sscs.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.EnvironmentFlags;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code updateHearingDetailsRequired} for case type {@code Benefit}.
 */
@Component
public class UpdateHearingDetailsRequiredNonprod implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String UPDATE_HEARING_DETAILS_REQUIRED = "updateHearingDetailsRequired";

    /**
     * Registers overlay event {@code updateHearingDetailsRequired} (active when CCD_DEF_ENV=prod).
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        if (EnvironmentFlags.flag("CCD_DEF_ENV", "prod")) return;
        builder.event(UPDATE_HEARING_DETAILS_REQUIRED)
            .forAllStates()
            .name("Update Hearing Details")
            .displayOrder(9998)
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE);
    }
}
