package uk.gov.hmcts.reform.sscs.ccd.event;

import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsWelshDocuments;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;
import uk.gov.hmcts.reform.sscs.ccd.domain.WorkAllocationFields;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code uploadWelshDocument} for case type {@code Benefit}.
 */
@Component
public class UploadWelshDocument implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String UPLOAD_WELSH_DOCUMENT = "uploadWelshDocument";

    /**
     * Registers event {@code uploadWelshDocument}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(UPLOAD_WELSH_DOCUMENT)
            .forAllStates()
            .name("Welsh - upload translated doc")
            .description("Upload Welsh translated documents")
            .displayOrder(1980)
            .showCondition("languagePreferenceWelsh=\"Yes\"")
            .showEventNotes()
            .explicitGrants()
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_SUPERUSER, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE)
            .fields();
        fields.page("1.0");
        fields.pageLabel("Upload Welsh documents");
        fields.complex(SscsCaseData::getWorkAllocationFields)
                    .mandatory(WorkAllocationFields::getUploadedWelshDocumentTypes)
                    .fieldShowCondition("[STATE]=\"DoNotShow\"")
                    .publishAs("scannedDocumentTypes").done();
        fields.optional(SscsCaseData::getOriginalDocuments);
        fields.complex(SscsCaseData::getSscsWelshPreviewDocuments).done();
        fields.complex(SscsCaseData::getSscsWelshPreviewDocuments, SscsWelshDocuments.class)
                    .mandatory(SscsWelshDocuments::getDocumentLink)
                    .optional(SscsWelshDocuments::getDocumentLanguage)
                    .optional(SscsWelshDocuments::getDocumentComment)
                    .optional(SscsWelshDocuments::getDocumentDateAdded).done();
    }
}
