package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;
import uk.gov.hmcts.reform.sscs.ccd.event.page.ValidSendToInterlocPage10;
import uk.gov.hmcts.reform.sscs.ccd.event.page.ValidSendToInterlocPage20;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code validSendToInterloc} for case type {@code Benefit}.
 */
@Component
public class ValidSendToInterloc implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String VALID_SEND_TO_INTERLOC = "validSendToInterloc";

    /**
     * Registers event {@code validSendToInterloc}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        var fields = builder.event(VALID_SEND_TO_INTERLOC)
            .forStates(State.APPEAL_CREATED, State.CLOSED, State.DORMANT_APPEAL_STATE, State.POST_HEARING, State.WITH_UT, State.HEARING, State.READY_TO_LIST, State.RESPONSE_RECEIVED, State.VALID_APPEAL, State.WITH_DWP, State.INTERLOCUTORY_REVIEW_STATE, State.INCOMPLETE_APPLICATION_INFORMATION_REQUESTED, State.NOT_LISTABLE, State.HANDLING_ERROR, State.AWAIT_CONFIDENTIALITY_REQUIREMENTS, State.AWAIT_OTHER_PARTY_DATA)
            .name("Send to interloc")
            .description("Send a case to a judge for review")
            .displayOrder(1450)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS, UserRole.CASEWORKER_SSCS_CALLAGENT, UserRole.CASEWORKER_SSCS_DWPRESPONSEWRITER, UserRole.CASEWORKER_SSCS_HMRCRESPONSEWRITER, UserRole.CASEWORKER_SSCS_JUDGE, UserRole.CASEWORKER_SSCS_REGISTRAR)
            .grant(Permission.CRUD, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_SUPERUSER, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE)
            .fields();
        ValidSendToInterlocPage10.apply(fields);
        ValidSendToInterlocPage20.apply(fields);
    }
}
