package uk.gov.hmcts.reform.sscs.ccd.event;

import java.util.EnumSet;
import java.util.Set;
import org.springframework.stereotype.Component;
import uk.gov.hmcts.ccd.sdk.api.CCDConfig;
import uk.gov.hmcts.ccd.sdk.api.ConfigBuilder;
import uk.gov.hmcts.ccd.sdk.api.Permission;
import uk.gov.hmcts.reform.sscs.ccd.domain.SscsCaseData;
import uk.gov.hmcts.reform.sscs.ccd.domain.State;
import uk.gov.hmcts.reform.sscs.ccd.domain.UserRole;

/**
 * Generated by ccd-definition-converter from Benefit on migration; owned by this service team.
 *
 * <p>Event {@code voidIncompleteApplication} for case type {@code Benefit}.
 */
@Component
public class VoidIncompleteApplication implements CCDConfig<SscsCaseData, State, UserRole> {
    /**
     * The CCD event ID.
     */
    public static final String VOID_INCOMPLETE_APPLICATION = "voidIncompleteApplication";

    /**
     * Registers event {@code voidIncompleteApplication}.
     *
     * @param builder the config builder
     */
    @Override
    public void configure(ConfigBuilder<SscsCaseData, State, UserRole> builder) {
        builder.event(VOID_INCOMPLETE_APPLICATION)
            .forStateTransition(EnumSet.of(State.INCOMPLETE_APPLICATION, State.INCOMPLETE_APPLICATION_INFORMATION_REQUESTED), State.VOID_STATE)
            .name("Void incomplete appeal")
            .description("Void non-valid appeal (Deprecated)")
            .displayOrder(1820)
            .showEventNotes()
            .explicitGrants()
            .grant(Set.of(Permission.R), UserRole.CASEWORKER_SSCS, UserRole.CASEWORKER_SSCS_CLERK, UserRole.CASEWORKER_SSCS_SUPERUSER, UserRole.CASEWORKER_SSCS_SYSTEMUPDATE);
    }
}
