name: Renovate Config Tests

on:
  push:
  pull_request:

env:
  LOG_LEVEL: debug

jobs:
  preset:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        file:
          - sscs-renovate
          - renovate
    env:
      RENOVATE_CONFIG_FILE: .github/${{ matrix.file }}.json

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: testing ${{ matrix.file }}
        run: npx -p renovate renovate-config-validator
