name: Renovate Config Tests

on:
  push:
  pull_request:

env:
  LOG_LEVEL: debug

jobs:
  preset:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        file:
          - sscs-renovate
          - renovate
    env:
      RENOVATE_CONFIG_FILE: .github/${{ matrix.file }}.json

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: testing ${{ matrix.file }}
        run: npx -p renovate renovate-config-validator
